// auto_diff: generated_differential
// This file is auto-generated by scripts/gen/generate-differential-tests.py.
// Do not edit manually. Re-generate with:
//   python3 scripts/gen/generate-differential-tests.py [--sample N]
//
// Generated at: 2026-05-15T16:08:21.968300
// Total fixtures: 25
//

#![allow(clippy::duplicate_mod)]

use std::path::Path;
use std::process::Command;
use std::time::Duration;

#[path = "common/iwasm_runtime.rs"]
mod iwasm_runtime;

#[path = "common/capability.rs"]
mod capability;

use capability::{iwasm_command, node_command};
use iwasm_runtime::run_iwasm_with_timeout_duration;
use ts2wasm_shared::test_helpers::temp_wasm_path;

fn assert_fixture_matches_node(fixture: &str) {
    let fixture_path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join(fixture);
    let output = temp_wasm_path(fixture);

    let node = node_command().arg(&fixture_path).output().unwrap();
    assert!(
        node.status.success(),
        "node failed for {fixture}\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&node.stdout),
        String::from_utf8_lossy(&node.stderr)
    );

    let build = Command::new(env!("CARGO_BIN_EXE_ts2wasm"))
        .arg("build")
        .arg(&fixture_path)
        .arg("-o")
        .arg(&output)
        .output()
        .unwrap();
    assert!(
        build.status.success(),
        "build failed for {fixture}\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&build.stdout),
        String::from_utf8_lossy(&build.stderr)
    );

    let iwasm =
        run_iwasm_with_timeout_duration(iwasm_command().arg(&output), Duration::from_secs(5))
            .unwrap_or_else(|e| panic!("iwasm execution failed for {fixture}: {e}"));
    assert!(
        !iwasm.timed_out,
        "iwasm timed out for {fixture}\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&iwasm.output.stdout),
        String::from_utf8_lossy(&iwasm.output.stderr)
    );
    assert!(
        iwasm.output.status.success(),
        "iwasm failed for {fixture}\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&iwasm.output.stdout),
        String::from_utf8_lossy(&iwasm.output.stderr)
    );

    let node_stdout = String::from_utf8_lossy(&node.stdout);
    let iwasm_stdout = String::from_utf8_lossy(&iwasm.output.stdout);
    assert_eq!(
        iwasm_stdout, node_stdout,
        "stdout mismatch for {fixture}\n  node:  {:?}\n  iwasm: {:?}",
        node_stdout, iwasm_stdout
    );
}

#[test]
fn auto_diff_arrays_objects_array_lowering_ts() {
    assert_fixture_matches_node("fixtures/arrays-objects/array-lowering.ts");
}

#[test]
fn auto_diff_arrays_objects_array_nonnumber_index_ts() {
    assert_fixture_matches_node("fixtures/arrays-objects/array-nonnumber-index.ts");
}

#[test]
fn auto_diff_arrays_objects_array_oob_ts() {
    assert_fixture_matches_node("fixtures/arrays-objects/array-oob.ts");
}

#[test]
fn auto_diff_arrays_objects_array_ts() {
    assert_fixture_matches_node("fixtures/arrays-objects/array.ts");
}

#[test]
fn auto_diff_arrays_objects_builtin_resolution_ts() {
    assert_fixture_matches_node("fixtures/arrays-objects/builtin-resolution.ts");
}

#[test]
fn auto_diff_arrays_objects_computed_property_ts() {
    assert_fixture_matches_node("fixtures/arrays-objects/computed-property.ts");
}

#[test]
fn auto_diff_arrays_objects_dynamic_property_assignment_ts() {
    assert_fixture_matches_node("fixtures/arrays-objects/dynamic-property-assignment.ts");
}

#[test]
fn auto_diff_arrays_objects_dynamic_property_ts() {
    assert_fixture_matches_node("fixtures/arrays-objects/dynamic-property.ts");
}

#[test]
fn auto_diff_arrays_objects_length_tag_ts() {
    assert_fixture_matches_node("fixtures/arrays-objects/length-tag.ts");
}

#[test]
fn auto_diff_arrays_objects_object_dup_key_ts() {
    assert_fixture_matches_node("fixtures/arrays-objects/object-dup-key.ts");
}

#[test]
fn auto_diff_arrays_objects_object_ts() {
    assert_fixture_matches_node("fixtures/arrays-objects/object.ts");
}

#[test]
fn auto_diff_arrays_objects_string_key_literal_ts() {
    assert_fixture_matches_node("fixtures/arrays-objects/string-key-literal.ts");
}

#[test]
fn auto_diff_arrays_objects_string_length_ts() {
    assert_fixture_matches_node("fixtures/arrays-objects/string-length.ts");
}

#[test]
fn auto_diff_arrow_functions_arrow_basic_ts() {
    assert_fixture_matches_node("fixtures/arrow-functions/arrow-basic.ts");
}

#[test]
fn auto_diff_async_await_async_arrow_ts() {
    assert_fixture_matches_node("fixtures/async-await/async-arrow.ts");
}

#[test]
fn auto_diff_async_await_async_exception_ts() {
    assert_fixture_matches_node("fixtures/async-await/async-exception.ts");
}

#[test]
fn auto_diff_async_await_async_nested_ts() {
    assert_fixture_matches_node("fixtures/async-await/async-nested.ts");
}

#[test]
fn auto_diff_async_await_async_void_ts() {
    assert_fixture_matches_node("fixtures/async-await/async-void.ts");
}

#[test]
fn auto_diff_async_await_await_sequence_ts() {
    assert_fixture_matches_node("fixtures/async-await/await-sequence.ts");
}

#[test]
fn auto_diff_async_await_basic_async_return_ts() {
    assert_fixture_matches_node("fixtures/async-await/basic-async-return.ts");
}

#[test]
fn auto_diff_atcoder_abc451_d_concat_power2_ts() {
    assert_fixture_matches_node("fixtures/atcoder/abc451-d-concat-power2.ts");
}

#[test]
fn auto_diff_basics_equality_equality_operators_ts() {
    assert_fixture_matches_node("fixtures/basics-equality/equality-operators.ts");
}

#[test]
fn auto_diff_basics_hello_exit_code_ts() {
    assert_fixture_matches_node("fixtures/basics-hello/exit-code.ts");
}

#[test]
fn auto_diff_basics_hello_hello_ts() {
    assert_fixture_matches_node("fixtures/basics-hello/hello.ts");
}

#[test]
fn auto_diff_basics_hello_stdin_empty_ts() {
    assert_fixture_matches_node("fixtures/basics-hello/stdin-empty.ts");
}
