/// Strongly-typed intrinsic identifier for runtime function calls.
///
/// This replaces the previous `RuntimeCall { runtime_fn: String }` pattern.
/// Each variant corresponds to a RuntimeFn in the backend-wasm catalog.
/// Auto-generated from backend-wasm spec files.
///
/// Pseudo-intrinsics (no corresponding RuntimeFn):
/// - ArrayPushMany: Expanded during IR lowering into ArrayPushGrow + ArrayPush
/// - HeapClosureCall: Direct heap closure calling convention
/// - PrivateFieldGet/Set/BrandCheck: Class private field operations
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RuntimeIntrinsic {
    ArrayGet,
    ArrayIndexPresent,
    ArrayBufferNew,
    ArrayPush,
    ArrayPushGrow,
    ArrayPop,
    ArraySlice,
    ArrayConcat,
    ArrayMapValueToString,
    ArrayMapUnaryPlus,
    ArrayMapStringSplit,
    ArrayMapArrayLikeIdentity,
    ArrayMapArrayLikeDouble,
    ArraySortNumeric,
    ArrayJoin,
    ArrayReverse,
    ArrayIndexOf,
    ArrayIncludes,
    ArrayFind,
    ArrayFindIndex,
    ArrayFindLast,
    ArrayFindLastIndex,
    ArrayFilter,
    ArrayEvery,
    ArraySome,
    ArrayReduce,
    ArrayReduceRight,
    ArrayLastIndexOf,
    ArrayForEach,
    ArrayMap,
    ArrayAt,
    ArrayFill,
    ArrayFlat,
    ArrayPushOrSpread,
    ArrayCopyWithin,
    ArrayWith,
    ArrayToReversed,
    ArrayToSorted,
    ArrayToSpliced,
    ArrayValues,
    ArrayKeys,
    ArrayEntries,
    ArrayShift,
    ArrayUnshift,
    ArraySplice,
    ArrayIsArray,
    MakeBigIntLiteral,
    BigIntToString,
    BigIntToBoolean,
    BigIntFromValue,
    BigIntAsIntN,
    BigIntAsUintN,
    BigIntUnaryMinus,
    BigIntAdd,
    BigIntSub,
    BigIntMul,
    BigIntPow,
    BigIntDiv,
    BigIntRem,
    BigIntDivisionByZeroRangeError,
    BigIntMixedArithmeticTypeError,
    BigIntStringComparisonBoundaryError,
    BigIntBitwiseNot,
    BigIntBitwiseAnd,
    BigIntBitwiseOr,
    BigIntBitwiseXor,
    BigIntLeftShift,
    BigIntRightShift,
    BigIntCompare,
    ReadStdinBytes,
    Write,
    Copy,
    ValueToStringInto,
    ErrorMessage,
    Log,
    PrivateBrandTypeError,
    AllocHeap,
    MemEqual,
    Index,
    GetLength,
    PropertyGet,
    DateNew,
    DateNewLive,
    DateNow,
    DateEpochMsNowNumber,
    DateGetTime,
    DateToString,
    DateGetLocalTimeField,
    DateToISOString,
    DateGetTimezoneOffset,
    DateGetUtcMilliseconds,
    DateGetUtcSeconds,
    DateGetUtcMinutes,
    DateGetUtcHours,
    DateGetUtcDay,
    DateGetUtcDate,
    DateGetUtcMonth,
    DateGetUtcFullYear,
    EncodeURI,
    DecodeURI,
    Escape,
    Unescape,
    FsReadFileSync,
    FsWriteFileSync,
    FsAppendFileSync,
    ProcessArgv,
    ProcessEnv,
    ObjectCreate,
    PropertySet,
    ProcessExit,
    PathJoin,
    PathResolve,
    PathBasename,
    PathDirname,
    CryptoRandomBytes,
    GetIterator,
    IteratorNext,
    JsonStringify,
    JsonParse,
    MapNew,
    MapGet,
    MapSet,
    MapHas,
    MapDelete,
    MapValuesArray,
    SetNew,
    SetAdd,
    SetHas,
    SetDelete,
    SetSize,
    SetClear,
    SetForEach,
    MapClear,
    MapSize,
    MapForEach,
    MapEntriesArray,
    SetFromArray,
    SetValuesArray,
    SetPrototypeAddGet,
    SetPrototypeAddSet,
    WeakMapNew,
    WeakMapSet,
    WeakMapGet,
    WeakMapHas,
    WeakMapDelete,
    WeakSetNew,
    WeakSetAdd,
    WeakSetHas,
    WeakSetDelete,
    MathFloor,
    MathCeil,
    MathRound,
    MathAbs,
    MathMax,
    MathMin,
    MathPow,
    MathRandom,
    MathTrunc,
    MathSign,
    ModuleRequire,
    ModuleExportsSet,
    ModuleExportsAssign,
    NumberFromI32,
    NumberToExponential,
    NumberToFixed,
    NumberToPrecision,
    NumberToI32,
    NumberIsNaN,
    NumberIsFinite,
    NumberIsInteger,
    NumberIsSafeInteger,
    PropertyDelete,
    PropertyHas,
    ObjectKeys,
    ObjectSpread,
    SpreadViaIterator,
    ObjectValues,
    ObjectEntries,
    ObjectHasOwnProperty,
    ObjectHasOwn,
    ObjectGetOwnPropertyDescriptor,
    ObjectGetPrototypeOf,
    ObjectSetPrototypeOf,
    ObjectFreeze,
    ObjectSeal,
    ObjectPreventExtensions,
    ObjectIsExtensible,
    ObjectIsSealed,
    ObjectIsFrozen,
    ObjectDefineProperty,
    ObjectAssign,
    ObjectIs,
    IsString,
    StringEqual,
    Add,
    AddFast,
    Sub,
    SubFast,
    Mul,
    MulFast,
    Div,
    DivFast,
    Mod,
    ModFast,
    BitwiseToI32,
    BitwiseAnd,
    BitwiseXor,
    BitwiseOr,
    Negate,
    Less,
    LessFast,
    LessEqual,
    LessEqualFast,
    Greater,
    GreaterFast,
    GreaterEqual,
    GreaterEqualFast,
    StrictEqual,
    EqualEqual,
    BangEqual,
    StrictNotEqual,
    And,
    Or,
    PromiseConstructor,
    PromiseResolve,
    PromiseReject,
    PromiseThen,
    PromiseCatch,
    PromiseAll,
    PromiseRace,
    RegExpTest,
    RegExpMatch,
    RegExpSearch,
    RegexpMatchInner,
    Concat,
    StringCharAt,
    StringAt,
    StringSubstring,
    StringSubstr,
    StringSlice,
    StringIndexOf,
    StringLastIndexOf,
    StringLocaleCompare,
    StringIncludes,
    StringPadStart,
    StringPadEnd,
    StringRepeat,
    StringSplit,
    StringTrim,
    StringTrimStart,
    StringTrimEnd,
    StringStartsWith,
    StringEndsWith,
    StringMatch,
    StringSearch,
    StringToUpperCase,
    StringToLowerCase,
    StringCharCodeAt,
    StringCodePointAt,
    StringIsWellFormed,
    StringToWellFormed,
    StringFromCharCode,
    StringFromCodePoint,
    StringReplace,
    StringReplaceAll,
    SymbolNew,
    SymbolFor,
    SymbolKeyFor,
    TaskPoll,
    TaskResult,
    TaskDrop,
    TruthyBool,
    Not,
    TypeOf,
    ValueOf,
    InstanceOf,
    IsNaN,
    ParseInt,
    ParseFloat,
    IsFinite,
    BooleanCoerce,
    NumberCoerce,
    TypedArrayFromArray,
    DataViewNew,
    DataViewGetInt32,
    DataViewSetInt32,
    DataViewGetFloat64,
    DataViewSetFloat64,
    /// Pseudo: expanded into ArrayPushGrow + ArrayPush during IR lowering
    ArrayPushMany,
    /// Pseudo: direct heap closure calling convention
    HeapClosureCall,
    /// Pseudo: class private field get
    PrivateFieldGet,
    /// Pseudo: class private field set
    PrivateFieldSet,
    /// Pseudo: class private brand check
    PrivateBrandCheck,
}

impl RuntimeIntrinsic {
    /// Returns all non-pseudo intrinsic variants.
    ///
    /// Pseudo-intrinsics (ArrayPushMany, HeapClosureCall, PrivateFieldGet,
    /// PrivateFieldSet, PrivateBrandCheck) are expanded during IR lowering
    /// and have no direct RuntimeFn equivalent.
    pub const fn all() -> &'static [RuntimeIntrinsic] {
        &[
            RuntimeIntrinsic::ArrayGet,
            RuntimeIntrinsic::ArrayIndexPresent,
            RuntimeIntrinsic::ArrayBufferNew,
            RuntimeIntrinsic::ArrayPush,
            RuntimeIntrinsic::ArrayPushGrow,
            RuntimeIntrinsic::ArrayPop,
            RuntimeIntrinsic::ArraySlice,
            RuntimeIntrinsic::ArrayConcat,
            RuntimeIntrinsic::ArrayMapValueToString,
            RuntimeIntrinsic::ArrayMapUnaryPlus,
            RuntimeIntrinsic::ArrayMapStringSplit,
            RuntimeIntrinsic::ArrayMapArrayLikeIdentity,
            RuntimeIntrinsic::ArrayMapArrayLikeDouble,
            RuntimeIntrinsic::ArraySortNumeric,
            RuntimeIntrinsic::ArrayJoin,
            RuntimeIntrinsic::ArrayReverse,
            RuntimeIntrinsic::ArrayIndexOf,
            RuntimeIntrinsic::ArrayIncludes,
            RuntimeIntrinsic::ArrayFind,
            RuntimeIntrinsic::ArrayFindIndex,
            RuntimeIntrinsic::ArrayFindLast,
            RuntimeIntrinsic::ArrayFindLastIndex,
            RuntimeIntrinsic::ArrayFilter,
            RuntimeIntrinsic::ArrayEvery,
            RuntimeIntrinsic::ArraySome,
            RuntimeIntrinsic::ArrayReduce,
            RuntimeIntrinsic::ArrayReduceRight,
            RuntimeIntrinsic::ArrayLastIndexOf,
            RuntimeIntrinsic::ArrayForEach,
            RuntimeIntrinsic::ArrayMap,
            RuntimeIntrinsic::ArrayAt,
            RuntimeIntrinsic::ArrayFill,
            RuntimeIntrinsic::ArrayFlat,
            RuntimeIntrinsic::ArrayPushOrSpread,
            RuntimeIntrinsic::ArrayCopyWithin,
            RuntimeIntrinsic::ArrayWith,
            RuntimeIntrinsic::ArrayToReversed,
            RuntimeIntrinsic::ArrayToSorted,
            RuntimeIntrinsic::ArrayToSpliced,
            RuntimeIntrinsic::ArrayValues,
            RuntimeIntrinsic::ArrayKeys,
            RuntimeIntrinsic::ArrayEntries,
            RuntimeIntrinsic::ArrayShift,
            RuntimeIntrinsic::ArrayUnshift,
            RuntimeIntrinsic::ArraySplice,
            RuntimeIntrinsic::ArrayIsArray,
            RuntimeIntrinsic::MakeBigIntLiteral,
            RuntimeIntrinsic::BigIntToString,
            RuntimeIntrinsic::BigIntToBoolean,
            RuntimeIntrinsic::BigIntFromValue,
            RuntimeIntrinsic::BigIntAsIntN,
            RuntimeIntrinsic::BigIntAsUintN,
            RuntimeIntrinsic::BigIntUnaryMinus,
            RuntimeIntrinsic::BigIntAdd,
            RuntimeIntrinsic::BigIntSub,
            RuntimeIntrinsic::BigIntMul,
            RuntimeIntrinsic::BigIntPow,
            RuntimeIntrinsic::BigIntDiv,
            RuntimeIntrinsic::BigIntRem,
            RuntimeIntrinsic::BigIntDivisionByZeroRangeError,
            RuntimeIntrinsic::BigIntMixedArithmeticTypeError,
            RuntimeIntrinsic::BigIntStringComparisonBoundaryError,
            RuntimeIntrinsic::BigIntBitwiseNot,
            RuntimeIntrinsic::BigIntBitwiseAnd,
            RuntimeIntrinsic::BigIntBitwiseOr,
            RuntimeIntrinsic::BigIntBitwiseXor,
            RuntimeIntrinsic::BigIntLeftShift,
            RuntimeIntrinsic::BigIntRightShift,
            RuntimeIntrinsic::BigIntCompare,
            RuntimeIntrinsic::ReadStdinBytes,
            RuntimeIntrinsic::Write,
            RuntimeIntrinsic::Copy,
            RuntimeIntrinsic::ValueToStringInto,
            RuntimeIntrinsic::ErrorMessage,
            RuntimeIntrinsic::Log,
            RuntimeIntrinsic::PrivateBrandTypeError,
            RuntimeIntrinsic::AllocHeap,
            RuntimeIntrinsic::MemEqual,
            RuntimeIntrinsic::Index,
            RuntimeIntrinsic::GetLength,
            RuntimeIntrinsic::PropertyGet,
            RuntimeIntrinsic::DateNew,
            RuntimeIntrinsic::DateNewLive,
            RuntimeIntrinsic::DateNow,
            RuntimeIntrinsic::DateEpochMsNowNumber,
            RuntimeIntrinsic::DateGetTime,
            RuntimeIntrinsic::DateToString,
            RuntimeIntrinsic::DateGetLocalTimeField,
            RuntimeIntrinsic::DateToISOString,
            RuntimeIntrinsic::DateGetTimezoneOffset,
            RuntimeIntrinsic::DateGetUtcMilliseconds,
            RuntimeIntrinsic::DateGetUtcSeconds,
            RuntimeIntrinsic::DateGetUtcMinutes,
            RuntimeIntrinsic::DateGetUtcHours,
            RuntimeIntrinsic::DateGetUtcDay,
            RuntimeIntrinsic::DateGetUtcDate,
            RuntimeIntrinsic::DateGetUtcMonth,
            RuntimeIntrinsic::DateGetUtcFullYear,
            RuntimeIntrinsic::EncodeURI,
            RuntimeIntrinsic::DecodeURI,
            RuntimeIntrinsic::Escape,
            RuntimeIntrinsic::Unescape,
            RuntimeIntrinsic::FsReadFileSync,
            RuntimeIntrinsic::FsWriteFileSync,
            RuntimeIntrinsic::FsAppendFileSync,
            RuntimeIntrinsic::ProcessArgv,
            RuntimeIntrinsic::ProcessEnv,
            RuntimeIntrinsic::ObjectCreate,
            RuntimeIntrinsic::PropertySet,
            RuntimeIntrinsic::ProcessExit,
            RuntimeIntrinsic::PathJoin,
            RuntimeIntrinsic::PathResolve,
            RuntimeIntrinsic::PathBasename,
            RuntimeIntrinsic::PathDirname,
            RuntimeIntrinsic::CryptoRandomBytes,
            RuntimeIntrinsic::GetIterator,
            RuntimeIntrinsic::IteratorNext,
            RuntimeIntrinsic::JsonStringify,
            RuntimeIntrinsic::JsonParse,
            RuntimeIntrinsic::MapNew,
            RuntimeIntrinsic::MapGet,
            RuntimeIntrinsic::MapSet,
            RuntimeIntrinsic::MapHas,
            RuntimeIntrinsic::MapDelete,
            RuntimeIntrinsic::MapValuesArray,
            RuntimeIntrinsic::SetNew,
            RuntimeIntrinsic::SetAdd,
            RuntimeIntrinsic::SetHas,
            RuntimeIntrinsic::SetDelete,
            RuntimeIntrinsic::SetSize,
            RuntimeIntrinsic::SetClear,
            RuntimeIntrinsic::SetForEach,
            RuntimeIntrinsic::MapClear,
            RuntimeIntrinsic::MapSize,
            RuntimeIntrinsic::MapForEach,
            RuntimeIntrinsic::MapEntriesArray,
            RuntimeIntrinsic::SetFromArray,
            RuntimeIntrinsic::SetValuesArray,
            RuntimeIntrinsic::SetPrototypeAddGet,
            RuntimeIntrinsic::SetPrototypeAddSet,
            RuntimeIntrinsic::WeakMapNew,
            RuntimeIntrinsic::WeakMapSet,
            RuntimeIntrinsic::WeakMapGet,
            RuntimeIntrinsic::WeakMapHas,
            RuntimeIntrinsic::WeakMapDelete,
            RuntimeIntrinsic::WeakSetNew,
            RuntimeIntrinsic::WeakSetAdd,
            RuntimeIntrinsic::WeakSetHas,
            RuntimeIntrinsic::WeakSetDelete,
            RuntimeIntrinsic::MathFloor,
            RuntimeIntrinsic::MathCeil,
            RuntimeIntrinsic::MathRound,
            RuntimeIntrinsic::MathAbs,
            RuntimeIntrinsic::MathMax,
            RuntimeIntrinsic::MathMin,
            RuntimeIntrinsic::MathPow,
            RuntimeIntrinsic::MathRandom,
            RuntimeIntrinsic::MathTrunc,
            RuntimeIntrinsic::MathSign,
            RuntimeIntrinsic::ModuleRequire,
            RuntimeIntrinsic::ModuleExportsSet,
            RuntimeIntrinsic::ModuleExportsAssign,
            RuntimeIntrinsic::NumberFromI32,
            RuntimeIntrinsic::NumberToExponential,
            RuntimeIntrinsic::NumberToFixed,
            RuntimeIntrinsic::NumberToPrecision,
            RuntimeIntrinsic::NumberToI32,
            RuntimeIntrinsic::NumberIsNaN,
            RuntimeIntrinsic::NumberIsFinite,
            RuntimeIntrinsic::NumberIsInteger,
            RuntimeIntrinsic::NumberIsSafeInteger,
            RuntimeIntrinsic::PropertyDelete,
            RuntimeIntrinsic::PropertyHas,
            RuntimeIntrinsic::ObjectKeys,
            RuntimeIntrinsic::ObjectSpread,
            RuntimeIntrinsic::SpreadViaIterator,
            RuntimeIntrinsic::ObjectValues,
            RuntimeIntrinsic::ObjectEntries,
            RuntimeIntrinsic::ObjectHasOwnProperty,
            RuntimeIntrinsic::ObjectHasOwn,
            RuntimeIntrinsic::ObjectGetOwnPropertyDescriptor,
            RuntimeIntrinsic::ObjectGetPrototypeOf,
            RuntimeIntrinsic::ObjectSetPrototypeOf,
            RuntimeIntrinsic::ObjectFreeze,
            RuntimeIntrinsic::ObjectSeal,
            RuntimeIntrinsic::ObjectPreventExtensions,
            RuntimeIntrinsic::ObjectIsExtensible,
            RuntimeIntrinsic::ObjectIsSealed,
            RuntimeIntrinsic::ObjectIsFrozen,
            RuntimeIntrinsic::ObjectDefineProperty,
            RuntimeIntrinsic::ObjectAssign,
            RuntimeIntrinsic::ObjectIs,
            RuntimeIntrinsic::IsString,
            RuntimeIntrinsic::StringEqual,
            RuntimeIntrinsic::Add,
            RuntimeIntrinsic::AddFast,
            RuntimeIntrinsic::Sub,
            RuntimeIntrinsic::SubFast,
            RuntimeIntrinsic::Mul,
            RuntimeIntrinsic::MulFast,
            RuntimeIntrinsic::Div,
            RuntimeIntrinsic::DivFast,
            RuntimeIntrinsic::Mod,
            RuntimeIntrinsic::ModFast,
            RuntimeIntrinsic::BitwiseToI32,
            RuntimeIntrinsic::BitwiseAnd,
            RuntimeIntrinsic::BitwiseXor,
            RuntimeIntrinsic::BitwiseOr,
            RuntimeIntrinsic::Negate,
            RuntimeIntrinsic::Less,
            RuntimeIntrinsic::LessFast,
            RuntimeIntrinsic::LessEqual,
            RuntimeIntrinsic::LessEqualFast,
            RuntimeIntrinsic::Greater,
            RuntimeIntrinsic::GreaterFast,
            RuntimeIntrinsic::GreaterEqual,
            RuntimeIntrinsic::GreaterEqualFast,
            RuntimeIntrinsic::StrictEqual,
            RuntimeIntrinsic::EqualEqual,
            RuntimeIntrinsic::BangEqual,
            RuntimeIntrinsic::StrictNotEqual,
            RuntimeIntrinsic::And,
            RuntimeIntrinsic::Or,
            RuntimeIntrinsic::PromiseConstructor,
            RuntimeIntrinsic::PromiseResolve,
            RuntimeIntrinsic::PromiseReject,
            RuntimeIntrinsic::PromiseThen,
            RuntimeIntrinsic::PromiseCatch,
            RuntimeIntrinsic::PromiseAll,
            RuntimeIntrinsic::PromiseRace,
            RuntimeIntrinsic::RegExpTest,
            RuntimeIntrinsic::RegExpMatch,
            RuntimeIntrinsic::RegExpSearch,
            RuntimeIntrinsic::RegexpMatchInner,
            RuntimeIntrinsic::Concat,
            RuntimeIntrinsic::StringCharAt,
            RuntimeIntrinsic::StringAt,
            RuntimeIntrinsic::StringSubstring,
            RuntimeIntrinsic::StringSubstr,
            RuntimeIntrinsic::StringSlice,
            RuntimeIntrinsic::StringIndexOf,
            RuntimeIntrinsic::StringLastIndexOf,
            RuntimeIntrinsic::StringLocaleCompare,
            RuntimeIntrinsic::StringIncludes,
            RuntimeIntrinsic::StringPadStart,
            RuntimeIntrinsic::StringPadEnd,
            RuntimeIntrinsic::StringRepeat,
            RuntimeIntrinsic::StringSplit,
            RuntimeIntrinsic::StringTrim,
            RuntimeIntrinsic::StringTrimStart,
            RuntimeIntrinsic::StringTrimEnd,
            RuntimeIntrinsic::StringStartsWith,
            RuntimeIntrinsic::StringEndsWith,
            RuntimeIntrinsic::StringMatch,
            RuntimeIntrinsic::StringSearch,
            RuntimeIntrinsic::StringToUpperCase,
            RuntimeIntrinsic::StringToLowerCase,
            RuntimeIntrinsic::StringCharCodeAt,
            RuntimeIntrinsic::StringCodePointAt,
            RuntimeIntrinsic::StringIsWellFormed,
            RuntimeIntrinsic::StringToWellFormed,
            RuntimeIntrinsic::StringFromCharCode,
            RuntimeIntrinsic::StringFromCodePoint,
            RuntimeIntrinsic::StringReplace,
            RuntimeIntrinsic::StringReplaceAll,
            RuntimeIntrinsic::SymbolNew,
            RuntimeIntrinsic::SymbolFor,
            RuntimeIntrinsic::SymbolKeyFor,
            RuntimeIntrinsic::TaskPoll,
            RuntimeIntrinsic::TaskResult,
            RuntimeIntrinsic::TaskDrop,
            RuntimeIntrinsic::TruthyBool,
            RuntimeIntrinsic::Not,
            RuntimeIntrinsic::TypeOf,
            RuntimeIntrinsic::ValueOf,
            RuntimeIntrinsic::InstanceOf,
            RuntimeIntrinsic::IsNaN,
            RuntimeIntrinsic::ParseInt,
            RuntimeIntrinsic::ParseFloat,
            RuntimeIntrinsic::IsFinite,
            RuntimeIntrinsic::BooleanCoerce,
            RuntimeIntrinsic::NumberCoerce,
            RuntimeIntrinsic::TypedArrayFromArray,
            RuntimeIntrinsic::DataViewNew,
            RuntimeIntrinsic::DataViewGetInt32,
            RuntimeIntrinsic::DataViewSetInt32,
            RuntimeIntrinsic::DataViewGetFloat64,
            RuntimeIntrinsic::DataViewSetFloat64,
        ]
    }

    /// Returns the RuntimeFn name string for backend dispatch.
    pub const fn name(self) -> &'static str {
        match self {
            RuntimeIntrinsic::ArrayGet => "ArrayGet",
            RuntimeIntrinsic::ArrayIndexPresent => "ArrayIndexPresent",
            RuntimeIntrinsic::ArrayBufferNew => "ArrayBufferNew",
            RuntimeIntrinsic::ArrayPush => "ArrayPush",
            RuntimeIntrinsic::ArrayPushGrow => "ArrayPushGrow",
            RuntimeIntrinsic::ArrayPop => "ArrayPop",
            RuntimeIntrinsic::ArraySlice => "ArraySlice",
            RuntimeIntrinsic::ArrayConcat => "ArrayConcat",
            RuntimeIntrinsic::ArrayMapValueToString => "ArrayMapValueToString",
            RuntimeIntrinsic::ArrayMapUnaryPlus => "ArrayMapUnaryPlus",
            RuntimeIntrinsic::ArrayMapStringSplit => "ArrayMapStringSplit",
            RuntimeIntrinsic::ArrayMapArrayLikeIdentity => "ArrayMapArrayLikeIdentity",
            RuntimeIntrinsic::ArrayMapArrayLikeDouble => "ArrayMapArrayLikeDouble",
            RuntimeIntrinsic::ArraySortNumeric => "ArraySortNumeric",
            RuntimeIntrinsic::ArrayJoin => "ArrayJoin",
            RuntimeIntrinsic::ArrayReverse => "ArrayReverse",
            RuntimeIntrinsic::ArrayIndexOf => "ArrayIndexOf",
            RuntimeIntrinsic::ArrayIncludes => "ArrayIncludes",
            RuntimeIntrinsic::ArrayFind => "ArrayFind",
            RuntimeIntrinsic::ArrayFindIndex => "ArrayFindIndex",
            RuntimeIntrinsic::ArrayFindLast => "ArrayFindLast",
            RuntimeIntrinsic::ArrayFindLastIndex => "ArrayFindLastIndex",
            RuntimeIntrinsic::ArrayFilter => "ArrayFilter",
            RuntimeIntrinsic::ArrayEvery => "ArrayEvery",
            RuntimeIntrinsic::ArraySome => "ArraySome",
            RuntimeIntrinsic::ArrayReduce => "ArrayReduce",
            RuntimeIntrinsic::ArrayReduceRight => "ArrayReduceRight",
            RuntimeIntrinsic::ArrayLastIndexOf => "ArrayLastIndexOf",
            RuntimeIntrinsic::ArrayForEach => "ArrayForEach",
            RuntimeIntrinsic::ArrayMap => "ArrayMap",
            RuntimeIntrinsic::ArrayAt => "ArrayAt",
            RuntimeIntrinsic::ArrayFill => "ArrayFill",
            RuntimeIntrinsic::ArrayFlat => "ArrayFlat",
            RuntimeIntrinsic::ArrayPushOrSpread => "ArrayPushOrSpread",
            RuntimeIntrinsic::ArrayCopyWithin => "ArrayCopyWithin",
            RuntimeIntrinsic::ArrayWith => "ArrayWith",
            RuntimeIntrinsic::ArrayToReversed => "ArrayToReversed",
            RuntimeIntrinsic::ArrayToSorted => "ArrayToSorted",
            RuntimeIntrinsic::ArrayToSpliced => "ArrayToSpliced",
            RuntimeIntrinsic::ArrayValues => "ArrayValues",
            RuntimeIntrinsic::ArrayKeys => "ArrayKeys",
            RuntimeIntrinsic::ArrayEntries => "ArrayEntries",
            RuntimeIntrinsic::ArrayShift => "ArrayShift",
            RuntimeIntrinsic::ArrayUnshift => "ArrayUnshift",
            RuntimeIntrinsic::ArraySplice => "ArraySplice",
            RuntimeIntrinsic::ArrayIsArray => "ArrayIsArray",
            RuntimeIntrinsic::MakeBigIntLiteral => "MakeBigIntLiteral",
            RuntimeIntrinsic::BigIntToString => "BigIntToString",
            RuntimeIntrinsic::BigIntToBoolean => "BigIntToBoolean",
            RuntimeIntrinsic::BigIntFromValue => "BigIntFromValue",
            RuntimeIntrinsic::BigIntAsIntN => "BigIntAsIntN",
            RuntimeIntrinsic::BigIntAsUintN => "BigIntAsUintN",
            RuntimeIntrinsic::BigIntUnaryMinus => "BigIntUnaryMinus",
            RuntimeIntrinsic::BigIntAdd => "BigIntAdd",
            RuntimeIntrinsic::BigIntSub => "BigIntSub",
            RuntimeIntrinsic::BigIntMul => "BigIntMul",
            RuntimeIntrinsic::BigIntPow => "BigIntPow",
            RuntimeIntrinsic::BigIntDiv => "BigIntDiv",
            RuntimeIntrinsic::BigIntRem => "BigIntRem",
            RuntimeIntrinsic::BigIntDivisionByZeroRangeError => "BigIntDivisionByZeroRangeError",
            RuntimeIntrinsic::BigIntMixedArithmeticTypeError => "BigIntMixedArithmeticTypeError",
            RuntimeIntrinsic::BigIntStringComparisonBoundaryError => {
                "BigIntStringComparisonBoundaryError"
            }
            RuntimeIntrinsic::BigIntBitwiseNot => "BigIntBitwiseNot",
            RuntimeIntrinsic::BigIntBitwiseAnd => "BigIntBitwiseAnd",
            RuntimeIntrinsic::BigIntBitwiseOr => "BigIntBitwiseOr",
            RuntimeIntrinsic::BigIntBitwiseXor => "BigIntBitwiseXor",
            RuntimeIntrinsic::BigIntLeftShift => "BigIntLeftShift",
            RuntimeIntrinsic::BigIntRightShift => "BigIntRightShift",
            RuntimeIntrinsic::BigIntCompare => "BigIntCompare",
            RuntimeIntrinsic::ReadStdinBytes => "ReadStdinBytes",
            RuntimeIntrinsic::Write => "Write",
            RuntimeIntrinsic::Copy => "Copy",
            RuntimeIntrinsic::ValueToStringInto => "ValueToStringInto",
            RuntimeIntrinsic::ErrorMessage => "ErrorMessage",
            RuntimeIntrinsic::Log => "Log",
            RuntimeIntrinsic::PrivateBrandTypeError => "PrivateBrandTypeError",
            RuntimeIntrinsic::AllocHeap => "AllocHeap",
            RuntimeIntrinsic::MemEqual => "MemEqual",
            RuntimeIntrinsic::Index => "Index",
            RuntimeIntrinsic::GetLength => "GetLength",
            RuntimeIntrinsic::PropertyGet => "PropertyGet",
            RuntimeIntrinsic::DateNew => "DateNew",
            RuntimeIntrinsic::DateNewLive => "DateNewLive",
            RuntimeIntrinsic::DateNow => "DateNow",
            RuntimeIntrinsic::DateEpochMsNowNumber => "DateEpochMsNowNumber",
            RuntimeIntrinsic::DateGetTime => "DateGetTime",
            RuntimeIntrinsic::DateToString => "DateToString",
            RuntimeIntrinsic::DateGetLocalTimeField => "DateGetLocalTimeField",
            RuntimeIntrinsic::DateToISOString => "DateToISOString",
            RuntimeIntrinsic::DateGetTimezoneOffset => "DateGetTimezoneOffset",
            RuntimeIntrinsic::DateGetUtcMilliseconds => "DateGetUtcMilliseconds",
            RuntimeIntrinsic::DateGetUtcSeconds => "DateGetUtcSeconds",
            RuntimeIntrinsic::DateGetUtcMinutes => "DateGetUtcMinutes",
            RuntimeIntrinsic::DateGetUtcHours => "DateGetUtcHours",
            RuntimeIntrinsic::DateGetUtcDay => "DateGetUtcDay",
            RuntimeIntrinsic::DateGetUtcDate => "DateGetUtcDate",
            RuntimeIntrinsic::DateGetUtcMonth => "DateGetUtcMonth",
            RuntimeIntrinsic::DateGetUtcFullYear => "DateGetUtcFullYear",
            RuntimeIntrinsic::EncodeURI => "EncodeURI",
            RuntimeIntrinsic::DecodeURI => "DecodeURI",
            RuntimeIntrinsic::Escape => "Escape",
            RuntimeIntrinsic::Unescape => "Unescape",
            RuntimeIntrinsic::FsReadFileSync => "FsReadFileSync",
            RuntimeIntrinsic::FsWriteFileSync => "FsWriteFileSync",
            RuntimeIntrinsic::FsAppendFileSync => "FsAppendFileSync",
            RuntimeIntrinsic::ProcessArgv => "ProcessArgv",
            RuntimeIntrinsic::ProcessEnv => "ProcessEnv",
            RuntimeIntrinsic::ObjectCreate => "ObjectCreate",
            RuntimeIntrinsic::PropertySet => "PropertySet",
            RuntimeIntrinsic::ProcessExit => "ProcessExit",
            RuntimeIntrinsic::PathJoin => "PathJoin",
            RuntimeIntrinsic::PathResolve => "PathResolve",
            RuntimeIntrinsic::PathBasename => "PathBasename",
            RuntimeIntrinsic::PathDirname => "PathDirname",
            RuntimeIntrinsic::CryptoRandomBytes => "CryptoRandomBytes",
            RuntimeIntrinsic::GetIterator => "GetIterator",
            RuntimeIntrinsic::IteratorNext => "IteratorNext",
            RuntimeIntrinsic::JsonStringify => "JsonStringify",
            RuntimeIntrinsic::JsonParse => "JsonParse",
            RuntimeIntrinsic::MapNew => "MapNew",
            RuntimeIntrinsic::MapGet => "MapGet",
            RuntimeIntrinsic::MapSet => "MapSet",
            RuntimeIntrinsic::MapHas => "MapHas",
            RuntimeIntrinsic::MapDelete => "MapDelete",
            RuntimeIntrinsic::MapValuesArray => "MapValuesArray",
            RuntimeIntrinsic::SetNew => "SetNew",
            RuntimeIntrinsic::SetAdd => "SetAdd",
            RuntimeIntrinsic::SetHas => "SetHas",
            RuntimeIntrinsic::SetDelete => "SetDelete",
            RuntimeIntrinsic::SetSize => "SetSize",
            RuntimeIntrinsic::SetClear => "SetClear",
            RuntimeIntrinsic::SetForEach => "SetForEach",
            RuntimeIntrinsic::MapClear => "MapClear",
            RuntimeIntrinsic::MapSize => "MapSize",
            RuntimeIntrinsic::MapForEach => "MapForEach",
            RuntimeIntrinsic::MapEntriesArray => "MapEntriesArray",
            RuntimeIntrinsic::SetFromArray => "SetFromArray",
            RuntimeIntrinsic::SetValuesArray => "SetValuesArray",
            RuntimeIntrinsic::SetPrototypeAddGet => "SetPrototypeAddGet",
            RuntimeIntrinsic::SetPrototypeAddSet => "SetPrototypeAddSet",
            RuntimeIntrinsic::WeakMapNew => "WeakMapNew",
            RuntimeIntrinsic::WeakMapSet => "WeakMapSet",
            RuntimeIntrinsic::WeakMapGet => "WeakMapGet",
            RuntimeIntrinsic::WeakMapHas => "WeakMapHas",
            RuntimeIntrinsic::WeakMapDelete => "WeakMapDelete",
            RuntimeIntrinsic::WeakSetNew => "WeakSetNew",
            RuntimeIntrinsic::WeakSetAdd => "WeakSetAdd",
            RuntimeIntrinsic::WeakSetHas => "WeakSetHas",
            RuntimeIntrinsic::WeakSetDelete => "WeakSetDelete",
            RuntimeIntrinsic::MathFloor => "MathFloor",
            RuntimeIntrinsic::MathCeil => "MathCeil",
            RuntimeIntrinsic::MathRound => "MathRound",
            RuntimeIntrinsic::MathAbs => "MathAbs",
            RuntimeIntrinsic::MathMax => "MathMax",
            RuntimeIntrinsic::MathMin => "MathMin",
            RuntimeIntrinsic::MathPow => "MathPow",
            RuntimeIntrinsic::MathRandom => "MathRandom",
            RuntimeIntrinsic::MathTrunc => "MathTrunc",
            RuntimeIntrinsic::MathSign => "MathSign",
            RuntimeIntrinsic::ModuleRequire => "ModuleRequire",
            RuntimeIntrinsic::ModuleExportsSet => "ModuleExportsSet",
            RuntimeIntrinsic::ModuleExportsAssign => "ModuleExportsAssign",
            RuntimeIntrinsic::NumberFromI32 => "NumberFromI32",
            RuntimeIntrinsic::NumberToExponential => "NumberToExponential",
            RuntimeIntrinsic::NumberToFixed => "NumberToFixed",
            RuntimeIntrinsic::NumberToPrecision => "NumberToPrecision",
            RuntimeIntrinsic::NumberToI32 => "NumberToI32",
            RuntimeIntrinsic::NumberIsNaN => "NumberIsNaN",
            RuntimeIntrinsic::NumberIsFinite => "NumberIsFinite",
            RuntimeIntrinsic::NumberIsInteger => "NumberIsInteger",
            RuntimeIntrinsic::NumberIsSafeInteger => "NumberIsSafeInteger",
            RuntimeIntrinsic::PropertyDelete => "PropertyDelete",
            RuntimeIntrinsic::PropertyHas => "PropertyHas",
            RuntimeIntrinsic::ObjectKeys => "ObjectKeys",
            RuntimeIntrinsic::ObjectSpread => "ObjectSpread",
            RuntimeIntrinsic::SpreadViaIterator => "SpreadViaIterator",
            RuntimeIntrinsic::ObjectValues => "ObjectValues",
            RuntimeIntrinsic::ObjectEntries => "ObjectEntries",
            RuntimeIntrinsic::ObjectHasOwnProperty => "ObjectHasOwnProperty",
            RuntimeIntrinsic::ObjectHasOwn => "ObjectHasOwn",
            RuntimeIntrinsic::ObjectGetOwnPropertyDescriptor => "ObjectGetOwnPropertyDescriptor",
            RuntimeIntrinsic::ObjectGetPrototypeOf => "ObjectGetPrototypeOf",
            RuntimeIntrinsic::ObjectSetPrototypeOf => "ObjectSetPrototypeOf",
            RuntimeIntrinsic::ObjectFreeze => "ObjectFreeze",
            RuntimeIntrinsic::ObjectSeal => "ObjectSeal",
            RuntimeIntrinsic::ObjectPreventExtensions => "ObjectPreventExtensions",
            RuntimeIntrinsic::ObjectIsExtensible => "ObjectIsExtensible",
            RuntimeIntrinsic::ObjectIsSealed => "ObjectIsSealed",
            RuntimeIntrinsic::ObjectIsFrozen => "ObjectIsFrozen",
            RuntimeIntrinsic::ObjectDefineProperty => "ObjectDefineProperty",
            RuntimeIntrinsic::ObjectAssign => "ObjectAssign",
            RuntimeIntrinsic::ObjectIs => "ObjectIs",
            RuntimeIntrinsic::IsString => "IsString",
            RuntimeIntrinsic::StringEqual => "StringEqual",
            RuntimeIntrinsic::Add => "Add",
            RuntimeIntrinsic::AddFast => "AddFast",
            RuntimeIntrinsic::Sub => "Sub",
            RuntimeIntrinsic::SubFast => "SubFast",
            RuntimeIntrinsic::Mul => "Mul",
            RuntimeIntrinsic::MulFast => "MulFast",
            RuntimeIntrinsic::Div => "Div",
            RuntimeIntrinsic::DivFast => "DivFast",
            RuntimeIntrinsic::Mod => "Mod",
            RuntimeIntrinsic::ModFast => "ModFast",
            RuntimeIntrinsic::BitwiseToI32 => "BitwiseToI32",
            RuntimeIntrinsic::BitwiseAnd => "BitwiseAnd",
            RuntimeIntrinsic::BitwiseXor => "BitwiseXor",
            RuntimeIntrinsic::BitwiseOr => "BitwiseOr",
            RuntimeIntrinsic::Negate => "Negate",
            RuntimeIntrinsic::Less => "Less",
            RuntimeIntrinsic::LessFast => "LessFast",
            RuntimeIntrinsic::LessEqual => "LessEqual",
            RuntimeIntrinsic::LessEqualFast => "LessEqualFast",
            RuntimeIntrinsic::Greater => "Greater",
            RuntimeIntrinsic::GreaterFast => "GreaterFast",
            RuntimeIntrinsic::GreaterEqual => "GreaterEqual",
            RuntimeIntrinsic::GreaterEqualFast => "GreaterEqualFast",
            RuntimeIntrinsic::StrictEqual => "StrictEqual",
            RuntimeIntrinsic::EqualEqual => "EqualEqual",
            RuntimeIntrinsic::BangEqual => "BangEqual",
            RuntimeIntrinsic::StrictNotEqual => "StrictNotEqual",
            RuntimeIntrinsic::And => "And",
            RuntimeIntrinsic::Or => "Or",
            RuntimeIntrinsic::PromiseConstructor => "PromiseConstructor",
            RuntimeIntrinsic::PromiseResolve => "PromiseResolve",
            RuntimeIntrinsic::PromiseReject => "PromiseReject",
            RuntimeIntrinsic::PromiseThen => "PromiseThen",
            RuntimeIntrinsic::PromiseCatch => "PromiseCatch",
            RuntimeIntrinsic::PromiseAll => "PromiseAll",
            RuntimeIntrinsic::PromiseRace => "PromiseRace",
            RuntimeIntrinsic::RegExpTest => "RegExpTest",
            RuntimeIntrinsic::RegExpMatch => "RegExpMatch",
            RuntimeIntrinsic::RegExpSearch => "RegExpSearch",
            RuntimeIntrinsic::RegexpMatchInner => "RegexpMatchInner",
            RuntimeIntrinsic::Concat => "Concat",
            RuntimeIntrinsic::StringCharAt => "StringCharAt",
            RuntimeIntrinsic::StringAt => "StringAt",
            RuntimeIntrinsic::StringSubstring => "StringSubstring",
            RuntimeIntrinsic::StringSubstr => "StringSubstr",
            RuntimeIntrinsic::StringSlice => "StringSlice",
            RuntimeIntrinsic::StringIndexOf => "StringIndexOf",
            RuntimeIntrinsic::StringLastIndexOf => "StringLastIndexOf",
            RuntimeIntrinsic::StringLocaleCompare => "StringLocaleCompare",
            RuntimeIntrinsic::StringIncludes => "StringIncludes",
            RuntimeIntrinsic::StringPadStart => "StringPadStart",
            RuntimeIntrinsic::StringPadEnd => "StringPadEnd",
            RuntimeIntrinsic::StringRepeat => "StringRepeat",
            RuntimeIntrinsic::StringSplit => "StringSplit",
            RuntimeIntrinsic::StringTrim => "StringTrim",
            RuntimeIntrinsic::StringTrimStart => "StringTrimStart",
            RuntimeIntrinsic::StringTrimEnd => "StringTrimEnd",
            RuntimeIntrinsic::StringStartsWith => "StringStartsWith",
            RuntimeIntrinsic::StringEndsWith => "StringEndsWith",
            RuntimeIntrinsic::StringMatch => "StringMatch",
            RuntimeIntrinsic::StringSearch => "StringSearch",
            RuntimeIntrinsic::StringToUpperCase => "StringToUpperCase",
            RuntimeIntrinsic::StringToLowerCase => "StringToLowerCase",
            RuntimeIntrinsic::StringCharCodeAt => "StringCharCodeAt",
            RuntimeIntrinsic::StringCodePointAt => "StringCodePointAt",
            RuntimeIntrinsic::StringIsWellFormed => "StringIsWellFormed",
            RuntimeIntrinsic::StringToWellFormed => "StringToWellFormed",
            RuntimeIntrinsic::StringFromCharCode => "StringFromCharCode",
            RuntimeIntrinsic::StringFromCodePoint => "StringFromCodePoint",
            RuntimeIntrinsic::StringReplace => "StringReplace",
            RuntimeIntrinsic::StringReplaceAll => "StringReplaceAll",
            RuntimeIntrinsic::SymbolNew => "SymbolNew",
            RuntimeIntrinsic::SymbolFor => "SymbolFor",
            RuntimeIntrinsic::SymbolKeyFor => "SymbolKeyFor",
            RuntimeIntrinsic::TaskPoll => "TaskPoll",
            RuntimeIntrinsic::TaskResult => "TaskResult",
            RuntimeIntrinsic::TaskDrop => "TaskDrop",
            RuntimeIntrinsic::TruthyBool => "TruthyBool",
            RuntimeIntrinsic::Not => "Not",
            RuntimeIntrinsic::TypeOf => "TypeOf",
            RuntimeIntrinsic::ValueOf => "ValueOf",
            RuntimeIntrinsic::InstanceOf => "InstanceOf",
            RuntimeIntrinsic::IsNaN => "IsNaN",
            RuntimeIntrinsic::ParseInt => "ParseInt",
            RuntimeIntrinsic::ParseFloat => "ParseFloat",
            RuntimeIntrinsic::IsFinite => "IsFinite",
            RuntimeIntrinsic::BooleanCoerce => "BooleanCoerce",
            RuntimeIntrinsic::NumberCoerce => "NumberCoerce",
            RuntimeIntrinsic::TypedArrayFromArray => "TypedArrayFromArray",
            RuntimeIntrinsic::DataViewNew => "DataViewNew",
            RuntimeIntrinsic::DataViewGetInt32 => "DataViewGetInt32",
            RuntimeIntrinsic::DataViewSetInt32 => "DataViewSetInt32",
            RuntimeIntrinsic::DataViewGetFloat64 => "DataViewGetFloat64",
            RuntimeIntrinsic::DataViewSetFloat64 => "DataViewSetFloat64",
            RuntimeIntrinsic::ArrayPushMany => "ArrayPushMany",
            RuntimeIntrinsic::HeapClosureCall => "HeapClosureCall",
            RuntimeIntrinsic::PrivateFieldGet => "PrivateFieldGet",
            RuntimeIntrinsic::PrivateFieldSet => "PrivateFieldSet",
            RuntimeIntrinsic::PrivateBrandCheck => "PrivateBrandCheck",
        }
    }
}
