//! Builtin JavaScript constructor registry.
//!
//! Each entry describes the ECMAScript-facing metadata (`name`, `length`,
//! `prototype`) and whether `[[Construct]]` / `Reflect.construct` should
//! treat the value as a constructor.

use ts2wasm_runtime_abi::ValueTag;

/// Identifies a well-known builtin constructor global.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u16)]
pub enum BuiltinConstructorKind {
    Object,
    Function,
    Boolean,
    Number,
    String,
    Array,
    Date,
    RegExp,
    Map,
    Set,
    WeakMap,
    WeakSet,
    Symbol,
    Promise,
    BigInt,
    Proxy,
    ArrayBuffer,
    SharedArrayBuffer,
    DataView,
    Int8Array,
    Uint8Array,
    Uint8ClampedArray,
    Int16Array,
    Uint16Array,
    Int32Array,
    Uint32Array,
    Float16Array,
    Float32Array,
    Float64Array,
    BigInt64Array,
    BigUint64Array,
    Error,
    EvalError,
    RangeError,
    ReferenceError,
    SyntaxError,
    TypeError,
    URIError,
    AggregateError,
    FinalizationRegistry,
    WeakRef,
    Iterator,
    AsyncIterator,
    SuppressedError,
    DisposableStack,
    AsyncDisposableStack,
}

/// Static metadata for one builtin constructor global.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BuiltinConstructorSpec {
    pub kind: BuiltinConstructorKind,
    /// ECMAScript `name` property value.
    pub name: &'static str,
    /// ECMAScript `length` property value.
    pub length: u8,
    /// Wasm global holding the constructor's `.prototype` object (without `$`).
    pub prototype_global: Option<&'static str>,
    /// When set, the constructor is also represented as a NUMBER-tagged sentinel.
    pub sentinel_payload: Option<i32>,
    /// Whether `Reflect.construct` / `isConstructor` should succeed.
    pub is_constructable: bool,
}

impl BuiltinConstructorKind {
    pub const ALL: &'static [BuiltinConstructorKind] = &[
        Self::Object,
        Self::Function,
        Self::Boolean,
        Self::Number,
        Self::String,
        Self::Array,
        Self::Date,
        Self::RegExp,
        Self::Map,
        Self::Set,
        Self::WeakMap,
        Self::WeakSet,
        Self::Symbol,
        Self::Promise,
        Self::BigInt,
        Self::Proxy,
        Self::ArrayBuffer,
        Self::SharedArrayBuffer,
        Self::DataView,
        Self::Int8Array,
        Self::Uint8Array,
        Self::Uint8ClampedArray,
        Self::Int16Array,
        Self::Uint16Array,
        Self::Int32Array,
        Self::Uint32Array,
        Self::Float16Array,
        Self::Float32Array,
        Self::Float64Array,
        Self::BigInt64Array,
        Self::BigUint64Array,
        Self::Error,
        Self::EvalError,
        Self::RangeError,
        Self::ReferenceError,
        Self::SyntaxError,
        Self::TypeError,
        Self::URIError,
        Self::AggregateError,
        Self::FinalizationRegistry,
        Self::WeakRef,
        Self::Iterator,
        Self::AsyncIterator,
        Self::SuppressedError,
        Self::DisposableStack,
        Self::AsyncDisposableStack,
    ];

    pub fn from_global_name(name: &str) -> Option<Self> {
        match name {
            "Object" => Some(Self::Object),
            "Function" => Some(Self::Function),
            "Boolean" => Some(Self::Boolean),
            "Number" => Some(Self::Number),
            "String" => Some(Self::String),
            "Array" => Some(Self::Array),
            "Date" => Some(Self::Date),
            "RegExp" => Some(Self::RegExp),
            "Map" => Some(Self::Map),
            "Set" => Some(Self::Set),
            "WeakMap" => Some(Self::WeakMap),
            "WeakSet" => Some(Self::WeakSet),
            "Symbol" => Some(Self::Symbol),
            "Promise" => Some(Self::Promise),
            "BigInt" => Some(Self::BigInt),
            "Proxy" => Some(Self::Proxy),
            "ArrayBuffer" => Some(Self::ArrayBuffer),
            "SharedArrayBuffer" => Some(Self::SharedArrayBuffer),
            "DataView" => Some(Self::DataView),
            "Int8Array" => Some(Self::Int8Array),
            "Uint8Array" => Some(Self::Uint8Array),
            "Uint8ClampedArray" => Some(Self::Uint8ClampedArray),
            "Int16Array" => Some(Self::Int16Array),
            "Uint16Array" => Some(Self::Uint16Array),
            "Int32Array" => Some(Self::Int32Array),
            "Uint32Array" => Some(Self::Uint32Array),
            "Float16Array" => Some(Self::Float16Array),
            "Float32Array" => Some(Self::Float32Array),
            "Float64Array" => Some(Self::Float64Array),
            "BigInt64Array" => Some(Self::BigInt64Array),
            "BigUint64Array" => Some(Self::BigUint64Array),
            "Error" => Some(Self::Error),
            "EvalError" => Some(Self::EvalError),
            "RangeError" => Some(Self::RangeError),
            "ReferenceError" => Some(Self::ReferenceError),
            "SyntaxError" => Some(Self::SyntaxError),
            "TypeError" => Some(Self::TypeError),
            "URIError" => Some(Self::URIError),
            "AggregateError" => Some(Self::AggregateError),
            "FinalizationRegistry" => Some(Self::FinalizationRegistry),
            "WeakRef" => Some(Self::WeakRef),
            "Iterator" => Some(Self::Iterator),
            "AsyncIterator" => Some(Self::AsyncIterator),
            "SuppressedError" => Some(Self::SuppressedError),
            "DisposableStack" => Some(Self::DisposableStack),
            "AsyncDisposableStack" => Some(Self::AsyncDisposableStack),
            _ => None,
        }
    }

    pub fn name(self) -> &'static str {
        spec(self).name
    }

    pub fn constructor_global(self) -> &'static str {
        match self {
            Self::Object => "builtin_ctor_object",
            Self::Function => "builtin_ctor_function",
            Self::Boolean => "builtin_ctor_boolean",
            Self::Number => "builtin_ctor_number",
            Self::String => "builtin_ctor_string",
            Self::Array => "builtin_ctor_array",
            Self::Date => "builtin_ctor_date",
            Self::RegExp => "builtin_ctor_regexp",
            Self::Map => "builtin_ctor_map",
            Self::Set => "builtin_ctor_set",
            Self::WeakMap => "builtin_ctor_weak_map",
            Self::WeakSet => "builtin_ctor_weak_set",
            Self::Symbol => "builtin_ctor_symbol",
            Self::Promise => "builtin_ctor_promise",
            Self::BigInt => "builtin_ctor_bigint",
            Self::Proxy => "builtin_ctor_proxy",
            Self::ArrayBuffer => "builtin_ctor_array_buffer",
            Self::SharedArrayBuffer => "builtin_ctor_shared_array_buffer",
            Self::DataView => "builtin_ctor_data_view",
            Self::Int8Array => "builtin_ctor_int8_array",
            Self::Uint8Array => "builtin_ctor_uint8_array",
            Self::Uint8ClampedArray => "builtin_ctor_uint8_clamped_array",
            Self::Int16Array => "builtin_ctor_int16_array",
            Self::Uint16Array => "builtin_ctor_uint16_array",
            Self::Int32Array => "builtin_ctor_int32_array",
            Self::Uint32Array => "builtin_ctor_uint32_array",
            Self::Float16Array => "builtin_ctor_float16_array",
            Self::Float32Array => "builtin_ctor_float32_array",
            Self::Float64Array => "builtin_ctor_float64_array",
            Self::BigInt64Array => "builtin_ctor_bigint64_array",
            Self::BigUint64Array => "builtin_ctor_bigint64_array",
            Self::Error => "builtin_ctor_error",
            Self::EvalError => "builtin_ctor_eval_error",
            Self::RangeError => "builtin_ctor_range_error",
            Self::ReferenceError => "builtin_ctor_reference_error",
            Self::SyntaxError => "builtin_ctor_syntax_error",
            Self::TypeError => "builtin_ctor_type_error",
            Self::URIError => "builtin_ctor_uri_error",
            Self::AggregateError => "builtin_ctor_aggregate_error",
            Self::FinalizationRegistry => "builtin_ctor_finalization_registry",
            Self::WeakRef => "builtin_ctor_weak_ref",
            Self::Iterator => "builtin_ctor_iterator",
            Self::AsyncIterator => "builtin_ctor_async_iterator",
            Self::SuppressedError => "builtin_ctor_suppressed_error",
            Self::DisposableStack => "builtin_ctor_disposable_stack",
            Self::AsyncDisposableStack => "builtin_ctor_async_disposable_stack",
        }
    }

    pub fn tagged_sentinel(self) -> Option<i32> {
        spec(self)
            .sentinel_payload
            .map(ValueTag::encode_reserved_number_payload)
    }
}

pub const fn spec(kind: BuiltinConstructorKind) -> BuiltinConstructorSpec {
    match kind {
        BuiltinConstructorKind::Object => BuiltinConstructorSpec {
            kind,
            name: "Object",
            length: 1,
            prototype_global: Some("builtin_proto_object"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::Function => BuiltinConstructorSpec {
            kind,
            name: "Function",
            length: 1,
            prototype_global: Some("builtin_proto_function"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::Boolean => BuiltinConstructorSpec {
            kind,
            name: "Boolean",
            length: 1,
            prototype_global: Some("builtin_proto_boolean"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::Number => BuiltinConstructorSpec {
            kind,
            name: "Number",
            length: 1,
            prototype_global: Some("builtin_proto_number"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::String => BuiltinConstructorSpec {
            kind,
            name: "String",
            length: 1,
            prototype_global: Some("builtin_proto_string"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::Array => BuiltinConstructorSpec {
            kind,
            name: "Array",
            length: 1,
            prototype_global: Some("builtin_proto_array"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::Date => BuiltinConstructorSpec {
            kind,
            name: "Date",
            length: 7,
            prototype_global: Some("builtin_proto_date"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::RegExp => BuiltinConstructorSpec {
            kind,
            name: "RegExp",
            length: 2,
            prototype_global: Some("builtin_proto_regexp"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::Map => BuiltinConstructorSpec {
            kind,
            name: "Map",
            length: 0,
            prototype_global: Some("builtin_proto_map"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::Set => BuiltinConstructorSpec {
            kind,
            name: "Set",
            length: 0,
            prototype_global: Some("builtin_proto_set"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::WeakMap => BuiltinConstructorSpec {
            kind,
            name: "WeakMap",
            length: 0,
            prototype_global: Some("builtin_proto_weak_map"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::WeakSet => BuiltinConstructorSpec {
            kind,
            name: "WeakSet",
            length: 0,
            prototype_global: Some("builtin_proto_weak_set"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::Symbol => BuiltinConstructorSpec {
            kind,
            name: "Symbol",
            length: 0,
            prototype_global: Some("builtin_proto_symbol"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::Promise => BuiltinConstructorSpec {
            kind,
            name: "Promise",
            length: 1,
            prototype_global: Some("builtin_proto_promise"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::BigInt => BuiltinConstructorSpec {
            kind,
            name: "BigInt",
            length: 1,
            prototype_global: Some("builtin_proto_bigint"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::Proxy => BuiltinConstructorSpec {
            kind,
            name: "Proxy",
            length: 2,
            prototype_global: None,
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::ArrayBuffer => BuiltinConstructorSpec {
            kind,
            name: "ArrayBuffer",
            length: 1,
            prototype_global: Some("builtin_proto_array_buffer"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::SharedArrayBuffer => BuiltinConstructorSpec {
            kind,
            name: "SharedArrayBuffer",
            length: 1,
            prototype_global: Some("builtin_proto_shared_array_buffer"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::DataView => BuiltinConstructorSpec {
            kind,
            name: "DataView",
            length: 3,
            prototype_global: Some("builtin_proto_data_view"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::Int8Array => BuiltinConstructorSpec {
            kind,
            name: "Int8Array",
            length: 3,
            prototype_global: Some("builtin_proto_int8_array"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::Uint8Array => BuiltinConstructorSpec {
            kind,
            name: "Uint8Array",
            length: 3,
            prototype_global: Some("builtin_proto_uint8_array"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::Uint8ClampedArray => BuiltinConstructorSpec {
            kind,
            name: "Uint8ClampedArray",
            length: 3,
            prototype_global: Some("builtin_proto_uint8_clamped_array"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::Int16Array => BuiltinConstructorSpec {
            kind,
            name: "Int16Array",
            length: 3,
            prototype_global: Some("builtin_proto_int16_array"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::Uint16Array => BuiltinConstructorSpec {
            kind,
            name: "Uint16Array",
            length: 3,
            prototype_global: Some("builtin_proto_uint16_array"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::Int32Array => BuiltinConstructorSpec {
            kind,
            name: "Int32Array",
            length: 3,
            prototype_global: Some("builtin_proto_int32_array"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::Uint32Array => BuiltinConstructorSpec {
            kind,
            name: "Uint32Array",
            length: 3,
            prototype_global: Some("builtin_proto_uint32_array"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::Float16Array => BuiltinConstructorSpec {
            kind,
            name: "Float16Array",
            length: 3,
            prototype_global: Some("builtin_proto_float16_array"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::Float32Array => BuiltinConstructorSpec {
            kind,
            name: "Float32Array",
            length: 3,
            prototype_global: Some("builtin_proto_float32_array"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::Float64Array => BuiltinConstructorSpec {
            kind,
            name: "Float64Array",
            length: 3,
            prototype_global: Some("builtin_proto_float64_array"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::BigInt64Array => BuiltinConstructorSpec {
            kind,
            name: "BigInt64Array",
            length: 3,
            prototype_global: Some("builtin_proto_bigint64_array"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::BigUint64Array => BuiltinConstructorSpec {
            kind,
            name: "BigUint64Array",
            length: 3,
            prototype_global: Some("builtin_proto_biguint64_array"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::Error => BuiltinConstructorSpec {
            kind,
            name: "Error",
            length: 1,
            prototype_global: Some("error_proto_error"),
            sentinel_payload: Some(ValueTag::ERROR_PAYLOAD),
            is_constructable: true,
        },
        BuiltinConstructorKind::EvalError => BuiltinConstructorSpec {
            kind,
            name: "EvalError",
            length: 1,
            prototype_global: Some("error_proto_eval_error"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::RangeError => BuiltinConstructorSpec {
            kind,
            name: "RangeError",
            length: 1,
            prototype_global: Some("error_proto_range_error"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::ReferenceError => BuiltinConstructorSpec {
            kind,
            name: "ReferenceError",
            length: 1,
            prototype_global: Some("error_proto_reference_error"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::SyntaxError => BuiltinConstructorSpec {
            kind,
            name: "SyntaxError",
            length: 1,
            prototype_global: Some("error_proto_syntax_error"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::TypeError => BuiltinConstructorSpec {
            kind,
            name: "TypeError",
            length: 1,
            prototype_global: Some("error_proto_type_error"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::URIError => BuiltinConstructorSpec {
            kind,
            name: "URIError",
            length: 1,
            prototype_global: Some("error_proto_uri_error"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::AggregateError => BuiltinConstructorSpec {
            kind,
            name: "AggregateError",
            length: 2,
            prototype_global: Some("error_proto_aggregate_error"),
            sentinel_payload: Some(ValueTag::AGGREGATE_ERROR_PAYLOAD),
            is_constructable: true,
        },
        BuiltinConstructorKind::FinalizationRegistry => BuiltinConstructorSpec {
            kind,
            name: "FinalizationRegistry",
            length: 1,
            prototype_global: Some("builtin_proto_finalization_registry"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::WeakRef => BuiltinConstructorSpec {
            kind,
            name: "WeakRef",
            length: 1,
            prototype_global: Some("builtin_proto_weak_ref"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::Iterator => BuiltinConstructorSpec {
            kind,
            name: "Iterator",
            length: 0,
            prototype_global: Some("builtin_proto_iterator"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::AsyncIterator => BuiltinConstructorSpec {
            kind,
            name: "AsyncIterator",
            length: 0,
            prototype_global: Some("builtin_proto_async_iterator"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::SuppressedError => BuiltinConstructorSpec {
            kind,
            name: "SuppressedError",
            length: 2,
            prototype_global: Some("builtin_proto_suppressed_error"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::DisposableStack => BuiltinConstructorSpec {
            kind,
            name: "DisposableStack",
            length: 0,
            prototype_global: Some("builtin_proto_disposable_stack"),
            sentinel_payload: None,
            is_constructable: true,
        },
        BuiltinConstructorKind::AsyncDisposableStack => BuiltinConstructorSpec {
            kind,
            name: "AsyncDisposableStack",
            length: 0,
            prototype_global: Some("builtin_proto_async_disposable_stack"),
            sentinel_payload: None,
            is_constructable: true,
        },
    }
}

pub fn error_kind_from_sentinel_payload(payload: i32) -> Option<BuiltinConstructorKind> {
    match payload {
        ValueTag::ERROR_PAYLOAD => Some(BuiltinConstructorKind::Error),
        ValueTag::AGGREGATE_ERROR_PAYLOAD => Some(BuiltinConstructorKind::AggregateError),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn all_kinds_have_unique_names() {
        let mut names = std::collections::BTreeSet::new();
        for kind in BuiltinConstructorKind::ALL {
            assert!(names.insert(spec(*kind).name));
        }
    }

    #[test]
    fn error_sentinels_fit_native_error_payload_range() {
        for kind in BuiltinConstructorKind::ALL {
            if let Some(payload) = spec(*kind).sentinel_payload {
                assert!(payload >= ValueTag::NATIVE_ERROR_PAYLOAD_BASE);
                assert!(payload < ValueTag::DIRECT_LOCAL_TOKEN_PAYLOAD_BASE);
            }
        }
    }
}
