#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Ord, PartialOrd)]
pub enum Capability {
    StdinRead,
    StdoutWrite,
    WasiClockRealtime,
    WasiRandom,

    WasiArgs,
    WasiEnv,
    WasiFilesystemRead,
    WasiFilesystemWrite,
    #[allow(dead_code)]
    WasiFilesystemAppend,
    #[allow(dead_code)]
    HostFsReadFileSync,
    #[allow(dead_code)]
    HostFsWriteFileSync,
    HostFsAppendFileSync,
    HostProcessExit,
    HostPathJoin,
    HostPathResolve,
    HostPathBasename,
    HostPathDirname,
    HostCryptoRandomBytes,
    HostEncodeURI,
    HostDecodeURI,
    HostEscape,
    HostUnescape,
    HostDateToString,
    HostDateGetLocalTimeField,
    HostDateToISOString,
    HostDateGetTimezoneOffset,
    HostDateToDateString,
    HostDateToTimeString,
    HostDateParse,
    HostDateUTC,
    HostMathAcos,
    HostMathAcosh,
    HostMathAsin,
    HostMathAsinh,
    HostMathAtan,
    HostMathAtanh,
    HostMathCos,
    HostMathCosh,
    HostMathExp,
    HostMathExpm1,
    HostMathLog,
    HostMathLog10,
    HostMathLog1p,
    HostMathLog2,
    HostMathSin,
    HostMathSinh,
    HostMathTan,
    HostMathTanh,
    HostStringNormalize,
    HostIntlNumberFormatFormat,
    HostIntlDateTimeFormatFormat,
    HostReflectApply,
    HostReflectConstruct,
    HostEvalDirect,
    HostEvalIndirect,
    HostFunctionCompile,
    HostFunctionCall,
    HostFunctionCallMethod,
    HostFunctionConstruct,
}

impl Capability {
    /// Get the manifest name for this capability (derived from catalog).
    pub const fn manifest_name(self) -> &'static str {
        match self {
            Self::StdinRead => "stdin.read",
            Self::StdoutWrite => "stdout.write",
            Self::WasiClockRealtime => "wasi.clock.realtime",
            Self::WasiRandom => "wasi.random",

            Self::WasiArgs => "wasi.args",
            Self::WasiEnv => "wasi.env",
            Self::WasiFilesystemRead => "wasi.filesystem.read",
            Self::WasiFilesystemWrite => "wasi.filesystem.write",
            Self::WasiFilesystemAppend => "wasi.filesystem.append",
            Self::HostFsReadFileSync => "host.fs.readFileSync",
            Self::HostFsWriteFileSync => "host.fs.writeFileSync",
            Self::HostFsAppendFileSync => "host.fs.appendFileSync",
            Self::HostProcessExit => "host.process.exit",
            Self::HostPathJoin => "host.path.join",
            Self::HostPathResolve => "host.path.resolve",
            Self::HostPathBasename => "host.path.basename",
            Self::HostPathDirname => "host.path.dirname",
            Self::HostCryptoRandomBytes => "host.crypto.randomBytes",
            Self::HostEncodeURI => "host.encodeURI",
            Self::HostDecodeURI => "host.decodeURI",
            Self::HostEscape => "host.escape",
            Self::HostUnescape => "host.unescape",
            Self::HostDateToString => "host.dateToString",
            Self::HostDateGetLocalTimeField => "host.dateGetLocalTimeField",
            Self::HostDateToISOString => "host.dateToISOString",
            Self::HostDateGetTimezoneOffset => "host.dateGetTimezoneOffset",
            Self::HostDateToDateString => "host.dateToDateString",
            Self::HostDateToTimeString => "host.dateToTimeString",
            Self::HostDateParse => "host.dateParse",
            Self::HostDateUTC => "host.dateUTC",
            Self::HostMathAcos => "host.mathAcos",
            Self::HostMathAcosh => "host.mathAcosh",
            Self::HostMathAsin => "host.mathAsin",
            Self::HostMathAsinh => "host.mathAsinh",
            Self::HostMathAtan => "host.mathAtan",
            Self::HostMathAtanh => "host.mathAtanh",
            Self::HostMathCos => "host.mathCos",
            Self::HostMathCosh => "host.mathCosh",
            Self::HostMathExp => "host.mathExp",
            Self::HostMathExpm1 => "host.mathExpm1",
            Self::HostMathLog => "host.mathLog",
            Self::HostMathLog10 => "host.mathLog10",
            Self::HostMathLog1p => "host.mathLog1p",
            Self::HostMathLog2 => "host.mathLog2",
            Self::HostMathSin => "host.mathSin",
            Self::HostMathSinh => "host.mathSinh",
            Self::HostMathTan => "host.mathTan",
            Self::HostMathTanh => "host.mathTanh",
            Self::HostStringNormalize => "host.stringNormalize",
            Self::HostIntlNumberFormatFormat => "host.intlNumberFormatFormat",
            Self::HostIntlDateTimeFormatFormat => "host.intlDateTimeFormatFormat",
            Self::HostReflectApply => "host.reflectApply",
            Self::HostReflectConstruct => "host.reflectConstruct",
            Self::HostEvalDirect => "host.eval.direct",
            Self::HostEvalIndirect => "host.eval.indirect",
            Self::HostFunctionCompile => "host.function.compile",
            Self::HostFunctionCall => "host.function.call",
            Self::HostFunctionCallMethod => "host.function.callMethod",
            Self::HostFunctionConstruct => "host.function.construct",
        }
    }
}
