#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Ord, PartialOrd)]
pub enum Capability {
    StdinRead,
    StdoutWrite,
    WasiClockRealtime,
    WasiRandom,

    WasiArgs,
    WasiEnv,
    WasiFilesystemRead,
    WasiFilesystemWrite,
    #[allow(dead_code)]
    WasiFilesystemAppend,
    #[allow(dead_code)]
    HostFsReadFileSync,
    #[allow(dead_code)]
    HostFsWriteFileSync,
    HostFsAppendFileSync,
    HostProcessExit,
    HostPathJoin,
    HostPathResolve,
    HostPathBasename,
    HostPathDirname,
    HostCryptoRandomBytes,
    HostEncodeURI,
    HostDecodeURI,
    HostEscape,
    HostUnescape,
    HostDateToString,
    HostDateGetLocalTimeField,
    HostDateToISOString,
    HostDateGetTimezoneOffset,
    HostDateToDateString,
    HostDateToTimeString,
    HostDateParse,
    HostDateUTC,
    HostMathAcos,
    HostMathAcosh,
    HostMathAsin,
    HostMathAsinh,
    HostMathAtan,
    HostMathAtanh,
    HostMathCos,
    HostMathCosh,
    HostMathExp,
    HostMathExpm1,
    HostMathLog,
    HostMathLog10,
    HostMathLog1p,
    HostMathLog2,
    HostMathSin,
    HostMathSinh,
    HostMathTan,
    HostMathTanh,
    HostMathAtan2,
    HostMathHypot,
    HostJsonStringify,
    HostJsonParse,
    HostStringNormalize,
    HostIntlNumberFormatFormat,
    HostIntlDateTimeFormatFormat,
    HostReflectApply,
    HostReflectConstruct,
    HostGetIterator,
    HostIteratorNext,
    HostIteratorMap,
    HostIteratorFilter,
    HostIteratorTake,
    HostIteratorDrop,
    HostIteratorToArray,
    HostIteratorReduce,
    HostIteratorForEach,
    HostIteratorSome,
    HostIteratorEvery,
    HostIteratorFind,
    HostEvalDirect,
    HostEvalIndirect,
    HostFunctionCompile,
    HostFunctionCall,
    HostFunctionCallMethod,
    HostFunctionConstruct,
}

const CAPABILITY_MANIFEST_NAMES: &[(Capability, &str)] = &[
    (Capability::StdinRead, "stdin.read"),
    (Capability::StdoutWrite, "stdout.write"),
    (Capability::WasiClockRealtime, "wasi.clock.realtime"),
    (Capability::WasiRandom, "wasi.random"),
    (Capability::WasiArgs, "wasi.args"),
    (Capability::WasiEnv, "wasi.env"),
    (Capability::WasiFilesystemRead, "wasi.filesystem.read"),
    (Capability::WasiFilesystemWrite, "wasi.filesystem.write"),
    (Capability::WasiFilesystemAppend, "wasi.filesystem.append"),
    (Capability::HostFsReadFileSync, "host.fs.readFileSync"),
    (Capability::HostFsWriteFileSync, "host.fs.writeFileSync"),
    (Capability::HostFsAppendFileSync, "host.fs.appendFileSync"),
    (Capability::HostProcessExit, "host.process.exit"),
    (Capability::HostPathJoin, "host.path.join"),
    (Capability::HostPathResolve, "host.path.resolve"),
    (Capability::HostPathBasename, "host.path.basename"),
    (Capability::HostPathDirname, "host.path.dirname"),
    (Capability::HostCryptoRandomBytes, "host.crypto.randomBytes"),
    (Capability::HostEncodeURI, "host.encodeURI"),
    (Capability::HostDecodeURI, "host.decodeURI"),
    (Capability::HostEscape, "host.escape"),
    (Capability::HostUnescape, "host.unescape"),
    (Capability::HostDateToString, "host.dateToString"),
    (
        Capability::HostDateGetLocalTimeField,
        "host.dateGetLocalTimeField",
    ),
    (Capability::HostDateToISOString, "host.dateToISOString"),
    (
        Capability::HostDateGetTimezoneOffset,
        "host.dateGetTimezoneOffset",
    ),
    (Capability::HostDateToDateString, "host.dateToDateString"),
    (Capability::HostDateToTimeString, "host.dateToTimeString"),
    (Capability::HostDateParse, "host.dateParse"),
    (Capability::HostDateUTC, "host.dateUTC"),
    (Capability::HostMathAcos, "host.mathAcos"),
    (Capability::HostMathAcosh, "host.mathAcosh"),
    (Capability::HostMathAsin, "host.mathAsin"),
    (Capability::HostMathAsinh, "host.mathAsinh"),
    (Capability::HostMathAtan, "host.mathAtan"),
    (Capability::HostMathAtanh, "host.mathAtanh"),
    (Capability::HostMathCos, "host.mathCos"),
    (Capability::HostMathCosh, "host.mathCosh"),
    (Capability::HostMathExp, "host.mathExp"),
    (Capability::HostMathExpm1, "host.mathExpm1"),
    (Capability::HostMathLog, "host.mathLog"),
    (Capability::HostMathLog10, "host.mathLog10"),
    (Capability::HostMathLog1p, "host.mathLog1p"),
    (Capability::HostMathLog2, "host.mathLog2"),
    (Capability::HostMathSin, "host.mathSin"),
    (Capability::HostMathSinh, "host.mathSinh"),
    (Capability::HostMathTan, "host.mathTan"),
    (Capability::HostMathTanh, "host.mathTanh"),
    (Capability::HostMathAtan2, "host.mathAtan2"),
    (Capability::HostMathHypot, "host.mathHypot"),
    (Capability::HostJsonStringify, "host.json.stringify"),
    (Capability::HostJsonParse, "host.json.parse"),
    (Capability::HostStringNormalize, "host.stringNormalize"),
    (
        Capability::HostIntlNumberFormatFormat,
        "host.intlNumberFormatFormat",
    ),
    (
        Capability::HostIntlDateTimeFormatFormat,
        "host.intlDateTimeFormatFormat",
    ),
    (Capability::HostReflectApply, "host.reflectApply"),
    (Capability::HostReflectConstruct, "host.reflectConstruct"),
    (Capability::HostGetIterator, "host.getIterator"),
    (Capability::HostIteratorNext, "host.iteratorNext"),
    (Capability::HostIteratorMap, "host.iterator.map"),
    (Capability::HostIteratorFilter, "host.iterator.filter"),
    (Capability::HostIteratorTake, "host.iterator.take"),
    (Capability::HostIteratorDrop, "host.iterator.drop"),
    (Capability::HostIteratorToArray, "host.iterator.toArray"),
    (Capability::HostIteratorReduce, "host.iterator.reduce"),
    (Capability::HostIteratorForEach, "host.iterator.forEach"),
    (Capability::HostIteratorSome, "host.iterator.some"),
    (Capability::HostIteratorEvery, "host.iterator.every"),
    (Capability::HostIteratorFind, "host.iterator.find"),
    (Capability::HostEvalDirect, "host.eval.direct"),
    (Capability::HostEvalIndirect, "host.eval.indirect"),
    (Capability::HostFunctionCompile, "host.function.compile"),
    (Capability::HostFunctionCall, "host.function.call"),
    (
        Capability::HostFunctionCallMethod,
        "host.function.callMethod",
    ),
    (Capability::HostFunctionConstruct, "host.function.construct"),
];

impl Capability {
    /// Get the manifest name for this capability (derived from catalog).
    pub fn manifest_name(self) -> &'static str {
        CAPABILITY_MANIFEST_NAMES
            .iter()
            .find_map(|(capability, name)| (*capability == self).then_some(*name))
            .expect("capability manifest name must exist")
    }
}
