/// ABI contract type for host imports.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum HostAbi {
    WasiPreview1,
    NodeShim,
    /// Internal host functions for runtime support
    /// Kept for future internal host function support
    #[allow(dead_code)]
    InternalHost,
}

/// Complete metadata for a host import binding (single source of truth).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct HostImportSpec {
    pub module: &'static str,
    pub name: &'static str,
    pub wat_symbol: &'static str,
    pub abi: HostAbi,
    /// WAT parameter list (e.g., "param i32 i32 i32 i32") or empty
    pub params: &'static str,
    /// WAT result type (e.g., "result i32") or empty
    pub result: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Ord, PartialOrd)]
pub enum HostImport {
    FdRead,
    FdWrite,
    PathOpen,
    /// WASI fd_seek — reposition file cursor
    #[allow(dead_code)]
    FdSeek,
    FdClose,
    /// WASI fd_prestat_get — query preopened directory info
    #[allow(dead_code)]
    FdPrestatGet,
    /// WASI fd_prestat_dir_name — get preopened directory name
    #[allow(dead_code)]
    FdPrestatDirName,
    /// WASI path_create_directory — create a directory
    #[allow(dead_code)]
    PathCreateDirectory,
    /// WASI path_filestat_get — get file metadata by path
    #[allow(dead_code)]
    PathFilestatGet,
    /// WASI path_readlink — read symlink target
    #[allow(dead_code)]
    PathReadlink,
    /// WASI path_remove_directory — remove a directory
    #[allow(dead_code)]
    PathRemoveDirectory,
    /// WASI path_rename — rename a file or directory
    #[allow(dead_code)]
    PathRename,
    /// WASI path_symlink — create a symbolic link
    #[allow(dead_code)]
    PathSymlink,
    /// WASI path_unlink_file — unlink a file
    #[allow(dead_code)]
    PathUnlinkFile,
    WasiProcExit,
    ClockTimeGet,
    #[allow(dead_code)]
    ClockResGet,
    RandomGet,
    ArgsSizesGet,
    ArgsGet,
    EnvironSizesGet,
    EnvironGet,
    #[allow(dead_code)]
    FsReadFileSync,
    #[allow(dead_code)]
    FsWriteFileSync,
    FsAppendFileSync,
    ProcessExit,
    PathJoin,
    PathResolve,
    PathBasename,
    PathDirname,
    CryptoRandomBytes,
    EncodeURI,
    DecodeURI,
    Escape,
    Unescape,
    DateToString,
    DateGetLocalTimeField,
    DateToISOString,
    DateGetTimezoneOffset,
    DateToDateString,
    DateToTimeString,
    DateParse,
    DateUTC,
    StringNormalize,
    IntlNumberFormatFormat,
    IntlDateTimeFormatFormat,
    ReflectApply,
    ReflectConstruct,
    GetIterator,
    IteratorNext,
    EvalDirect,
    EvalIndirect,
    FunctionCompile,
    FunctionCall,
    FunctionConstruct,
}

impl HostImport {
    /// Get the complete metadata for this host import (single source of truth).
    pub const fn spec(self) -> HostImportSpec {
        match self {
            Self::FdRead => HostImportSpec {
                module: "wasi_snapshot_preview1",
                name: "fd_read",
                wat_symbol: "$fd_read",
                abi: HostAbi::WasiPreview1,
                params: "param i32 i32 i32 i32",
                result: "result i32",
            },
            Self::FdWrite => HostImportSpec {
                module: "wasi_snapshot_preview1",
                name: "fd_write",
                wat_symbol: "$fd_write",
                abi: HostAbi::WasiPreview1,
                params: "param i32 i32 i32 i32",
                result: "result i32",
            },
            Self::PathOpen => HostImportSpec {
                module: "wasi_snapshot_preview1",
                name: "path_open",
                wat_symbol: "$path_open",
                abi: HostAbi::WasiPreview1,
                params: "param i32 i32 i32 i32 i32 i64 i64 i32 i32",
                result: "result i32",
            },
            Self::FdSeek => HostImportSpec {
                module: "wasi_snapshot_preview1",
                name: "fd_seek",
                wat_symbol: "$fd_seek",
                abi: HostAbi::WasiPreview1,
                params: "param i32 i64 i32 i32",
                result: "result i32",
            },
            Self::FdClose => HostImportSpec {
                module: "wasi_snapshot_preview1",
                name: "fd_close",
                wat_symbol: "$fd_close",
                abi: HostAbi::WasiPreview1,
                params: "param i32",
                result: "result i32",
            },
            Self::FdPrestatGet => HostImportSpec {
                module: "wasi_snapshot_preview1",
                name: "fd_prestat_get",
                wat_symbol: "$fd_prestat_get",
                abi: HostAbi::WasiPreview1,
                params: "param i32 i32",
                result: "result i32",
            },
            Self::FdPrestatDirName => HostImportSpec {
                module: "wasi_snapshot_preview1",
                name: "fd_prestat_dir_name",
                wat_symbol: "$fd_prestat_dir_name",
                abi: HostAbi::WasiPreview1,
                params: "param i32 i32 i32",
                result: "result i32",
            },
            Self::PathCreateDirectory => HostImportSpec {
                module: "wasi_snapshot_preview1",
                name: "path_create_directory",
                wat_symbol: "$path_create_directory",
                abi: HostAbi::WasiPreview1,
                params: "param i32 i32 i32",
                result: "result i32",
            },
            Self::PathFilestatGet => HostImportSpec {
                module: "wasi_snapshot_preview1",
                name: "path_filestat_get",
                wat_symbol: "$path_filestat_get",
                abi: HostAbi::WasiPreview1,
                params: "param i32 i32 i32 i32 i32",
                result: "result i32",
            },
            Self::PathReadlink => HostImportSpec {
                module: "wasi_snapshot_preview1",
                name: "path_readlink",
                wat_symbol: "$path_readlink",
                abi: HostAbi::WasiPreview1,
                params: "param i32 i32 i32 i32 i32",
                result: "result i32",
            },
            Self::PathRemoveDirectory => HostImportSpec {
                module: "wasi_snapshot_preview1",
                name: "path_remove_directory",
                wat_symbol: "$path_remove_directory",
                abi: HostAbi::WasiPreview1,
                params: "param i32 i32 i32",
                result: "result i32",
            },
            Self::PathRename => HostImportSpec {
                module: "wasi_snapshot_preview1",
                name: "path_rename",
                wat_symbol: "$path_rename",
                abi: HostAbi::WasiPreview1,
                params: "param i32 i32 i32 i32 i32",
                result: "result i32",
            },
            Self::PathSymlink => HostImportSpec {
                module: "wasi_snapshot_preview1",
                name: "path_symlink",
                wat_symbol: "$path_symlink",
                abi: HostAbi::WasiPreview1,
                params: "param i32 i32 i32 i32 i32",
                result: "result i32",
            },
            Self::PathUnlinkFile => HostImportSpec {
                module: "wasi_snapshot_preview1",
                name: "path_unlink_file",
                wat_symbol: "$path_unlink_file",
                abi: HostAbi::WasiPreview1,
                params: "param i32 i32 i32",
                result: "result i32",
            },
            Self::WasiProcExit => HostImportSpec {
                module: "wasi_snapshot_preview1",
                name: "proc_exit",
                wat_symbol: "$wasi_proc_exit",
                abi: HostAbi::WasiPreview1,
                params: "param i32",
                result: "",
            },
            Self::ClockTimeGet => HostImportSpec {
                module: "wasi_snapshot_preview1",
                name: "clock_time_get",
                wat_symbol: "$clock_time_get",
                abi: HostAbi::WasiPreview1,
                params: "param i32 i64 i32",
                result: "result i32",
            },
            Self::ClockResGet => HostImportSpec {
                module: "wasi_snapshot_preview1",
                name: "clock_res_get",
                wat_symbol: "$clock_res_get",
                abi: HostAbi::WasiPreview1,
                params: "param i32 i32",
                result: "result i32",
            },
            Self::RandomGet => HostImportSpec {
                module: "wasi_snapshot_preview1",
                name: "random_get",
                wat_symbol: "$random_get",
                abi: HostAbi::WasiPreview1,
                params: "param i32 i32",
                result: "result i32",
            },
            Self::ArgsSizesGet => HostImportSpec {
                module: "wasi_snapshot_preview1",
                name: "args_sizes_get",
                wat_symbol: "$args_sizes_get",
                abi: HostAbi::WasiPreview1,
                params: "param i32 i32",
                result: "result i32",
            },
            Self::ArgsGet => HostImportSpec {
                module: "wasi_snapshot_preview1",
                name: "args_get",
                wat_symbol: "$args_get",
                abi: HostAbi::WasiPreview1,
                params: "param i32 i32",
                result: "result i32",
            },
            Self::EnvironSizesGet => HostImportSpec {
                module: "wasi_snapshot_preview1",
                name: "environ_sizes_get",
                wat_symbol: "$environ_sizes_get",
                abi: HostAbi::WasiPreview1,
                params: "param i32 i32",
                result: "result i32",
            },
            Self::EnvironGet => HostImportSpec {
                module: "wasi_snapshot_preview1",
                name: "environ_get",
                wat_symbol: "$environ_get",
                abi: HostAbi::WasiPreview1,
                params: "param i32 i32",
                result: "result i32",
            },
            Self::FsReadFileSync => HostImportSpec {
                module: "host",
                name: "fs.readFileSync",
                wat_symbol: "$host_fs_read_file_sync",
                abi: HostAbi::NodeShim,
                params: "param i32 i32",
                result: "result i32",
            },
            Self::FsWriteFileSync => HostImportSpec {
                module: "host",
                name: "fs.writeFileSync",
                wat_symbol: "$host_fs_write_file_sync",
                abi: HostAbi::NodeShim,
                params: "param i32 i32",
                result: "",
            },
            Self::FsAppendFileSync => HostImportSpec {
                module: "host",
                name: "fs.appendFileSync",
                wat_symbol: "$host_fs_append_file_sync",
                abi: HostAbi::NodeShim,
                params: "param i32 i32",
                result: "",
            },
            Self::ProcessExit => HostImportSpec {
                module: "host",
                name: "process.exit",
                wat_symbol: "$host_process_exit",
                abi: HostAbi::NodeShim,
                params: "param i32",
                result: "",
            },
            Self::PathJoin => HostImportSpec {
                module: "host",
                name: "path.join",
                wat_symbol: "$host_path_join",
                abi: HostAbi::NodeShim,
                params: "param i32 i32",
                result: "result i32",
            },
            Self::PathResolve => HostImportSpec {
                module: "host",
                name: "path.resolve",
                wat_symbol: "$host_path_resolve",
                abi: HostAbi::NodeShim,
                params: "param i32",
                result: "result i32",
            },
            Self::PathBasename => HostImportSpec {
                module: "host",
                name: "path.basename",
                wat_symbol: "$host_path_basename",
                abi: HostAbi::NodeShim,
                params: "param i32",
                result: "result i32",
            },
            Self::PathDirname => HostImportSpec {
                module: "host",
                name: "path.dirname",
                wat_symbol: "$host_path_dirname",
                abi: HostAbi::NodeShim,
                params: "param i32",
                result: "result i32",
            },
            Self::CryptoRandomBytes => HostImportSpec {
                module: "host",
                name: "crypto.randomBytes",
                wat_symbol: "$host_crypto_random_bytes",
                abi: HostAbi::NodeShim,
                params: "param i32",
                result: "result i32",
            },
            Self::EncodeURI => HostImportSpec {
                module: "host",
                name: "encodeURI",
                wat_symbol: "$host_encode_uri",
                abi: HostAbi::NodeShim,
                params: "param i32",
                result: "result i32",
            },
            Self::DecodeURI => HostImportSpec {
                module: "host",
                name: "decodeURI",
                wat_symbol: "$host_decode_uri",
                abi: HostAbi::NodeShim,
                params: "param i32",
                result: "result i32",
            },
            Self::Escape => HostImportSpec {
                module: "host",
                name: "escape",
                wat_symbol: "$host_escape",
                abi: HostAbi::NodeShim,
                params: "param i32",
                result: "result i32",
            },
            Self::Unescape => HostImportSpec {
                module: "host",
                name: "unescape",
                wat_symbol: "$host_unescape",
                abi: HostAbi::NodeShim,
                params: "param i32",
                result: "result i32",
            },
            Self::DateToString => HostImportSpec {
                module: "host",
                name: "dateToString",
                wat_symbol: "$host_date_to_string",
                abi: HostAbi::NodeShim,
                params: "param i32",
                result: "result i32",
            },
            Self::DateGetLocalTimeField => HostImportSpec {
                module: "host",
                name: "dateGetLocalTimeField",
                wat_symbol: "$host_date_get_local_time_field",
                abi: HostAbi::NodeShim,
                params: "param i32 i32",
                result: "result i32",
            },
            Self::DateToISOString => HostImportSpec {
                module: "host",
                name: "dateToISOString",
                wat_symbol: "$host_date_to_iso_string",
                abi: HostAbi::NodeShim,
                params: "param i32",
                result: "result i32",
            },
            Self::DateGetTimezoneOffset => HostImportSpec {
                module: "host",
                name: "dateGetTimezoneOffset",
                wat_symbol: "$host_date_get_timezone_offset",
                abi: HostAbi::NodeShim,
                params: "param i32",
                result: "result i32",
            },
            Self::DateToDateString => HostImportSpec {
                module: "host",
                name: "dateToDateString",
                wat_symbol: "$host_date_to_date_string",
                abi: HostAbi::NodeShim,
                params: "param i32",
                result: "result i32",
            },
            Self::DateToTimeString => HostImportSpec {
                module: "host",
                name: "dateToTimeString",
                wat_symbol: "$host_date_to_time_string",
                abi: HostAbi::NodeShim,
                params: "param i32",
                result: "result i32",
            },
            Self::DateParse => HostImportSpec {
                module: "host",
                name: "dateParse",
                wat_symbol: "$host_date_parse",
                abi: HostAbi::NodeShim,
                params: "param i32",
                result: "result i32",
            },
            Self::DateUTC => HostImportSpec {
                module: "host",
                name: "dateUTC",
                wat_symbol: "$host_date_utc",
                abi: HostAbi::NodeShim,
                params: "param i32 i32 i32 i32 i32 i32 i32",
                result: "result i32",
            },
            Self::StringNormalize => HostImportSpec {
                module: "host",
                name: "stringNormalize",
                wat_symbol: "$host_string_normalize",
                abi: HostAbi::NodeShim,
                params: "param i32 i32",
                result: "result i32",
            },
            Self::IntlNumberFormatFormat => HostImportSpec {
                module: "host",
                name: "intlNumberFormatFormat",
                wat_symbol: "$host_intl_number_format_format",
                abi: HostAbi::NodeShim,
                params: "param i32 i32",
                result: "result i32",
            },
            Self::IntlDateTimeFormatFormat => HostImportSpec {
                module: "host",
                name: "intlDateTimeFormatFormat",
                wat_symbol: "$host_intl_date_time_format_format",
                abi: HostAbi::NodeShim,
                params: "param i32 i32",
                result: "result i32",
            },
            Self::ReflectApply => HostImportSpec {
                module: "host",
                name: "reflectApply",
                wat_symbol: "$host_reflect_apply",
                abi: HostAbi::NodeShim,
                params: "param i32 i32 i32",
                result: "result i32",
            },
            Self::ReflectConstruct => HostImportSpec {
                module: "host",
                name: "reflectConstruct",
                wat_symbol: "$host_reflect_construct",
                abi: HostAbi::NodeShim,
                params: "param i32 i32",
                result: "result i32",
            },
            Self::GetIterator => HostImportSpec {
                module: "host",
                name: "getIterator",
                wat_symbol: "$host_get_iterator",
                abi: HostAbi::NodeShim,
                params: "param i32",
                result: "result i32",
            },
            Self::IteratorNext => HostImportSpec {
                module: "host",
                name: "iteratorNext",
                wat_symbol: "$host_iterator_next",
                abi: HostAbi::NodeShim,
                params: "param i32",
                result: "result i32",
            },
            Self::EvalDirect => HostImportSpec {
                module: "host",
                name: "eval.direct",
                wat_symbol: "$host_eval_direct",
                abi: HostAbi::NodeShim,
                params: "param i32 i32",
                result: "result i32",
            },
            Self::EvalIndirect => HostImportSpec {
                module: "host",
                name: "eval.indirect",
                wat_symbol: "$host_eval_indirect",
                abi: HostAbi::NodeShim,
                params: "param i32 i32",
                result: "result i32",
            },
            Self::FunctionCompile => HostImportSpec {
                module: "host",
                name: "function.compile",
                wat_symbol: "$host_function_compile",
                abi: HostAbi::NodeShim,
                params: "param i32",
                result: "result i32",
            },
            Self::FunctionCall => HostImportSpec {
                module: "host",
                name: "function.call",
                wat_symbol: "$host_function_call",
                abi: HostAbi::NodeShim,
                params: "param i32 i32",
                result: "result i32",
            },
            Self::FunctionConstruct => HostImportSpec {
                module: "host",
                name: "function.construct",
                wat_symbol: "$host_function_construct",
                abi: HostAbi::NodeShim,
                params: "param i32 i32",
                result: "result i32",
            },
        }
    }

    /// Get the flat import name for manifest (derived from spec).
    /// Kept for future manifest emission capabilities.
    #[allow(dead_code)]
    pub const fn manifest_name(self) -> &'static str {
        match self {
            Self::FdRead => "wasi_snapshot_preview1.fd_read",
            Self::FdWrite => "wasi_snapshot_preview1.fd_write",
            Self::PathOpen => "wasi_snapshot_preview1.path_open",
            Self::FdClose => "wasi_snapshot_preview1.fd_close",
            Self::FdSeek => "wasi_snapshot_preview1.fd_seek",
            Self::FdPrestatGet => "wasi_snapshot_preview1.fd_prestat_get",
            Self::FdPrestatDirName => "wasi_snapshot_preview1.fd_prestat_dir_name",
            Self::PathCreateDirectory => "wasi_snapshot_preview1.path_create_directory",
            Self::PathFilestatGet => "wasi_snapshot_preview1.path_filestat_get",
            Self::PathReadlink => "wasi_snapshot_preview1.path_readlink",
            Self::PathRemoveDirectory => "wasi_snapshot_preview1.path_remove_directory",
            Self::PathRename => "wasi_snapshot_preview1.path_rename",
            Self::PathSymlink => "wasi_snapshot_preview1.path_symlink",
            Self::PathUnlinkFile => "wasi_snapshot_preview1.path_unlink_file",
            Self::WasiProcExit => "wasi_snapshot_preview1.proc_exit",
            Self::ClockTimeGet => "wasi_snapshot_preview1.clock_time_get",
            Self::ClockResGet => "wasi_snapshot_preview1.clock_res_get",
            Self::RandomGet => "wasi_snapshot_preview1.random_get",
            Self::ArgsSizesGet => "wasi_snapshot_preview1.args_sizes_get",
            Self::ArgsGet => "wasi_snapshot_preview1.args_get",
            Self::EnvironSizesGet => "wasi_snapshot_preview1.environ_sizes_get",
            Self::EnvironGet => "wasi_snapshot_preview1.environ_get",
            Self::FsReadFileSync => "host.fs.readFileSync",
            Self::FsWriteFileSync => "host.fs.writeFileSync",
            Self::FsAppendFileSync => "host.fs.appendFileSync",
            Self::ProcessExit => "host.process.exit",
            Self::PathJoin => "host.path.join",
            Self::PathResolve => "host.path.resolve",
            Self::PathBasename => "host.path.basename",
            Self::PathDirname => "host.path.dirname",
            Self::CryptoRandomBytes => "host.crypto.randomBytes",
            Self::EncodeURI => "host.encodeURI",
            Self::DecodeURI => "host.decodeURI",
            Self::Escape => "host.escape",
            Self::Unescape => "host.unescape",
            Self::DateToString => "host.dateToString",
            Self::DateGetLocalTimeField => "host.dateGetLocalTimeField",
            Self::DateToISOString => "host.dateToISOString",
            Self::DateGetTimezoneOffset => "host.dateGetTimezoneOffset",
            Self::DateToDateString => "host.dateToDateString",
            Self::DateToTimeString => "host.dateToTimeString",
            Self::DateParse => "host.dateParse",
            Self::DateUTC => "host.dateUTC",
            Self::StringNormalize => "host.stringNormalize",
            Self::IntlNumberFormatFormat => "host.intlNumberFormatFormat",
            Self::IntlDateTimeFormatFormat => "host.intlDateTimeFormatFormat",
            Self::ReflectApply => "host.reflectApply",
            Self::ReflectConstruct => "host.reflectConstruct",
            Self::GetIterator => "host.getIterator",
            Self::IteratorNext => "host.iteratorNext",
            Self::EvalDirect => "host.eval.direct",
            Self::EvalIndirect => "host.eval.indirect",
            Self::FunctionCompile => "host.function.compile",
            Self::FunctionCall => "host.function.call",
            Self::FunctionConstruct => "host.function.construct",
        }
    }
}
