[package]
name = "ts2wasm-backend-wasm"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
wasm-encoder-backend = ["dep:wasm-encoder"]

[dependencies]
ts2wasm-shared = { path = "../shared" }
ts2wasm-source = { path = "../source" }
ts2wasm-diagnostic = { path = "../diagnostic" }
ts2wasm-ir = { path = "../ir" }
ts2wasm-runtime-abi = { path = "../runtime-abi" }
ts2wasm-runtime-catalog = { path = "../runtime-catalog" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wasm-encoder = { version = "0.248", optional = true }
