//! Catalog of RuntimeFn variants handled by the Array domain.
//!
//! Array domain includes: Array, TypedArray, ArrayBuffer, and DataView operations.

use crate::runtime_fn::RuntimeFn;

/// All RuntimeFn variants routed through [`emit_dispatch_array`].
pub const ARRAY_FUNCTIONS: &[RuntimeFn] = &[
    RuntimeFn::ArrayGet,
    RuntimeFn::ArrayIndexPresent,
    RuntimeFn::ArrayPush,
    RuntimeFn::ArrayPushGrow,
    RuntimeFn::ArrayPop,
    RuntimeFn::ArraySlice,
    RuntimeFn::ArrayConcat,
    RuntimeFn::ArrayMapValueToString,
    RuntimeFn::ArrayMapUnaryPlus,
    RuntimeFn::ArrayMapStringSplit,
    RuntimeFn::ArrayMapArrayLikeIdentity,
    RuntimeFn::ArrayMapArrayLikeDouble,
    RuntimeFn::ArraySortNumeric,
    RuntimeFn::ArrayJoin,
    RuntimeFn::ArrayToReversed,
    RuntimeFn::ArrayToSorted,
    RuntimeFn::ArrayReverse,
    RuntimeFn::ArrayIsArray,
    RuntimeFn::ArrayIndexOf,
    RuntimeFn::ArrayIncludes,
    RuntimeFn::ArrayFind,
    RuntimeFn::ArrayFindIndex,
    RuntimeFn::ArrayFindLast,
    RuntimeFn::ArrayFindLastIndex,
    RuntimeFn::ArrayFilter,
    RuntimeFn::ArrayEvery,
    RuntimeFn::ArraySome,
    RuntimeFn::ArrayReduce,
    RuntimeFn::ArrayReduceRight,
    RuntimeFn::ArrayLastIndexOf,
    RuntimeFn::ArrayForEach,
    RuntimeFn::ArrayMap,
    RuntimeFn::ArrayAt,
    RuntimeFn::ArrayFill,
    RuntimeFn::ArrayFlat,
    RuntimeFn::ArrayPushOrSpread,
    RuntimeFn::ArrayCopyWithin,
    RuntimeFn::ArrayWith,
    RuntimeFn::ArrayValues,
    RuntimeFn::ArrayKeys,
    RuntimeFn::ArrayEntries,
    RuntimeFn::ArrayToSpliced,
    RuntimeFn::ArrayShift,
    RuntimeFn::ArrayUnshift,
    RuntimeFn::ArraySplice,
    RuntimeFn::ArrayBufferNew,
    RuntimeFn::TypedArrayFromArray,
    RuntimeFn::DataViewNew,
    RuntimeFn::DataViewGetInt32,
    RuntimeFn::DataViewSetInt32,
    RuntimeFn::DataViewGetFloat64,
    RuntimeFn::DataViewSetFloat64,
];
