use super::emitter::WatEmitter;
use super::runtime_fn::RuntimeFn;

impl WatEmitter<'_> {
    pub(super) fn emit_runtime(&mut self, wat: &mut String) {
        for runtime_fn in RuntimeFn::emission_order() {
            if !self
                .link_plan
                .required_runtime_functions()
                .contains(runtime_fn)
            {
                continue;
            }
            match runtime_fn {
                RuntimeFn::ReadStdinBytes => self.emit_read_stdin_bytes(wat),
                RuntimeFn::Write => self.emit_write(wat),
                RuntimeFn::Copy => self.emit_copy(wat),
                RuntimeFn::ValueToStringInto => self.emit_value_to_string_into(wat),
                RuntimeFn::ErrorMessage => self.emit_error_message(wat),
                RuntimeFn::Log => self.emit_log(wat),
                RuntimeFn::TruthyBool => self.emit_truthy_bool(wat),
                RuntimeFn::Not => self.emit_not(wat),
                RuntimeFn::TypeOf => self.emit_typeof(wat),
                RuntimeFn::MakeBigIntLiteral => self.emit_make_bigint_literal(wat),
                RuntimeFn::BigIntToString => self.emit_bigint_to_string(wat),
                RuntimeFn::BigIntToBoolean => self.emit_bigint_to_boolean(wat),
                RuntimeFn::BigIntFromValue => self.emit_bigint_from_value(wat),
                RuntimeFn::BigIntAsIntN => self.emit_bigint_as_int_n(wat),
                RuntimeFn::BigIntAsUintN => self.emit_bigint_as_uint_n(wat),
                RuntimeFn::BigIntUnaryMinus => self.emit_bigint_unary_minus(wat),
                RuntimeFn::BigIntAdd => self.emit_bigint_add(wat),
                RuntimeFn::BigIntSub => self.emit_bigint_sub(wat),
                RuntimeFn::BigIntMul => self.emit_bigint_mul(wat),
                RuntimeFn::BigIntDiv => self.emit_bigint_div(wat),
                RuntimeFn::BigIntRem => self.emit_bigint_rem(wat),
                RuntimeFn::BigIntCompare => self.emit_bigint_compare(wat),
                RuntimeFn::StringEqual => self.emit_string_equal(wat),
                RuntimeFn::Concat => self.emit_concat(wat),
                RuntimeFn::IsString => self.emit_is_string(wat),
                RuntimeFn::Add => self.emit_add(wat),
                RuntimeFn::AddFast => self.emit_add_fast(wat),
                RuntimeFn::Sub => self.emit_sub(wat),
                RuntimeFn::SubFast => self.emit_sub_fast(wat),
                RuntimeFn::Mul => self.emit_mul(wat),
                RuntimeFn::MulFast => self.emit_mul_fast(wat),
                RuntimeFn::Div => self.emit_div(wat),
                RuntimeFn::DivFast => self.emit_div_fast(wat),
                RuntimeFn::Mod => self.emit_mod(wat),
                RuntimeFn::ModFast => self.emit_mod_fast(wat),
                RuntimeFn::Negate => self.emit_negate(wat),
                RuntimeFn::Less => self.emit_less(wat),
                RuntimeFn::LessFast => self.emit_less_fast(wat),
                RuntimeFn::LessEqual => self.emit_less_equal(wat),
                RuntimeFn::LessEqualFast => self.emit_less_equal_fast(wat),
                RuntimeFn::Greater => self.emit_greater(wat),
                RuntimeFn::GreaterFast => self.emit_greater_fast(wat),
                RuntimeFn::GreaterEqual => self.emit_greater_equal(wat),
                RuntimeFn::GreaterEqualFast => self.emit_greater_equal_fast(wat),
                RuntimeFn::StrictEqual => self.emit_strict_equal(wat),
                RuntimeFn::EqualEqual => self.emit_equal_equal(wat),
                RuntimeFn::BangEqual => self.emit_bang_equal(wat),
                RuntimeFn::StrictNotEqual => self.emit_strict_not_equal(wat),
                RuntimeFn::And => self.emit_and(wat),
                RuntimeFn::Or => self.emit_or(wat),
                RuntimeFn::AllocHeap => self.emit_alloc_heap(wat),
                RuntimeFn::MemEqual => self.emit_mem_equal(wat),
                RuntimeFn::ArrayGet => self.emit_array_get(wat),
                RuntimeFn::Index => self.emit_index(wat),
                RuntimeFn::GetLength => self.emit_get_length(wat),
                RuntimeFn::PropertyGet => self.emit_property_get(wat),
                RuntimeFn::PropertySet => self.emit_property_set(wat),
                RuntimeFn::PropertyDelete => self.emit_property_delete(wat),
                RuntimeFn::PropertyHas => self.emit_property_has(wat),
                RuntimeFn::MapNew => self.emit_map_new(wat),
                RuntimeFn::MapGet => self.emit_map_get(wat),
                RuntimeFn::MapSet => self.emit_map_set(wat),
                RuntimeFn::MapHas => self.emit_map_has(wat),
                RuntimeFn::MapDelete => self.emit_map_delete(wat),
                RuntimeFn::SetNew => self.emit_set_new(wat),
                RuntimeFn::SetAdd => self.emit_set_add(wat),
                RuntimeFn::SetHas => self.emit_set_has(wat),
                RuntimeFn::SetDelete => self.emit_set_delete(wat),
                RuntimeFn::SetSize => self.emit_set_size(wat),
                RuntimeFn::SetClear => self.emit_set_clear(wat),
                RuntimeFn::SetFromArray => self.emit_set_from_array(wat),
                RuntimeFn::SetValuesArray => self.emit_set_values_array(wat),
                RuntimeFn::SetPrototypeAddGet => self.emit_set_prototype_add_get(wat),
                RuntimeFn::SetPrototypeAddSet => self.emit_set_prototype_add_set(wat),
                RuntimeFn::DateNew => self.emit_date_new(wat),
                RuntimeFn::DateNewLive => self.emit_date_new_live(wat),
                RuntimeFn::DateNow => self.emit_date_now(wat),
                RuntimeFn::DateEpochMsNowNumber => self.emit_date_epoch_ms_now_number(wat),
                RuntimeFn::DateGetTime => self.emit_date_get_time(wat),
                RuntimeFn::StringCharAt => self.emit_string_char_at(wat),
                RuntimeFn::StringSubstring => self.emit_string_substring(wat),
                RuntimeFn::StringSlice => self.emit_string_slice(wat),
                RuntimeFn::StringIndexOf => self.emit_string_index_of(wat),
                RuntimeFn::StringSplit => self.emit_string_split(wat),
                RuntimeFn::StringTrim => self.emit_string_trim(wat),
                RuntimeFn::StringToUpperCase => self.emit_string_to_upper_case(wat),
                RuntimeFn::StringToLowerCase => self.emit_string_to_lower_case(wat),
                RuntimeFn::StringCharCodeAt => self.emit_string_char_code_at(wat),
                RuntimeFn::StringFromCharCode => self.emit_string_from_char_code(wat),
                RuntimeFn::RegExpTest => self.emit_regexp_test(wat),
                RuntimeFn::RegExpMatch => self.emit_regexp_match(wat),
                RuntimeFn::ArrayPush => self.emit_array_push(wat),
                RuntimeFn::ArrayPop => self.emit_array_pop(wat),
                RuntimeFn::ArraySlice => self.emit_array_slice(wat),
                RuntimeFn::ArrayConcat => self.emit_array_concat(wat),
                RuntimeFn::ArrayJoin => self.emit_array_join(wat),
                RuntimeFn::ArrayReverse => self.emit_array_reverse(wat),
                RuntimeFn::ObjectKeys => self.emit_object_keys(wat),
                RuntimeFn::ObjectValues => self.emit_object_values(wat),
                RuntimeFn::ObjectEntries => self.emit_object_entries(wat),
                RuntimeFn::ObjectGetPrototypeOf => self.emit_object_get_prototype_of(wat),
                RuntimeFn::ObjectSetPrototypeOf => self.emit_object_set_prototype_of(wat),
                RuntimeFn::InstanceOf => self.emit_instanceof(wat),
                RuntimeFn::MathFloor => self.emit_math_floor(wat),
                RuntimeFn::MathCeil => self.emit_math_ceil(wat),
                RuntimeFn::MathRound => self.emit_math_round(wat),
                RuntimeFn::MathAbs => self.emit_math_abs(wat),
                RuntimeFn::MathMax => self.emit_math_max(wat),
                RuntimeFn::MathMin => self.emit_math_min(wat),
                RuntimeFn::MathPow => self.emit_math_pow(wat),
                RuntimeFn::MathRandom => self.emit_math_random(wat),
                RuntimeFn::JsonStringify => self.emit_json_stringify(wat),
                RuntimeFn::JsonParse => self.emit_json_parse(wat),
                RuntimeFn::ModuleRequire => self.emit_module_require(wat),
                RuntimeFn::ModuleExportsSet => self.emit_module_exports_set(wat),
                RuntimeFn::ModuleExportsAssign => self.emit_module_exports_assign(wat),
                RuntimeFn::FsReadFileSync => self.emit_fs_read_file_sync(wat),
                RuntimeFn::FsWriteFileSync => self.emit_fs_write_file_sync(wat),
                RuntimeFn::FsAppendFileSync => self.emit_fs_append_file_sync(wat),
                RuntimeFn::ProcessArgv => self.emit_process_argv(wat),
                RuntimeFn::ProcessEnv => self.emit_process_env(wat),
                RuntimeFn::ProcessExit => self.emit_process_exit(wat),
                RuntimeFn::PathJoin => self.emit_path_join(wat),
                RuntimeFn::PathResolve => self.emit_path_resolve(wat),
                RuntimeFn::PathBasename => self.emit_path_basename(wat),
                RuntimeFn::PathDirname => self.emit_path_dirname(wat),
                RuntimeFn::CryptoRandomBytes => self.emit_crypto_random_bytes(wat),
            }
        }
    }
}
