use super::emitter::WatEmitter;
use super::runtime_fn::RuntimeFn;

impl WatEmitter<'_> {
    /// Dispatch Core, Operator, TypeCoercion, Number, and Json domain runtime functions.
    pub(super) fn emit_dispatch_core(&mut self, f: RuntimeFn, wat: &mut String) {
        match f {
            RuntimeFn::ReadStdinBytes => self.emit_read_stdin_bytes(wat),
            RuntimeFn::Write => self.emit_write(wat),
            RuntimeFn::Copy => self.emit_copy(wat),
            RuntimeFn::ValueToStringInto => self.emit_value_to_string_into(wat),
            RuntimeFn::ErrorMessage => self.emit_error_message(wat),
            RuntimeFn::Log => self.emit_log(wat),
            RuntimeFn::PrivateBrandTypeError => self.emit_private_brand_type_error(wat),
            RuntimeFn::AllocHeap => self.emit_alloc_heap(wat),
            RuntimeFn::MemEqual => self.emit_mem_equal(wat),
            RuntimeFn::Index => self.emit_index(wat),
            RuntimeFn::GetLength => self.emit_get_length(wat),
            RuntimeFn::TruthyBool => self.emit_truthy_bool(wat),
            RuntimeFn::Not => self.emit_not(wat),
            RuntimeFn::TypeOf => self.emit_typeof(wat),
            RuntimeFn::IsString => self.emit_is_string(wat),
            RuntimeFn::InstanceOf => self.emit_instanceof(wat),
            RuntimeFn::IsNaN => self.emit_is_nan(wat),
            RuntimeFn::ParseInt => self.emit_parse_int(wat),
            RuntimeFn::ParseFloat => self.emit_parse_float(wat),
            RuntimeFn::IsFinite => self.emit_is_finite(wat),
            RuntimeFn::BooleanCoerce => self.emit_boolean_coerce(wat),
            RuntimeFn::NumberCoerce => self.emit_number_coerce(wat),
            RuntimeFn::ValueOf => self.emit_value_of(wat),
            RuntimeFn::NumberFromI32 => self.emit_number_from_i32(wat),
            RuntimeFn::NumberToI32 => self.emit_number_to_i32(wat),
            RuntimeFn::NumberToExponential => self.emit_value_to_string_into(wat),
            RuntimeFn::NumberToFixed => self.emit_value_to_string_into(wat),
            RuntimeFn::NumberToPrecision => self.emit_value_to_string_into(wat),
            RuntimeFn::NumberIsNaN => self.emit_number_is_nan(wat),
            RuntimeFn::NumberIsFinite => self.emit_number_is_finite(wat),
            RuntimeFn::NumberIsInteger => self.emit_number_is_integer(wat),
            RuntimeFn::NumberIsSafeInteger => self.emit_number_is_safe_integer(wat),
            RuntimeFn::Add => self.emit_add(wat),
            RuntimeFn::AddFast => self.emit_add_fast(wat),
            RuntimeFn::Sub => self.emit_sub(wat),
            RuntimeFn::SubFast => self.emit_sub_fast(wat),
            RuntimeFn::Mul => self.emit_mul(wat),
            RuntimeFn::MulFast => self.emit_mul_fast(wat),
            RuntimeFn::Div => self.emit_div(wat),
            RuntimeFn::DivFast => self.emit_div_fast(wat),
            RuntimeFn::Mod => self.emit_mod(wat),
            RuntimeFn::ModFast => self.emit_mod_fast(wat),
            RuntimeFn::BitwiseToI32 => self.emit_bitwise_to_i32(wat),
            RuntimeFn::BitwiseAnd => self.emit_bitwise_and(wat),
            RuntimeFn::BitwiseXor => self.emit_bitwise_xor(wat),
            RuntimeFn::BitwiseOr => self.emit_bitwise_or(wat),
            RuntimeFn::Negate => self.emit_negate(wat),
            RuntimeFn::Less => self.emit_less(wat),
            RuntimeFn::LessFast => self.emit_less_fast(wat),
            RuntimeFn::LessEqual => self.emit_less_equal(wat),
            RuntimeFn::LessEqualFast => self.emit_less_equal_fast(wat),
            RuntimeFn::Greater => self.emit_greater(wat),
            RuntimeFn::GreaterFast => self.emit_greater_fast(wat),
            RuntimeFn::GreaterEqual => self.emit_greater_equal(wat),
            RuntimeFn::GreaterEqualFast => self.emit_greater_equal_fast(wat),
            RuntimeFn::StrictEqual => self.emit_strict_equal(wat),
            RuntimeFn::EqualEqual => self.emit_equal_equal(wat),
            RuntimeFn::BangEqual => self.emit_bang_equal(wat),
            RuntimeFn::StrictNotEqual => self.emit_strict_not_equal(wat),
            RuntimeFn::And => self.emit_and(wat),
            RuntimeFn::Or => self.emit_or(wat),
            RuntimeFn::JsonStringify => self.emit_json_stringify(wat),
            RuntimeFn::JsonParse => self.emit_json_parse(wat),
            _ => unreachable!("non-core RuntimeFn routed to core dispatch"),
        }
    }
}
