use super::emitter::WatEmitter;
use super::runtime_fn::RuntimeFn;

impl WatEmitter<'_> {
    /// Dispatch Array and TypedArray domain runtime functions.
    pub(super) fn emit_dispatch_array(&mut self, f: RuntimeFn, wat: &mut String) {
        match f {
            RuntimeFn::ArrayGet => self.emit_array_get(wat),
            RuntimeFn::ArrayIndexPresent => self.emit_array_index_present(wat),
            RuntimeFn::ArrayPush => self.emit_array_push(wat),
            RuntimeFn::ArrayPushGrow => self.emit_array_push_grow(wat),
            RuntimeFn::ArrayPop => self.emit_array_pop(wat),
            RuntimeFn::ArraySlice => self.emit_array_slice(wat),
            RuntimeFn::ArrayConcat => self.emit_array_concat(wat),
            RuntimeFn::ArrayMapValueToString => self.emit_array_map_value_to_string(wat),
            RuntimeFn::ArrayMapUnaryPlus => self.emit_array_map_unary_plus(wat),
            RuntimeFn::ArrayMapStringSplit => self.emit_array_map_string_split(wat),
            RuntimeFn::ArrayMapArrayLikeIdentity => self.emit_array_map_array_like_identity(wat),
            RuntimeFn::ArrayMapArrayLikeDouble => self.emit_array_map_array_like_double(wat),
            RuntimeFn::ArraySortNumeric => self.emit_array_sort_numeric(wat),
            RuntimeFn::ArrayJoin => self.emit_array_join(wat),
            RuntimeFn::ArrayToReversed => self.emit_array_to_reversed(wat),
            RuntimeFn::ArrayToSorted => self.emit_array_to_sorted(wat),
            RuntimeFn::ArrayReverse => self.emit_array_reverse(wat),
            RuntimeFn::ArrayIsArray => self.emit_array_is_array(wat),
            RuntimeFn::ArrayIndexOf => self.emit_array_index_of(wat),
            RuntimeFn::ArrayIncludes => self.emit_array_includes(wat),
            RuntimeFn::ArrayFind => self.emit_array_find(wat),
            RuntimeFn::ArrayFindIndex => self.emit_array_find_index(wat),
            RuntimeFn::ArrayFindLast => self.emit_array_find_last(wat),
            RuntimeFn::ArrayFindLastIndex => self.emit_array_find_last_index(wat),
            RuntimeFn::ArrayFilter => self.emit_array_filter(wat),
            RuntimeFn::ArrayEvery => self.emit_array_every(wat),
            RuntimeFn::ArraySome => self.emit_array_some(wat),
            RuntimeFn::ArrayReduce => self.emit_array_reduce(wat),
            RuntimeFn::ArrayReduceRight => self.emit_array_reduce_right(wat),
            RuntimeFn::ArrayLastIndexOf => self.emit_array_last_index_of(wat),
            RuntimeFn::ArrayForEach => self.emit_array_for_each(wat),
            RuntimeFn::ArrayMap => self.emit_array_map(wat),
            RuntimeFn::ArrayAt => self.emit_array_at(wat),
            RuntimeFn::ArrayFill => self.emit_array_fill(wat),
            RuntimeFn::ArrayFlat => self.emit_array_flat(wat),
            RuntimeFn::ArrayPushOrSpread => self.emit_array_push_or_spread(wat),
            RuntimeFn::ArrayCopyWithin => self.emit_array_copy_within(wat),
            RuntimeFn::ArrayWith => self.emit_array_with(wat),
            RuntimeFn::ArrayValues => self.emit_array_values(wat),
            RuntimeFn::ArrayKeys => self.emit_array_keys(wat),
            RuntimeFn::ArrayEntries => self.emit_array_entries(wat),
            RuntimeFn::ArrayToSpliced => self.emit_array_to_spliced(wat),
            RuntimeFn::ArrayShift => self.emit_array_shift(wat),
            RuntimeFn::ArrayUnshift => self.emit_array_unshift(wat),
            RuntimeFn::ArraySplice => self.emit_array_splice(wat),
            RuntimeFn::ArrayBufferNew => self.emit_arraybuffer_new(wat),
            RuntimeFn::TypedArrayFromArray => self.emit_typed_array_from_array(wat),
            RuntimeFn::DataViewNew => self.emit_dataview_new(wat),
            RuntimeFn::DataViewGetInt32 => self.emit_dataview_get_int32(wat),
            RuntimeFn::DataViewSetInt32 => self.emit_dataview_set_int32(wat),
            RuntimeFn::DataViewGetFloat64 => self.emit_dataview_get_float64(wat),
            RuntimeFn::DataViewSetFloat64 => self.emit_dataview_set_float64(wat),
            _ => unreachable!("non-array RuntimeFn routed to array dispatch"),
        }
    }
}
