use super::emitter::WatEmitter;
use super::runtime_fn::RuntimeFn;

impl WatEmitter<'_> {
    /// Dispatch Date, Math, Promise, and Task domain runtime functions.
    pub(super) fn emit_dispatch_date(&mut self, f: RuntimeFn, wat: &mut String) {
        match f {
            RuntimeFn::DateNew => self.emit_date_new(wat),
            RuntimeFn::DateNewLive => self.emit_date_new_live(wat),
            RuntimeFn::DateNow => self.emit_date_now(wat),
            RuntimeFn::DateEpochMsNowNumber => self.emit_date_epoch_ms_now_number(wat),
            RuntimeFn::DateGetTime => self.emit_date_get_time(wat),
            RuntimeFn::DateToString => self.emit_date_to_string(wat),
            RuntimeFn::DateGetLocalTimeField => self.emit_date_get_local_time_field(wat),
            RuntimeFn::DateToISOString => self.emit_date_to_iso_string(wat),
            RuntimeFn::DateGetTimezoneOffset => self.emit_date_get_timezone_offset(wat),
            RuntimeFn::DateGetUtcMilliseconds => self.emit_date_get_utc_milliseconds(wat),
            RuntimeFn::DateGetUtcSeconds => self.emit_date_get_utc_seconds(wat),
            RuntimeFn::DateGetUtcMinutes => self.emit_date_get_utc_minutes(wat),
            RuntimeFn::DateGetUtcHours => self.emit_date_get_utc_hours(wat),
            RuntimeFn::DateGetUtcDay => self.emit_date_get_utc_day(wat),
            RuntimeFn::DateGetUtcDate => self.emit_date_get_utc_date(wat),
            RuntimeFn::DateGetUtcMonth => self.emit_date_get_utc_month(wat),
            RuntimeFn::DateGetUtcFullYear => self.emit_date_get_utc_full_year(wat),
            RuntimeFn::MathFloor => self.emit_math_floor(wat),
            RuntimeFn::MathCeil => self.emit_math_ceil(wat),
            RuntimeFn::MathRound => self.emit_math_round(wat),
            RuntimeFn::MathAbs => self.emit_math_abs(wat),
            RuntimeFn::MathMax => self.emit_math_max(wat),
            RuntimeFn::MathMin => self.emit_math_min(wat),
            RuntimeFn::MathPow => self.emit_math_pow(wat),
            RuntimeFn::MathRandom => self.emit_math_random(wat),
            RuntimeFn::MathTrunc => self.emit_math_trunc(wat),
            RuntimeFn::MathSign => self.emit_math_sign(wat),
            RuntimeFn::MathCbrt => self.emit_math_cbrt(wat),
            RuntimeFn::MathClz32 => self.emit_math_clz32(wat),
            RuntimeFn::MathImul => self.emit_math_imul(wat),
            RuntimeFn::MathSqrt => self.emit_math_sqrt(wat),
            RuntimeFn::MathAcos => self.emit_math_acos(wat),
            RuntimeFn::MathAcosh => self.emit_math_acosh(wat),
            RuntimeFn::MathAsin => self.emit_math_asin(wat),
            RuntimeFn::MathAsinh => self.emit_math_asinh(wat),
            RuntimeFn::MathAtan => self.emit_math_atan(wat),
            RuntimeFn::MathAtan2 => self.emit_math_atan2(wat),
            RuntimeFn::MathAtanh => self.emit_math_atanh(wat),
            RuntimeFn::MathCos => self.emit_math_cos(wat),
            RuntimeFn::MathCosh => self.emit_math_cosh(wat),
            RuntimeFn::MathExp => self.emit_math_exp(wat),
            RuntimeFn::MathExpm1 => self.emit_math_expm1(wat),
            RuntimeFn::MathFround => self.emit_math_fround(wat),
            RuntimeFn::MathHypot => self.emit_math_hypot(wat),
            RuntimeFn::MathLog => self.emit_math_log(wat),
            RuntimeFn::MathLog10 => self.emit_math_log10(wat),
            RuntimeFn::MathLog1p => self.emit_math_log1p(wat),
            RuntimeFn::MathLog2 => self.emit_math_log2(wat),
            RuntimeFn::MathSin => self.emit_math_sin(wat),
            RuntimeFn::MathSinh => self.emit_math_sinh(wat),
            RuntimeFn::MathTan => self.emit_math_tan(wat),
            RuntimeFn::MathTanh => self.emit_math_tanh(wat),
            RuntimeFn::PromiseConstructor => self.emit_promise_constructor(wat),
            RuntimeFn::PromiseResolve => self.emit_promise_resolve(wat),
            RuntimeFn::PromiseReject => self.emit_promise_reject(wat),
            RuntimeFn::PromiseThen => self.emit_promise_then(wat),
            RuntimeFn::PromiseCatch => self.emit_promise_catch(wat),
            RuntimeFn::PromiseFinally => self.emit_promise_finally(wat),
            RuntimeFn::PromiseAll => self.emit_promise_all(wat),
            RuntimeFn::PromiseAllSettled => self.emit_promise_all_settled(wat),
            RuntimeFn::PromiseAny => self.emit_promise_any(wat),
            RuntimeFn::PromiseRace => self.emit_promise_race(wat),
            RuntimeFn::PromiseWithResolvers => self.emit_promise_with_resolvers(wat),
            RuntimeFn::AggregateError => self.emit_aggregate_error(wat),
            RuntimeFn::TaskPoll => self.emit_task_poll(wat),
            RuntimeFn::TaskResult => self.emit_task_result(wat),
            RuntimeFn::TaskDrop => self.emit_task_drop(wat),
            _ => unreachable!("non-date/math/promise/task RuntimeFn routed to date dispatch"),
        }
    }
}
