use super::*;

impl RuntimeFn {
    pub(crate) const fn from_builtin(builtin: BuiltinId) -> Self {
        match builtin {
            BuiltinId::ConsoleLog => Self::Log,
            BuiltinId::ReadStdinUtf8 => Self::ReadStdinBytes,
            BuiltinId::FsReadFileSync => Self::FsReadFileSync,
            BuiltinId::FsWriteFileSync => Self::FsWriteFileSync,
            BuiltinId::FsAppendFileSync => Self::FsAppendFileSync,
            BuiltinId::ProcessArgv => Self::ProcessArgv,
            BuiltinId::ProcessEnv => Self::ProcessEnv,
            BuiltinId::ProcessExit => Self::ProcessExit,
            BuiltinId::PathJoin => Self::PathJoin,
            BuiltinId::PathResolve => Self::PathResolve,
            BuiltinId::PathBasename => Self::PathBasename,
            BuiltinId::PathDirname => Self::PathDirname,
            BuiltinId::CryptoRandomBytes => Self::CryptoRandomBytes,
            BuiltinId::InstanceOf => Self::InstanceOf,
            BuiltinId::MathPow => Self::MathPow,
        }
    }

    pub(crate) const fn spec(self) -> RuntimeSpec {
        match self {
            Self::ReadStdinBytes => RuntimeSpec {
                symbol: "$read_stdin_bytes",
                deps: READ_STDIN_DEPS,
                imports: IMPORT_FD_READ,
                capability: CAP_STDIN_READ,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Write => RuntimeSpec {
                symbol: "$write",
                deps: WRITE_DEPS,
                imports: IMPORT_FD_WRITE,
                capability: CAP_STDOUT_WRITE,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::EffectOnly,
            },
            Self::Copy => RuntimeSpec {
                symbol: "$copy",
                deps: COPY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::EffectOnly,
            },
            Self::ValueToStringInto => RuntimeSpec {
                symbol: "$value_to_string_into",
                deps: VTS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: VTS_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ErrorMessage => RuntimeSpec {
                symbol: "$error_message",
                deps: ERROR_MESSAGE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: VTS_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Log => RuntimeSpec {
                symbol: "$log",
                deps: LOG_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: LOG_RUNTIME_STRINGS,
                result: RuntimeResult::EffectOnly,
            },
            Self::TruthyBool => RuntimeSpec {
                symbol: "$truthy_bool",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Not => RuntimeSpec {
                symbol: "$not",
                deps: &[Self::TruthyBool],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::TypeOf => RuntimeSpec {
                symbol: "$typeof",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: TYPEOF_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::NumberFromI32 => RuntimeSpec {
                symbol: "$number_from_i32",
                deps: NUMBER_FROM_I32_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::NumberToI32 => RuntimeSpec {
                symbol: "$number_to_i32",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MakeBigIntLiteral => RuntimeSpec {
                symbol: "$make_bigint_literal",
                deps: MAKE_BIGINT_LITERAL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntToString => RuntimeSpec {
                symbol: "$bigint_to_string",
                deps: BIGINT_TO_STRING_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntToBoolean => RuntimeSpec {
                symbol: "$bigint_to_boolean",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntFromValue => RuntimeSpec {
                symbol: "$bigint_from_value",
                deps: BIGINT_FROM_VALUE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntAsIntN => RuntimeSpec {
                symbol: "$bigint_as_int_n",
                deps: BIGINT_AS_INT_N_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntAsUintN => RuntimeSpec {
                symbol: "$bigint_as_uint_n",
                deps: BIGINT_AS_UINT_N_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntUnaryMinus => RuntimeSpec {
                symbol: "$bigint_unary_minus",
                deps: BIGINT_UNARY_MINUS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntAdd => RuntimeSpec {
                symbol: "$bigint_add",
                deps: BIGINT_ADD_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntSub => RuntimeSpec {
                symbol: "$bigint_sub",
                deps: BIGINT_SUB_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntMul => RuntimeSpec {
                symbol: "$bigint_mul",
                deps: BIGINT_MUL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntPow => RuntimeSpec {
                symbol: "$bigint_pow",
                deps: BIGINT_POW_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntDiv => RuntimeSpec {
                symbol: "$bigint_div",
                deps: BIGINT_DIV_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntRem => RuntimeSpec {
                symbol: "$bigint_rem",
                deps: BIGINT_REM_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntMixedArithmeticTypeError => RuntimeSpec {
                symbol: "$bigint_mixed_arithmetic_type_error",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntBitwiseNot => RuntimeSpec {
                symbol: "$bigint_bitwise_not",
                deps: BIGINT_BITWISE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntBitwiseAnd => RuntimeSpec {
                symbol: "$bigint_bitwise_and",
                deps: BIGINT_BITWISE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntBitwiseOr => RuntimeSpec {
                symbol: "$bigint_bitwise_or",
                deps: BIGINT_BITWISE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntBitwiseXor => RuntimeSpec {
                symbol: "$bigint_bitwise_xor",
                deps: BIGINT_BITWISE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntCompare => RuntimeSpec {
                symbol: "$bigint_compare",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringEqual => RuntimeSpec {
                symbol: "$string_equal",
                deps: STRING_EQUAL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Concat => RuntimeSpec {
                symbol: "$concat",
                deps: CONCAT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::IsString => RuntimeSpec {
                symbol: "$is_string",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Add => RuntimeSpec {
                symbol: "$add",
                deps: ADD_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::AddFast => RuntimeSpec {
                symbol: "$add_fast",
                deps: ADD_FAST_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Sub => RuntimeSpec {
                symbol: "$sub",
                deps: NUMBER_ARITH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SubFast => RuntimeSpec {
                symbol: "$sub_fast",
                deps: SUB_FAST_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Mul => RuntimeSpec {
                symbol: "$mul",
                deps: NUMBER_ARITH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MulFast => RuntimeSpec {
                symbol: "$mul_fast",
                deps: MUL_FAST_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Div => RuntimeSpec {
                symbol: "$div",
                deps: NUMBER_ARITH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DivFast => RuntimeSpec {
                symbol: "$div_fast",
                deps: DIV_FAST_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Mod => RuntimeSpec {
                symbol: "$mod",
                deps: NUMBER_ARITH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ModFast => RuntimeSpec {
                symbol: "$mod_fast",
                deps: MOD_FAST_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Negate => RuntimeSpec {
                symbol: "$negate",
                deps: NUMBER_ARITH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Less => RuntimeSpec {
                symbol: "$less",
                deps: LESS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::LessFast => RuntimeSpec {
                symbol: "$less_fast",
                deps: LESS_FAST_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::LessEqual => RuntimeSpec {
                symbol: "$less_equal",
                deps: LESS_EQUAL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::LessEqualFast => RuntimeSpec {
                symbol: "$less_equal_fast",
                deps: LESS_EQUAL_FAST_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Greater => RuntimeSpec {
                symbol: "$greater",
                deps: GREATER_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::GreaterFast => RuntimeSpec {
                symbol: "$greater_fast",
                deps: GREATER_FAST_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::GreaterEqual => RuntimeSpec {
                symbol: "$greater_equal",
                deps: GREATER_EQUAL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::GreaterEqualFast => RuntimeSpec {
                symbol: "$greater_equal_fast",
                deps: GREATER_EQUAL_FAST_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StrictEqual => RuntimeSpec {
                symbol: "$strict_equal",
                deps: STRICT_EQUAL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::EqualEqual => RuntimeSpec {
                symbol: "$equal_equal",
                deps: EQUAL_EQUAL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BangEqual => RuntimeSpec {
                symbol: "$bang_equal",
                deps: BANG_EQUAL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StrictNotEqual => RuntimeSpec {
                symbol: "$strict_not_equal",
                deps: STRICT_NOT_EQUAL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::And => RuntimeSpec {
                symbol: "$and",
                deps: AND_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Or => RuntimeSpec {
                symbol: "$or",
                deps: OR_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::AllocHeap => RuntimeSpec {
                symbol: "$alloc_heap",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MemEqual => RuntimeSpec {
                symbol: "$mem_equal",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayGet => RuntimeSpec {
                symbol: "$array_get",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Index => RuntimeSpec {
                symbol: "$index",
                deps: INDEX_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::GetLength => RuntimeSpec {
                symbol: "$get_length",
                deps: &[Self::PropertyGet],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PropertyGet => RuntimeSpec {
                symbol: "$property_get",
                deps: &[Self::MemEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PropertySet => RuntimeSpec {
                symbol: "$property_set",
                deps: &[Self::AllocHeap, Self::Copy, Self::MemEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PropertyDelete => RuntimeSpec {
                symbol: "$property_delete",
                deps: &[Self::MemEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PropertyHas => RuntimeSpec {
                symbol: "$property_has",
                deps: &[Self::MemEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MapNew => RuntimeSpec {
                symbol: "$map_new",
                deps: MAP_NEW_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MapGet => RuntimeSpec {
                symbol: "$map_get",
                deps: MAP_GET_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MapSet => RuntimeSpec {
                symbol: "$map_set",
                deps: MAP_SET_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MapHas => RuntimeSpec {
                symbol: "$map_has",
                deps: MAP_HAS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MapDelete => RuntimeSpec {
                symbol: "$map_delete",
                deps: MAP_DELETE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetNew => RuntimeSpec {
                symbol: "$set_new",
                deps: SET_NEW_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetAdd => RuntimeSpec {
                symbol: "$set_add",
                deps: SET_ADD_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetHas => RuntimeSpec {
                symbol: "$set_has",
                deps: SET_HAS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetDelete => RuntimeSpec {
                symbol: "$set_delete",
                deps: SET_DELETE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetSize => RuntimeSpec {
                symbol: "$set_size",
                deps: SET_SIZE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetClear => RuntimeSpec {
                symbol: "$set_clear",
                deps: SET_CLEAR_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetFromArray => RuntimeSpec {
                symbol: "$set_from_array",
                deps: SET_FROM_ARRAY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetValuesArray => RuntimeSpec {
                symbol: "$set_values_array",
                deps: SET_VALUES_ARRAY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetPrototypeAddGet => RuntimeSpec {
                symbol: "$set_prototype_add_get",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetPrototypeAddSet => RuntimeSpec {
                symbol: "$set_prototype_add_set",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateNew => RuntimeSpec {
                symbol: "$date_new",
                deps: DATE_NEW_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateNewLive => RuntimeSpec {
                symbol: "$date_new_live",
                deps: DATE_NEW_LIVE_DEPS,
                imports: IMPORT_CLOCK_TIME_GET,
                capability: CAP_WASI_CLOCK_REALTIME,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateNow => RuntimeSpec {
                symbol: "$date_now",
                deps: DATE_NOW_DEPS,
                imports: IMPORT_CLOCK_TIME_GET,
                capability: CAP_WASI_CLOCK_REALTIME,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateEpochMsNowNumber => RuntimeSpec {
                symbol: "$date_epoch_ms_now_number",
                deps: DATE_EPOCH_MS_NOW_NUMBER_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateGetTime => RuntimeSpec {
                symbol: "$date_get_time",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringCharAt => RuntimeSpec {
                symbol: "$string_char_at",
                deps: STRING_CHAR_AT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringSubstring => RuntimeSpec {
                symbol: "$string_substring",
                deps: STRING_SUBSTRING_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringSlice => RuntimeSpec {
                symbol: "$string_slice",
                deps: STRING_SLICE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringIndexOf => RuntimeSpec {
                symbol: "$string_index_of",
                deps: STRING_INDEX_OF_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringSplit => RuntimeSpec {
                symbol: "$string_split",
                deps: STRING_SPLIT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringTrim => RuntimeSpec {
                symbol: "$string_trim",
                deps: STRING_TRIM_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringToUpperCase => RuntimeSpec {
                symbol: "$string_to_upper_case",
                deps: STRING_TO_UPPER_CASE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringToLowerCase => RuntimeSpec {
                symbol: "$string_to_lower_case",
                deps: STRING_TO_LOWER_CASE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringCharCodeAt => RuntimeSpec {
                symbol: "$string_char_code_at",
                deps: STRING_CHAR_CODE_AT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringFromCharCode => RuntimeSpec {
                symbol: "$string_from_char_code",
                deps: STRING_FROM_CHAR_CODE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::RegExpTest => RuntimeSpec {
                symbol: "$regexp_test",
                deps: REGEXP_TEST_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::RegExpMatch => RuntimeSpec {
                symbol: "$regexp_match",
                deps: REGEXP_MATCH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayPush => RuntimeSpec {
                symbol: "$array_push",
                deps: ARRAY_PUSH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayPushGrow => RuntimeSpec {
                symbol: "$array_push_grow",
                deps: ARRAY_PUSH_GROW_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayPop => RuntimeSpec {
                symbol: "$array_pop",
                deps: ARRAY_POP_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArraySlice => RuntimeSpec {
                symbol: "$array_slice",
                deps: ARRAY_SLICE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayConcat => RuntimeSpec {
                symbol: "$array_concat",
                deps: ARRAY_CONCAT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayMapValueToString => RuntimeSpec {
                symbol: "$array_map_value_to_string",
                deps: ARRAY_MAP_VALUE_TO_STRING_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayMapUnaryPlus => RuntimeSpec {
                symbol: "$array_map_unary_plus",
                deps: ARRAY_MAP_UNARY_PLUS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayMapStringSplit => RuntimeSpec {
                symbol: "$array_map_string_split",
                deps: ARRAY_MAP_STRING_SPLIT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayMapArrayLikeIdentity => RuntimeSpec {
                symbol: "$array_map_array_like_identity",
                deps: ARRAY_MAP_ARRAY_LIKE_IDENTITY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArraySortNumeric => RuntimeSpec {
                symbol: "$array_sort_numeric",
                deps: ARRAY_SORT_NUMERIC_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayJoin => RuntimeSpec {
                symbol: "$array_join",
                deps: ARRAY_JOIN_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayReverse => RuntimeSpec {
                symbol: "$array_reverse",
                deps: ARRAY_REVERSE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectKeys => RuntimeSpec {
                symbol: "$object_keys",
                deps: OBJECT_KEYS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectSpread => RuntimeSpec {
                symbol: "$object_spread",
                deps: OBJECT_SPREAD_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectValues => RuntimeSpec {
                symbol: "$object_values",
                deps: OBJECT_VALUES_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectEntries => RuntimeSpec {
                symbol: "$object_entries",
                deps: OBJECT_ENTRIES_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectGetPrototypeOf => RuntimeSpec {
                symbol: "$object_get_prototype_of",
                deps: OBJECT_PROTOTYPE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectSetPrototypeOf => RuntimeSpec {
                symbol: "$object_set_prototype_of",
                deps: OBJECT_PROTOTYPE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::InstanceOf => RuntimeSpec {
                symbol: "$instanceof",
                deps: &[],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MathFloor => RuntimeSpec {
                symbol: "$math_floor",
                deps: MATH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MathCeil => RuntimeSpec {
                symbol: "$math_ceil",
                deps: MATH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MathRound => RuntimeSpec {
                symbol: "$math_round",
                deps: MATH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MathAbs => RuntimeSpec {
                symbol: "$math_abs",
                deps: MATH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MathMax => RuntimeSpec {
                symbol: "$math_max",
                deps: MATH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MathMin => RuntimeSpec {
                symbol: "$math_min",
                deps: MATH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MathPow => RuntimeSpec {
                symbol: "$math_pow",
                deps: MATH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MathRandom => RuntimeSpec {
                symbol: "$math_random",
                deps: MATH_RANDOM_DEPS,
                imports: IMPORT_RANDOM_GET,
                capability: CAP_WASI_RANDOM,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::JsonStringify => RuntimeSpec {
                symbol: "$json_stringify",
                deps: JSON_STRINGIFY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: JSON_STRINGIFY_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::JsonParse => RuntimeSpec {
                symbol: "$json_parse",
                deps: JSON_PARSE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: JSON_PARSE_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ModuleRequire => RuntimeSpec {
                symbol: "$module_require",
                deps: &[Self::AllocHeap],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ModuleExportsSet => RuntimeSpec {
                symbol: "$module_exports_set",
                deps: &[Self::AllocHeap, Self::PropertySet],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::EffectOnly,
            },
            Self::ModuleExportsAssign => RuntimeSpec {
                symbol: "$module_exports_assign",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::EffectOnly,
            },
            Self::FsReadFileSync => RuntimeSpec {
                symbol: "$fs_read_file_sync",
                deps: NO_DEPS,
                imports: IMPORT_FS_READ_FILE_SYNC,
                capability: CAP_HOST_FS_READ_FILE_SYNC,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::FsWriteFileSync => RuntimeSpec {
                symbol: "$fs_write_file_sync",
                deps: NO_DEPS,
                imports: IMPORT_FS_WRITE_FILE_SYNC,
                capability: CAP_HOST_FS_WRITE_FILE_SYNC,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::FsAppendFileSync => RuntimeSpec {
                symbol: "$fs_append_file_sync",
                deps: NO_DEPS,
                imports: IMPORT_FS_APPEND_FILE_SYNC,
                capability: CAP_HOST_FS_APPEND_FILE_SYNC,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ProcessArgv => RuntimeSpec {
                symbol: "$process_argv",
                deps: NO_DEPS,
                imports: IMPORT_PROCESS_ARGV,
                capability: CAP_HOST_PROCESS_ARGV,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ProcessEnv => RuntimeSpec {
                symbol: "$process_env",
                deps: NO_DEPS,
                imports: IMPORT_PROCESS_ENV,
                capability: CAP_HOST_PROCESS_ENV,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ProcessExit => RuntimeSpec {
                symbol: "$process_exit",
                deps: NO_DEPS,
                imports: IMPORT_PROCESS_EXIT,
                capability: CAP_HOST_PROCESS_EXIT,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::EffectOnly,
            },
            Self::PathJoin => RuntimeSpec {
                symbol: "$path_join",
                deps: NO_DEPS,
                imports: IMPORT_PATH_JOIN,
                capability: CAP_HOST_PATH_JOIN,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PathResolve => RuntimeSpec {
                symbol: "$path_resolve",
                deps: NO_DEPS,
                imports: IMPORT_PATH_RESOLVE,
                capability: CAP_HOST_PATH_RESOLVE,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PathBasename => RuntimeSpec {
                symbol: "$path_basename",
                deps: NO_DEPS,
                imports: IMPORT_PATH_BASENAME,
                capability: CAP_HOST_PATH_BASENAME,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PathDirname => RuntimeSpec {
                symbol: "$path_dirname",
                deps: NO_DEPS,
                imports: IMPORT_PATH_DIRNAME,
                capability: CAP_HOST_PATH_DIRNAME,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::CryptoRandomBytes => RuntimeSpec {
                symbol: "$crypto_random_bytes",
                deps: NO_DEPS,
                imports: IMPORT_CRYPTO_RANDOM_BYTES,
                capability: CAP_HOST_CRYPTO_RANDOM_BYTES,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
        }
    }

    pub(crate) const fn symbol(self) -> &'static str {
        self.spec().symbol
    }

    pub(crate) const fn globals(self) -> &'static [RuntimeGlobal] {
        match self {
            Self::AllocHeap => GLOBALS_ALLOC_HEAP,
            Self::ModuleRequire | Self::ModuleExportsSet | Self::ModuleExportsAssign => {
                GLOBALS_MODULE_RUNTIME
            }
            Self::SetFromArray | Self::SetPrototypeAddGet | Self::SetPrototypeAddSet => {
                GLOBALS_SET_PROTOTYPE_ADD
            }
            _ => NO_GLOBALS,
        }
    }

    pub(crate) const fn result(self) -> RuntimeResult {
        self.spec().result
    }

    pub(crate) const fn is_value(self) -> bool {
        matches!(self.result(), RuntimeResult::Value)
    }

    /// Get the manifest name for this runtime function (derived from symbol).
    /// This is not const because it matches on strings.
    pub(crate) fn manifest_name(self) -> &'static str {
        match self {
            Self::ReadStdinBytes => "read_stdin_bytes",
            Self::Write => "write",
            Self::Copy => "copy",
            Self::ValueToStringInto => "value_to_string_into",
            Self::ErrorMessage => "error_message",
            Self::Log => "log",
            Self::TruthyBool => "truthy_bool",
            Self::Not => "not",
            Self::TypeOf => "typeof",
            Self::NumberFromI32 => "number_from_i32",
            Self::NumberToI32 => "number_to_i32",
            Self::MakeBigIntLiteral => "make_bigint_literal",
            Self::BigIntToString => "bigint_to_string",
            Self::BigIntToBoolean => "bigint_to_boolean",
            Self::BigIntFromValue => "bigint_from_value",
            Self::BigIntAsIntN => "bigint_as_int_n",
            Self::BigIntAsUintN => "bigint_as_uint_n",
            Self::BigIntUnaryMinus => "bigint_unary_minus",
            Self::BigIntAdd => "bigint_add",
            Self::BigIntSub => "bigint_sub",
            Self::BigIntMul => "bigint_mul",
            Self::BigIntPow => "bigint_pow",
            Self::BigIntDiv => "bigint_div",
            Self::BigIntRem => "bigint_rem",
            Self::BigIntMixedArithmeticTypeError => "bigint_mixed_arithmetic_type_error",
            Self::BigIntBitwiseNot => "bigint_bitwise_not",
            Self::BigIntBitwiseAnd => "bigint_bitwise_and",
            Self::BigIntBitwiseOr => "bigint_bitwise_or",
            Self::BigIntBitwiseXor => "bigint_bitwise_xor",
            Self::BigIntCompare => "bigint_compare",
            Self::StringEqual => "string_equal",
            Self::Concat => "concat",
            Self::IsString => "is_string",
            Self::Add => "add",
            Self::AddFast => "add_fast",
            Self::Sub => "sub",
            Self::SubFast => "sub_fast",
            Self::Mul => "mul",
            Self::MulFast => "mul_fast",
            Self::Div => "div",
            Self::DivFast => "div_fast",
            Self::Mod => "mod",
            Self::ModFast => "mod_fast",
            Self::Negate => "negate",
            Self::Less => "less",
            Self::LessFast => "less_fast",
            Self::LessEqual => "less_equal",
            Self::LessEqualFast => "less_equal_fast",
            Self::Greater => "greater",
            Self::GreaterFast => "greater_fast",
            Self::GreaterEqual => "greater_equal",
            Self::GreaterEqualFast => "greater_equal_fast",
            Self::StrictEqual => "strict_equal",
            Self::EqualEqual => "equal_equal",
            Self::BangEqual => "bang_equal",
            Self::StrictNotEqual => "strict_not_equal",
            Self::And => "and",
            Self::Or => "or",
            Self::AllocHeap => "alloc_heap",
            Self::MemEqual => "mem_equal",
            Self::ArrayGet => "array_get",
            Self::Index => "index",
            Self::GetLength => "get_length",
            Self::PropertyGet => "property_get",
            Self::PropertySet => "property_set",
            Self::PropertyDelete => "property_delete",
            Self::PropertyHas => "property_has",
            Self::MapNew => "map_new",
            Self::MapGet => "map_get",
            Self::MapSet => "map_set",
            Self::MapHas => "map_has",
            Self::MapDelete => "map_delete",
            Self::SetNew => "set_new",
            Self::SetAdd => "set_add",
            Self::SetHas => "set_has",
            Self::SetDelete => "set_delete",
            Self::SetSize => "set_size",
            Self::SetClear => "set_clear",
            Self::SetFromArray => "set_from_array",
            Self::SetValuesArray => "set_values_array",
            Self::SetPrototypeAddGet => "set_prototype_add_get",
            Self::SetPrototypeAddSet => "set_prototype_add_set",
            Self::DateNew => "date_new",
            Self::DateNewLive => "date_new_live",
            Self::DateNow => "date_now",
            Self::DateEpochMsNowNumber => "date_epoch_ms_now_number",
            Self::DateGetTime => "date_get_time",
            Self::StringCharAt => "string_char_at",
            Self::StringSubstring => "string_substring",
            Self::StringSlice => "string_slice",
            Self::StringIndexOf => "string_index_of",
            Self::StringSplit => "string_split",
            Self::StringTrim => "string_trim",
            Self::StringToUpperCase => "string_to_upper_case",
            Self::StringToLowerCase => "string_to_lower_case",
            Self::StringCharCodeAt => "string_char_code_at",
            Self::StringFromCharCode => "string_from_char_code",
            Self::RegExpTest => "regexp_test",
            Self::RegExpMatch => "regexp_match",
            Self::ArrayPush => "array_push",
            Self::ArrayPushGrow => "array_push_grow",
            Self::ArrayPop => "array_pop",
            Self::ArraySlice => "array_slice",
            Self::ArrayConcat => "array_concat",
            Self::ArrayMapValueToString => "array_map_value_to_string",
            Self::ArrayMapUnaryPlus => "array_map_unary_plus",
            Self::ArrayMapStringSplit => "array_map_string_split",
            Self::ArrayMapArrayLikeIdentity => "array_map_array_like_identity",
            Self::ArraySortNumeric => "array_sort_numeric",
            Self::ArrayJoin => "array_join",
            Self::ArrayReverse => "array_reverse",
            Self::ObjectKeys => "object_keys",
            Self::ObjectSpread => "object_spread",
            Self::ObjectValues => "object_values",
            Self::ObjectEntries => "object_entries",
            Self::ObjectGetPrototypeOf => "object_get_prototype_of",
            Self::ObjectSetPrototypeOf => "object_set_prototype_of",
            Self::MathFloor => "math_floor",
            Self::MathCeil => "math_ceil",
            Self::MathRound => "math_round",
            Self::MathAbs => "math_abs",
            Self::MathMax => "math_max",
            Self::MathMin => "math_min",
            Self::MathPow => "math_pow",
            Self::MathRandom => "math_random",
            Self::JsonStringify => "json_stringify",
            Self::JsonParse => "json_parse",
            Self::ModuleRequire => "module_require",
            Self::ModuleExportsSet => "module_exports_set",
            Self::ModuleExportsAssign => "module_exports_assign",
            Self::FsReadFileSync => "fs_read_file_sync",
            Self::FsWriteFileSync => "fs_write_file_sync",
            Self::FsAppendFileSync => "fs_append_file_sync",
            Self::ProcessArgv => "process_argv",
            Self::ProcessEnv => "process_env",
            Self::ProcessExit => "process_exit",
            Self::PathJoin => "path_join",
            Self::PathResolve => "path_resolve",
            Self::PathBasename => "path_basename",
            Self::PathDirname => "path_dirname",
            Self::CryptoRandomBytes => "crypto_random_bytes",
            Self::InstanceOf => "instanceof",
        }
    }

    pub(crate) const fn emission_order() -> &'static [RuntimeFn] {
        &[
            Self::ReadStdinBytes,
            Self::Write,
            Self::Copy,
            Self::ValueToStringInto,
            Self::ErrorMessage,
            Self::Log,
            Self::TruthyBool,
            Self::Not,
            Self::TypeOf,
            Self::NumberFromI32,
            Self::NumberToI32,
            Self::StringEqual,
            Self::Concat,
            Self::IsString,
            Self::Add,
            Self::AddFast,
            Self::Sub,
            Self::SubFast,
            Self::Mul,
            Self::MulFast,
            Self::Div,
            Self::DivFast,
            Self::Mod,
            Self::ModFast,
            Self::Negate,
            Self::BigIntCompare,
            Self::Less,
            Self::LessFast,
            Self::LessEqual,
            Self::LessEqualFast,
            Self::Greater,
            Self::GreaterFast,
            Self::GreaterEqual,
            Self::GreaterEqualFast,
            Self::StrictEqual,
            Self::EqualEqual,
            Self::BangEqual,
            Self::StrictNotEqual,
            Self::And,
            Self::Or,
            Self::AllocHeap,
            Self::MakeBigIntLiteral,
            Self::BigIntToString,
            Self::BigIntToBoolean,
            Self::BigIntAdd,
            Self::BigIntFromValue,
            Self::BigIntAsIntN,
            Self::BigIntAsUintN,
            Self::BigIntUnaryMinus,
            Self::BigIntSub,
            Self::BigIntMul,
            Self::BigIntPow,
            Self::BigIntDiv,
            Self::BigIntRem,
            Self::BigIntMixedArithmeticTypeError,
            Self::BigIntBitwiseNot,
            Self::BigIntBitwiseAnd,
            Self::BigIntBitwiseOr,
            Self::BigIntBitwiseXor,
            Self::MemEqual,
            Self::ArrayGet,
            Self::Index,
            Self::GetLength,
            Self::PropertyGet,
            Self::PropertySet,
            Self::PropertyDelete,
            Self::PropertyHas,
            Self::MapNew,
            Self::MapGet,
            Self::MapSet,
            Self::MapHas,
            Self::MapDelete,
            Self::SetNew,
            Self::SetAdd,
            Self::SetHas,
            Self::SetDelete,
            Self::SetSize,
            Self::SetClear,
            Self::SetFromArray,
            Self::SetValuesArray,
            Self::SetPrototypeAddGet,
            Self::SetPrototypeAddSet,
            Self::DateNew,
            Self::DateEpochMsNowNumber,
            Self::DateNewLive,
            Self::DateNow,
            Self::DateGetTime,
            // String methods
            Self::StringCharAt,
            Self::StringSubstring,
            Self::StringSlice,
            Self::StringIndexOf,
            Self::StringSplit,
            Self::StringTrim,
            Self::StringToUpperCase,
            Self::StringToLowerCase,
            Self::StringCharCodeAt,
            Self::StringFromCharCode,
            Self::RegExpTest,
            Self::RegExpMatch,
            // Array methods
            Self::ArrayPush,
            Self::ArrayPushGrow,
            Self::ArrayPop,
            Self::ArraySlice,
            Self::ArrayConcat,
            Self::ArrayMapValueToString,
            Self::ArrayMapUnaryPlus,
            Self::ArrayMapStringSplit,
            Self::ArrayMapArrayLikeIdentity,
            Self::ArraySortNumeric,
            Self::ArrayJoin,
            Self::ArrayReverse,
            // Object statics
            Self::ObjectKeys,
            Self::ObjectSpread,
            Self::ObjectValues,
            Self::ObjectEntries,
            Self::ObjectGetPrototypeOf,
            Self::ObjectSetPrototypeOf,
            // Instanceof operator
            Self::InstanceOf,
            // Math functions
            Self::MathFloor,
            Self::MathCeil,
            Self::MathRound,
            Self::MathAbs,
            Self::MathMax,
            Self::MathMin,
            Self::MathPow,
            Self::MathRandom,
            // JSON functions
            Self::JsonStringify,
            Self::JsonParse,
            // Module system functions
            Self::ModuleRequire,
            Self::ModuleExportsSet,
            Self::ModuleExportsAssign,
            // Node host wrappers
            Self::FsReadFileSync,
            Self::FsWriteFileSync,
            Self::FsAppendFileSync,
            Self::ProcessArgv,
            Self::ProcessEnv,
            Self::ProcessExit,
            Self::PathJoin,
            Self::PathResolve,
            Self::PathBasename,
            Self::PathDirname,
            Self::CryptoRandomBytes,
        ]
    }

    #[cfg(test)]
    pub(crate) const fn all() -> &'static [RuntimeFn] {
        &[
            Self::ReadStdinBytes,
            Self::Write,
            Self::Copy,
            Self::ValueToStringInto,
            Self::ErrorMessage,
            Self::Log,
            Self::TruthyBool,
            Self::Not,
            Self::TypeOf,
            Self::NumberFromI32,
            Self::NumberToI32,
            Self::StringEqual,
            Self::Concat,
            Self::IsString,
            Self::Add,
            Self::AddFast,
            Self::Sub,
            Self::SubFast,
            Self::Mul,
            Self::MulFast,
            Self::Div,
            Self::DivFast,
            Self::Mod,
            Self::ModFast,
            Self::Negate,
            Self::BigIntCompare,
            Self::Less,
            Self::LessFast,
            Self::LessEqual,
            Self::LessEqualFast,
            Self::Greater,
            Self::GreaterFast,
            Self::GreaterEqual,
            Self::GreaterEqualFast,
            Self::StrictEqual,
            Self::EqualEqual,
            Self::BangEqual,
            Self::StrictNotEqual,
            Self::And,
            Self::Or,
            Self::AllocHeap,
            Self::MakeBigIntLiteral,
            Self::BigIntToString,
            Self::BigIntToBoolean,
            Self::BigIntAdd,
            Self::BigIntFromValue,
            Self::BigIntAsIntN,
            Self::BigIntAsUintN,
            Self::BigIntUnaryMinus,
            Self::BigIntSub,
            Self::BigIntMul,
            Self::BigIntPow,
            Self::BigIntDiv,
            Self::BigIntRem,
            Self::BigIntMixedArithmeticTypeError,
            Self::BigIntBitwiseNot,
            Self::BigIntBitwiseAnd,
            Self::BigIntBitwiseOr,
            Self::BigIntBitwiseXor,
            Self::MemEqual,
            Self::ArrayGet,
            Self::Index,
            Self::GetLength,
            Self::PropertyGet,
            Self::PropertySet,
            Self::PropertyDelete,
            Self::PropertyHas,
            Self::MapNew,
            Self::MapGet,
            Self::MapSet,
            Self::MapHas,
            Self::MapDelete,
            Self::SetNew,
            Self::SetAdd,
            Self::SetHas,
            Self::SetDelete,
            Self::SetSize,
            Self::SetClear,
            Self::SetFromArray,
            Self::SetValuesArray,
            Self::SetPrototypeAddGet,
            Self::SetPrototypeAddSet,
            Self::DateNew,
            Self::DateEpochMsNowNumber,
            Self::DateNewLive,
            Self::DateNow,
            Self::DateGetTime,
            // String methods
            Self::StringCharAt,
            Self::StringSubstring,
            Self::StringSlice,
            Self::StringIndexOf,
            Self::StringSplit,
            Self::StringTrim,
            Self::StringToUpperCase,
            Self::StringToLowerCase,
            Self::StringCharCodeAt,
            Self::StringFromCharCode,
            Self::RegExpTest,
            Self::RegExpMatch,
            // Array methods
            Self::ArrayPush,
            Self::ArrayPushGrow,
            Self::ArrayPop,
            Self::ArraySlice,
            Self::ArrayConcat,
            Self::ArrayMapValueToString,
            Self::ArrayMapUnaryPlus,
            Self::ArrayMapStringSplit,
            Self::ArrayMapArrayLikeIdentity,
            Self::ArraySortNumeric,
            Self::ArrayJoin,
            Self::ArrayReverse,
            // Object statics
            Self::ObjectKeys,
            Self::ObjectSpread,
            Self::ObjectValues,
            Self::ObjectEntries,
            Self::ObjectGetPrototypeOf,
            Self::ObjectSetPrototypeOf,
            // Instanceof operator
            Self::InstanceOf,
            // Math functions
            Self::MathFloor,
            Self::MathCeil,
            Self::MathRound,
            Self::MathAbs,
            Self::MathMax,
            Self::MathMin,
            Self::MathPow,
            Self::MathRandom,
            // JSON functions
            Self::JsonStringify,
            Self::JsonParse,
            // Module system functions
            Self::ModuleRequire,
            Self::ModuleExportsSet,
            Self::ModuleExportsAssign,
            // Node host wrappers
            Self::FsReadFileSync,
            Self::FsWriteFileSync,
            Self::FsAppendFileSync,
            Self::ProcessArgv,
            Self::ProcessEnv,
            Self::ProcessExit,
            Self::PathJoin,
            Self::PathResolve,
            Self::PathBasename,
            Self::PathDirname,
            Self::CryptoRandomBytes,
        ]
    }
}
