// Combined spec arms -- auto-generated.
// Regenerate with: python3 scripts/refactor/extract-runtime-domains.py
match self {
            Self::ArrayGet => RuntimeSpec {
                symbol: "$array_get",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayIndexPresent => RuntimeSpec {
                symbol: "$array_index_present",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayBufferNew => RuntimeSpec {
                symbol: "$arraybuffer_new",
                deps: ARRAYBUFFER_NEW_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayPush => RuntimeSpec {
                symbol: "$array_push",
                deps: ARRAY_PUSH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayPushGrow => RuntimeSpec {
                symbol: "$array_push_grow",
                deps: ARRAY_PUSH_GROW_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayPop => RuntimeSpec {
                symbol: "$array_pop",
                deps: ARRAY_POP_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArraySlice => RuntimeSpec {
                symbol: "$array_slice",
                deps: ARRAY_SLICE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayConcat => RuntimeSpec {
                symbol: "$array_concat",
                deps: ARRAY_CONCAT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayMapValueToString => RuntimeSpec {
                symbol: "$array_map_value_to_string",
                deps: ARRAY_MAP_VALUE_TO_STRING_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayMapUnaryPlus => RuntimeSpec {
                symbol: "$array_map_unary_plus",
                deps: ARRAY_MAP_UNARY_PLUS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayMapStringSplit => RuntimeSpec {
                symbol: "$array_map_string_split",
                deps: ARRAY_MAP_STRING_SPLIT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayMapArrayLikeIdentity => RuntimeSpec {
                symbol: "$array_map_array_like_identity",
                deps: ARRAY_MAP_ARRAY_LIKE_IDENTITY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayMapArrayLikeDouble => RuntimeSpec {
                symbol: "$array_map_array_like_double",
                deps: ARRAY_MAP_ARRAY_LIKE_DOUBLE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArraySortNumeric => RuntimeSpec {
                symbol: "$array_sort_numeric",
                deps: ARRAY_SORT_NUMERIC_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayJoin => RuntimeSpec {
                symbol: "$array_join",
                deps: ARRAY_JOIN_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayReverse => RuntimeSpec {
                symbol: "$array_reverse",
                deps: ARRAY_REVERSE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayIndexOf => RuntimeSpec {
                symbol: "$array_index_of",
                deps: ARRAY_INDEX_OF_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayIncludes => RuntimeSpec {
                symbol: "$array_includes",
                deps: ARRAY_INCLUDES_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayFind => RuntimeSpec {
                symbol: "$array_find",
                deps: ARRAY_FIND_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayFindIndex => RuntimeSpec {
                symbol: "$array_find_index",
                deps: ARRAY_FIND_INDEX_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayFindLast => RuntimeSpec {
                symbol: "$array_find_last",
                deps: ARRAY_FIND_LAST_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayFindLastIndex => RuntimeSpec {
                symbol: "$array_find_last_index",
                deps: ARRAY_FIND_LAST_INDEX_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayFilter => RuntimeSpec {
                symbol: "$array_filter",
                deps: ARRAY_FILTER_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayEvery => RuntimeSpec {
                symbol: "$array_every",
                deps: ARRAY_EVERY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArraySome => RuntimeSpec {
                symbol: "$array_some",
                deps: ARRAY_SOME_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayReduce => RuntimeSpec {
                symbol: "$array_reduce",
                deps: ARRAY_REDUCE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayReduceRight => RuntimeSpec {
                symbol: "$array_reduce_right",
                deps: ARRAY_REDUCE_RIGHT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayLastIndexOf => RuntimeSpec {
                symbol: "$array_last_index_of",
                deps: ARRAY_LAST_INDEX_OF_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayForEach => RuntimeSpec {
                symbol: "$array_for_each",
                deps: ARRAY_FOR_EACH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayMap => RuntimeSpec {
                symbol: "$array_map",
                deps: ARRAY_MAP_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayAt => RuntimeSpec {
                symbol: "$array_at",
                deps: ARRAY_AT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayFill => RuntimeSpec {
                symbol: "$array_fill",
                deps: ARRAY_FILL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayFlat => RuntimeSpec {
                symbol: "$array_flat",
                deps: ARRAY_FLAT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayPushOrSpread => RuntimeSpec {
                symbol: "$array_push_or_spread",
                deps: ARRAY_PUSH_OR_SPREAD_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayCopyWithin => RuntimeSpec {
                symbol: "$array_copy_within",
                deps: ARRAY_COPY_WITHIN_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayWith => RuntimeSpec {
                symbol: "$array_with",
                deps: ARRAY_WITH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayToReversed => RuntimeSpec {
                symbol: "$array_to_reversed",
                deps: ARRAY_TO_REVERSED_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayToSorted => RuntimeSpec {
                symbol: "$array_to_sorted",
                deps: ARRAY_TO_SORTED_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayToSpliced => RuntimeSpec {
                symbol: "$array_to_spliced",
                deps: ARRAY_TO_SPLICED_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayValues => RuntimeSpec {
                symbol: "$array_values",
                deps: ARRAY_VALUES_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayKeys => RuntimeSpec {
                symbol: "$array_keys",
                deps: ARRAY_KEYS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayEntries => RuntimeSpec {
                symbol: "$array_entries",
                deps: ARRAY_ENTRIES_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayShift => RuntimeSpec {
                symbol: "$array_shift",
                deps: ARRAY_SHIFT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayUnshift => RuntimeSpec {
                symbol: "$array_unshift",
                deps: ARRAY_UNSHIFT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArraySplice => RuntimeSpec {
                symbol: "$array_splice",
                deps: ARRAY_SPLICE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayIsArray => RuntimeSpec {
                symbol: "$array_is_array",
                deps: &[],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MakeBigIntLiteral => RuntimeSpec {
                symbol: "$make_bigint_literal",
                deps: MAKE_BIGINT_LITERAL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntToString => RuntimeSpec {
                symbol: "$bigint_to_string",
                deps: BIGINT_TO_STRING_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntToBoolean => RuntimeSpec {
                symbol: "$bigint_to_boolean",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntFromValue => RuntimeSpec {
                symbol: "$bigint_from_value",
                deps: BIGINT_FROM_VALUE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntAsIntN => RuntimeSpec {
                symbol: "$bigint_as_int_n",
                deps: BIGINT_AS_INT_N_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntAsUintN => RuntimeSpec {
                symbol: "$bigint_as_uint_n",
                deps: BIGINT_AS_UINT_N_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntUnaryMinus => RuntimeSpec {
                symbol: "$bigint_unary_minus",
                deps: BIGINT_UNARY_MINUS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntAdd => RuntimeSpec {
                symbol: "$bigint_add",
                deps: BIGINT_ADD_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntSub => RuntimeSpec {
                symbol: "$bigint_sub",
                deps: BIGINT_SUB_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntMul => RuntimeSpec {
                symbol: "$bigint_mul",
                deps: BIGINT_MUL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntPow => RuntimeSpec {
                symbol: "$bigint_pow",
                deps: BIGINT_POW_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntDiv => RuntimeSpec {
                symbol: "$bigint_div",
                deps: BIGINT_DIV_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: BIGINT_DIVISION_BY_ZERO_RANGE_ERROR_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntRem => RuntimeSpec {
                symbol: "$bigint_rem",
                deps: BIGINT_REM_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntDivisionByZeroRangeError => RuntimeSpec {
                symbol: "$bigint_division_by_zero_range_error",
                deps: BIGINT_DIVISION_BY_ZERO_RANGE_ERROR_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: BIGINT_DIVISION_BY_ZERO_RANGE_ERROR_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntMixedArithmeticTypeError => RuntimeSpec {
                symbol: "$bigint_mixed_arithmetic_type_error",
                deps: BIGINT_MIXED_ARITHMETIC_TYPE_ERROR_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: BIGINT_MIXED_ARITHMETIC_TYPE_ERROR_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntStringComparisonBoundaryError => RuntimeSpec {
                symbol: "$bigint_string_comparison_boundary_error",
                deps: BIGINT_STRING_COMPARISON_BOUNDARY_ERROR_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: BIGINT_STRING_COMPARISON_BOUNDARY_ERROR_RUNTIME_STRINGS,
                result: RuntimeResult::EffectOnly,
            },
            Self::BigIntBitwiseNot => RuntimeSpec {
                symbol: "$bigint_bitwise_not",
                deps: BIGINT_BITWISE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntBitwiseAnd => RuntimeSpec {
                symbol: "$bigint_bitwise_and",
                deps: BIGINT_BITWISE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntBitwiseOr => RuntimeSpec {
                symbol: "$bigint_bitwise_or",
                deps: BIGINT_BITWISE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntBitwiseXor => RuntimeSpec {
                symbol: "$bigint_bitwise_xor",
                deps: BIGINT_BITWISE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntLeftShift => RuntimeSpec {
                symbol: "$bigint_left_shift",
                deps: BIGINT_LEFT_SHIFT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntRightShift => RuntimeSpec {
                symbol: "$bigint_right_shift",
                deps: BIGINT_RIGHT_SHIFT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntCompare => RuntimeSpec {
                symbol: "$bigint_compare",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ReadStdinBytes => RuntimeSpec {
                symbol: "$read_stdin_bytes",
                deps: READ_STDIN_DEPS,
                imports: IMPORT_FD_READ,
                capability: CAP_STDIN_READ,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Write => RuntimeSpec {
                symbol: "$write",
                deps: WRITE_DEPS,
                imports: IMPORT_FD_WRITE,
                capability: CAP_STDOUT_WRITE,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::EffectOnly,
            },
            Self::Copy => RuntimeSpec {
                symbol: "$copy",
                deps: COPY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::EffectOnly,
            },
            Self::ValueToStringInto => RuntimeSpec {
                symbol: "$value_to_string_into",
                deps: VTS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: VTS_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ErrorMessage => RuntimeSpec {
                symbol: "$error_message",
                deps: ERROR_MESSAGE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: VTS_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Log => RuntimeSpec {
                symbol: "$log",
                deps: LOG_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: LOG_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PrivateBrandTypeError => RuntimeSpec {
                symbol: "$private_brand_type_error",
                deps: PRIVATE_BRAND_TYPE_ERROR_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: PRIVATE_BRAND_TYPE_ERROR_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::AllocHeap => RuntimeSpec {
                symbol: "$alloc_heap",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MemEqual => RuntimeSpec {
                symbol: "$mem_equal",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Index => RuntimeSpec {
                symbol: "$index",
                deps: INDEX_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::GetLength => RuntimeSpec {
                symbol: "$get_length",
                deps: &[Self::PropertyGet],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateNew => RuntimeSpec {
                symbol: "$date_new",
                deps: DATE_NEW_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateNewLive => RuntimeSpec {
                symbol: "$date_new_live",
                deps: DATE_NEW_LIVE_DEPS,
                imports: IMPORT_CLOCK_TIME_GET,
                capability: CAP_WASI_CLOCK_REALTIME,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateNow => RuntimeSpec {
                symbol: "$date_now",
                deps: DATE_NOW_DEPS,
                imports: IMPORT_CLOCK_TIME_GET,
                capability: CAP_WASI_CLOCK_REALTIME,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateEpochMsNowNumber => RuntimeSpec {
                symbol: "$date_epoch_ms_now_number",
                deps: DATE_EPOCH_MS_NOW_NUMBER_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateGetTime => RuntimeSpec {
                symbol: "$date_get_time",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateToString => RuntimeSpec {
                symbol: "$date_to_string",
                deps: NO_DEPS,
                imports: IMPORT_DATE_TO_STRING,
                capability: CAP_HOST_DATE_TO_STRING,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateGetLocalTimeField => RuntimeSpec {
                symbol: "$date_get_local_time_field",
                deps: NO_DEPS,
                imports: IMPORT_DATE_GET_LOCAL_TIME_FIELD,
                capability: CAP_HOST_DATE_GET_LOCAL_TIME_FIELD,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateToISOString => RuntimeSpec {
                symbol: "$date_to_iso_string",
                deps: NO_DEPS,
                imports: IMPORT_DATE_TO_ISO_STRING,
                capability: CAP_HOST_DATE_TO_ISO_STRING,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateGetTimezoneOffset => RuntimeSpec {
                symbol: "$date_get_timezone_offset",
                deps: NO_DEPS,
                imports: IMPORT_DATE_GET_TIMEZONE_OFFSET,
                capability: CAP_HOST_DATE_GET_TIMEZONE_OFFSET,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateGetUtcMilliseconds => RuntimeSpec {
                symbol: "$date_get_utc_milliseconds",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateGetUtcSeconds => RuntimeSpec {
                symbol: "$date_get_utc_seconds",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateGetUtcMinutes => RuntimeSpec {
                symbol: "$date_get_utc_minutes",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateGetUtcHours => RuntimeSpec {
                symbol: "$date_get_utc_hours",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateGetUtcDay => RuntimeSpec {
                symbol: "$date_get_utc_day",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateGetUtcDate => RuntimeSpec {
                symbol: "$date_get_utc_date",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateGetUtcMonth => RuntimeSpec {
                symbol: "$date_get_utc_month",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateGetUtcFullYear => RuntimeSpec {
                symbol: "$date_get_utc_full_year",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::EncodeURI => RuntimeSpec {
                symbol: "$encode_uri",
                deps: NO_DEPS,
                imports: IMPORT_ENCODE_URI,
                capability: CAP_HOST_ENCODE_URI,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DecodeURI => RuntimeSpec {
                symbol: "$decode_uri",
                deps: NO_DEPS,
                imports: IMPORT_DECODE_URI,
                capability: CAP_HOST_DECODE_URI,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Escape => RuntimeSpec {
                symbol: "$escape",
                deps: NO_DEPS,
                imports: IMPORT_ESCAPE,
                capability: CAP_HOST_ESCAPE,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Unescape => RuntimeSpec {
                symbol: "$unescape",
                deps: NO_DEPS,
                imports: IMPORT_UNESCAPE,
                capability: CAP_HOST_UNESCAPE,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::FsReadFileSync => RuntimeSpec {
                symbol: "$fs_read_file_sync",
                deps: FS_READ_WASI_DEPS,
                imports: IMPORT_FS_READ_WASI,
                capability: CAP_WASI_FILESYSTEM_READ,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::FsWriteFileSync => RuntimeSpec {
                symbol: "$fs_write_file_sync",
                deps: NO_DEPS,
                imports: IMPORT_FS_WRITE_WASI,
                capability: CAP_WASI_FILESYSTEM_WRITE,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::FsAppendFileSync => RuntimeSpec {
                symbol: "$fs_append_file_sync",
                deps: NO_DEPS,
                imports: IMPORT_FS_APPEND_FILE_SYNC,
                capability: CAP_HOST_FS_APPEND_FILE_SYNC,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ProcessArgv => RuntimeSpec {
                symbol: "$process_argv",
                deps: &[Self::AllocHeap, Self::Copy],
                imports: &[HostImport::ArgsSizesGet, HostImport::ArgsGet],
                capability: CAP_WASI_ARGS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ProcessEnv => RuntimeSpec {
                symbol: "$process_env",
                deps: &[
                    Self::AllocHeap,
                    Self::Copy,
                    Self::ObjectCreate,
                    Self::PropertySet,
                ],
                imports: &[HostImport::EnvironSizesGet, HostImport::EnvironGet],
                capability: CAP_WASI_ENV,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ProcessExit => RuntimeSpec {
                symbol: "$process_exit",
                deps: NO_DEPS,
                imports: IMPORT_PROCESS_EXIT,
                capability: CAP_HOST_PROCESS_EXIT,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::EffectOnly,
            },
            Self::PathJoin => RuntimeSpec {
                symbol: "$path_join",
                deps: NO_DEPS,
                imports: IMPORT_PATH_JOIN,
                capability: CAP_HOST_PATH_JOIN,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PathResolve => RuntimeSpec {
                symbol: "$path_resolve",
                deps: NO_DEPS,
                imports: IMPORT_PATH_RESOLVE,
                capability: CAP_HOST_PATH_RESOLVE,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PathBasename => RuntimeSpec {
                symbol: "$path_basename",
                deps: NO_DEPS,
                imports: IMPORT_PATH_BASENAME,
                capability: CAP_HOST_PATH_BASENAME,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PathDirname => RuntimeSpec {
                symbol: "$path_dirname",
                deps: NO_DEPS,
                imports: IMPORT_PATH_DIRNAME,
                capability: CAP_HOST_PATH_DIRNAME,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::CryptoRandomBytes => RuntimeSpec {
                symbol: "$crypto_random_bytes",
                deps: NO_DEPS,
                imports: IMPORT_CRYPTO_RANDOM_BYTES,
                capability: CAP_HOST_CRYPTO_RANDOM_BYTES,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Dollar262Global => RuntimeSpec {
                symbol: "$dollar_262_global",
                deps: &[Self::ObjectCreate],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Dollar262Eval => RuntimeSpec {
                symbol: "$dollar_262_eval",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::GetIterator => RuntimeSpec {
                symbol: "$get_iterator",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::EffectOnly,
            },
            Self::IteratorNext => RuntimeSpec {
                symbol: "$iterator_next",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::EffectOnly,
            },
            Self::JsonStringify => RuntimeSpec {
                symbol: "$json_stringify",
                deps: JSON_STRINGIFY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: JSON_STRINGIFY_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::JsonParse => RuntimeSpec {
                symbol: "$json_parse",
                deps: JSON_PARSE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: JSON_PARSE_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MapNew => RuntimeSpec {
                symbol: "$map_new",
                deps: MAP_NEW_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MapGet => RuntimeSpec {
                symbol: "$map_get",
                deps: MAP_GET_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MapSet => RuntimeSpec {
                symbol: "$map_set",
                deps: MAP_SET_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MapHas => RuntimeSpec {
                symbol: "$map_has",
                deps: MAP_HAS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MapDelete => RuntimeSpec {
                symbol: "$map_delete",
                deps: MAP_DELETE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MapValuesArray => RuntimeSpec {
                symbol: "$map_values_array",
                deps: MAP_VALUES_ARRAY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetNew => RuntimeSpec {
                symbol: "$set_new",
                deps: SET_NEW_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetAdd => RuntimeSpec {
                symbol: "$set_add",
                deps: SET_ADD_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetHas => RuntimeSpec {
                symbol: "$set_has",
                deps: SET_HAS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetDelete => RuntimeSpec {
                symbol: "$set_delete",
                deps: SET_DELETE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetSize => RuntimeSpec {
                symbol: "$set_size",
                deps: SET_SIZE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetClear => RuntimeSpec {
                symbol: "$set_clear",
                deps: SET_CLEAR_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetForEach => RuntimeSpec {
                symbol: "$set_for_each",
                deps: SET_FOR_EACH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MapClear => RuntimeSpec {
                symbol: "$map_clear",
                deps: MAP_CLEAR_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MapSize => RuntimeSpec {
                symbol: "$map_size",
                deps: MAP_SIZE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MapForEach => RuntimeSpec {
                symbol: "$map_for_each",
                deps: MAP_FOR_EACH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MapEntriesArray => RuntimeSpec {
                symbol: "$map_entries_array",
                deps: MAP_ENTRIES_ARRAY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MapEntryPairsArray => RuntimeSpec {
                symbol: "$map_entry_pairs_array",
                deps: MAP_ENTRY_PAIRS_ARRAY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetFromArray => RuntimeSpec {
                symbol: "$set_from_array",
                deps: SET_FROM_ARRAY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetValuesArray => RuntimeSpec {
                symbol: "$set_values_array",
                deps: SET_VALUES_ARRAY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetPrototypeAddGet => RuntimeSpec {
                symbol: "$set_prototype_add_get",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetPrototypeAddSet => RuntimeSpec {
                symbol: "$set_prototype_add_set",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::WeakMapNew => RuntimeSpec {
                symbol: "$weak_map_new",
                deps: &[RuntimeFn::AllocHeap],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::WeakMapSet => RuntimeSpec {
                symbol: "$weak_map_set",
                deps: &[RuntimeFn::StrictEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::WeakMapGet => RuntimeSpec {
                symbol: "$weak_map_get",
                deps: &[RuntimeFn::StrictEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::WeakMapHas => RuntimeSpec {
                symbol: "$weak_map_has",
                deps: &[RuntimeFn::StrictEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::WeakMapDelete => RuntimeSpec {
                symbol: "$weak_map_delete",
                deps: &[RuntimeFn::StrictEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::WeakSetNew => RuntimeSpec {
                symbol: "$weak_set_new",
                deps: &[RuntimeFn::AllocHeap],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::WeakSetAdd => RuntimeSpec {
                symbol: "$weak_set_add",
                deps: &[RuntimeFn::StrictEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::WeakSetHas => RuntimeSpec {
                symbol: "$weak_set_has",
                deps: &[RuntimeFn::StrictEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::WeakSetDelete => RuntimeSpec {
                symbol: "$weak_set_delete",
                deps: &[RuntimeFn::StrictEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MathFloor => RuntimeSpec {
                symbol: "$math_floor",
                deps: MATH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MathCeil => RuntimeSpec {
                symbol: "$math_ceil",
                deps: MATH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MathRound => RuntimeSpec {
                symbol: "$math_round",
                deps: MATH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MathAbs => RuntimeSpec {
                symbol: "$math_abs",
                deps: MATH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MathMax => RuntimeSpec {
                symbol: "$math_max",
                deps: MATH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MathMin => RuntimeSpec {
                symbol: "$math_min",
                deps: MATH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MathPow => RuntimeSpec {
                symbol: "$math_pow",
                deps: MATH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MathRandom => RuntimeSpec {
                symbol: "$math_random",
                deps: MATH_RANDOM_DEPS,
                imports: IMPORT_RANDOM_GET,
                capability: CAP_WASI_RANDOM,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MathTrunc => RuntimeSpec {
                symbol: "$math_trunc",
                deps: MATH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MathSign => RuntimeSpec {
                symbol: "$math_sign",
                deps: MATH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MathCbrt => RuntimeSpec {
                symbol: "$math_cbrt",
                deps: MATH_NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MathClz32 => RuntimeSpec {
                symbol: "$math_clz32",
                deps: MATH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MathImul => RuntimeSpec {
                symbol: "$math_imul",
                deps: MATH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MathSqrt => RuntimeSpec {
                symbol: "$math_sqrt",
                deps: MATH_NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ModuleRequire => RuntimeSpec {
                symbol: "$module_require",
                deps: &[Self::AllocHeap],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ModuleExportsSet => RuntimeSpec {
                symbol: "$module_exports_set",
                deps: &[Self::AllocHeap, Self::PropertySet],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::EffectOnly,
            },
            Self::ModuleExportsAssign => RuntimeSpec {
                symbol: "$module_exports_assign",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::EffectOnly,
            },
            Self::NumberFromI32 => RuntimeSpec {
                symbol: "$number_from_i32",
                deps: NUMBER_FROM_I32_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::NumberToExponential => RuntimeSpec {
                symbol: "$value_to_string_into",
                deps: VTS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: VTS_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::NumberToFixed => RuntimeSpec {
                symbol: "$value_to_string_into",
                deps: VTS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: VTS_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::NumberToPrecision => RuntimeSpec {
                symbol: "$value_to_string_into",
                deps: VTS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: VTS_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::NumberToI32 => RuntimeSpec {
                symbol: "$number_to_i32",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::NumberIsNaN => RuntimeSpec {
                symbol: "$number_is_nan",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::NumberIsFinite => RuntimeSpec {
                symbol: "$number_is_finite",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::NumberIsInteger => RuntimeSpec {
                symbol: "$number_is_integer",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::NumberIsSafeInteger => RuntimeSpec {
                symbol: "$number_is_safe_integer",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PropertyGet => RuntimeSpec {
                symbol: "$property_get",
                deps: &[Self::MemEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PropertySet => RuntimeSpec {
                symbol: "$property_set",
                deps: &[Self::AllocHeap, Self::Copy, Self::MemEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PropertyDelete => RuntimeSpec {
                symbol: "$property_delete",
                deps: &[Self::MemEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PropertyHas => RuntimeSpec {
                symbol: "$property_has",
                deps: &[Self::MemEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectKeys => RuntimeSpec {
                symbol: "$object_keys",
                deps: OBJECT_KEYS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectSpread => RuntimeSpec {
                symbol: "$object_spread",
                deps: OBJECT_SPREAD_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SpreadViaIterator => RuntimeSpec {
                symbol: "$spread_via_iterator",
                deps: &[],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectValues => RuntimeSpec {
                symbol: "$object_values",
                deps: OBJECT_VALUES_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectEntries => RuntimeSpec {
                symbol: "$object_entries",
                deps: OBJECT_ENTRIES_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectHasOwnProperty => RuntimeSpec {
                symbol: "$object_has_own_property",
                deps: OBJECT_HAS_OWN_PROPERTY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectHasOwn => RuntimeSpec {
                symbol: "$object_has_own",
                deps: OBJECT_HAS_OWN_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectGetOwnPropertyDescriptor => RuntimeSpec {
                symbol: "$object_get_own_property_descriptor",
                deps: OBJECT_GET_OWN_PROPERTY_DESCRIPTOR_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectGetPrototypeOf => RuntimeSpec {
                symbol: "$object_get_prototype_of",
                deps: OBJECT_PROTOTYPE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectSetPrototypeOf => RuntimeSpec {
                symbol: "$object_set_prototype_of",
                deps: OBJECT_PROTOTYPE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectFreeze => RuntimeSpec {
                symbol: "$object_freeze",
                deps: OBJECT_FREEZE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectSeal => RuntimeSpec {
                symbol: "$object_seal",
                deps: OBJECT_SEAL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectPreventExtensions => RuntimeSpec {
                symbol: "$object_prevent_extensions",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectIsExtensible => RuntimeSpec {
                symbol: "$object_is_extensible",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectIsSealed => RuntimeSpec {
                symbol: "$object_is_sealed",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectIsFrozen => RuntimeSpec {
                symbol: "$object_is_frozen",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectDefineProperty => RuntimeSpec {
                symbol: "$object_define_property",
                deps: OBJECT_DEFINE_PROPERTY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectAssign => RuntimeSpec {
                symbol: "$object_assign",
                deps: OBJECT_ASSIGN_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectCreate => RuntimeSpec {
                symbol: "$object_create",
                deps: OBJECT_CREATE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectIs => RuntimeSpec {
                symbol: "$object_is",
                deps: &[
                    Self::IsString,
                    Self::StringEqual,
                    Self::BigIntCompare,
                    Self::NumberToI32,
                ],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Add => RuntimeSpec {
                symbol: "$add",
                deps: ADD_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::AddFast => RuntimeSpec {
                symbol: "$add_fast",
                deps: ADD_FAST_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Sub => RuntimeSpec {
                symbol: "$sub",
                deps: NUMBER_ARITH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SubFast => RuntimeSpec {
                symbol: "$sub_fast",
                deps: SUB_FAST_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Mul => RuntimeSpec {
                symbol: "$mul",
                deps: NUMBER_ARITH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MulFast => RuntimeSpec {
                symbol: "$mul_fast",
                deps: MUL_FAST_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Div => RuntimeSpec {
                symbol: "$div",
                deps: NUMBER_ARITH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DivFast => RuntimeSpec {
                symbol: "$div_fast",
                deps: DIV_FAST_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Mod => RuntimeSpec {
                symbol: "$mod",
                deps: NUMBER_ARITH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ModFast => RuntimeSpec {
                symbol: "$mod_fast",
                deps: MOD_FAST_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BitwiseToI32 => RuntimeSpec {
                symbol: "$bitwise_to_i32",
                deps: &[Self::NumberToI32],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BitwiseAnd => RuntimeSpec {
                symbol: "$bitwise_and",
                deps: BITWISE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BitwiseXor => RuntimeSpec {
                symbol: "$bitwise_xor",
                deps: BITWISE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BitwiseOr => RuntimeSpec {
                symbol: "$bitwise_or",
                deps: BITWISE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Negate => RuntimeSpec {
                symbol: "$negate",
                deps: NUMBER_ARITH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Less => RuntimeSpec {
                symbol: "$less",
                deps: LESS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::LessFast => RuntimeSpec {
                symbol: "$less_fast",
                deps: LESS_FAST_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::LessEqual => RuntimeSpec {
                symbol: "$less_equal",
                deps: LESS_EQUAL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::LessEqualFast => RuntimeSpec {
                symbol: "$less_equal_fast",
                deps: LESS_EQUAL_FAST_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Greater => RuntimeSpec {
                symbol: "$greater",
                deps: GREATER_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::GreaterFast => RuntimeSpec {
                symbol: "$greater_fast",
                deps: GREATER_FAST_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::GreaterEqual => RuntimeSpec {
                symbol: "$greater_equal",
                deps: GREATER_EQUAL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::GreaterEqualFast => RuntimeSpec {
                symbol: "$greater_equal_fast",
                deps: GREATER_EQUAL_FAST_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StrictEqual => RuntimeSpec {
                symbol: "$strict_equal",
                deps: STRICT_EQUAL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::EqualEqual => RuntimeSpec {
                symbol: "$equal_equal",
                deps: EQUAL_EQUAL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BangEqual => RuntimeSpec {
                symbol: "$bang_equal",
                deps: BANG_EQUAL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StrictNotEqual => RuntimeSpec {
                symbol: "$strict_not_equal",
                deps: STRICT_NOT_EQUAL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::And => RuntimeSpec {
                symbol: "$and",
                deps: AND_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Or => RuntimeSpec {
                symbol: "$or",
                deps: OR_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PromiseConstructor => RuntimeSpec {
                symbol: "$promise_constructor",
                deps: &[Self::AllocHeap],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PromiseResolve => RuntimeSpec {
                symbol: "$promise_resolve",
                deps: &[Self::AllocHeap],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PromiseReject => RuntimeSpec {
                symbol: "$promise_reject",
                deps: &[Self::AllocHeap],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PromiseThen => RuntimeSpec {
                symbol: "$promise_then",
                deps: &[Self::AllocHeap, Self::StrictEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PromiseCatch => RuntimeSpec {
                symbol: "$promise_catch",
                deps: &[Self::StrictEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PromiseAll => RuntimeSpec {
                symbol: "$promise_all",
                deps: &[Self::AllocHeap],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PromiseRace => RuntimeSpec {
                symbol: "$promise_race",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::RegExpTest => RuntimeSpec {
                symbol: "$regexp_test",
                deps: REGEXP_TEST_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::RegExpMatch => RuntimeSpec {
                symbol: "$regexp_match",
                deps: REGEXP_MATCH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::RegExpSearch => RuntimeSpec {
                symbol: "$regexp_search",
                deps: REGEXP_SEARCH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::RegexpMatchInner => RuntimeSpec {
                symbol: "$regexp_match_inner",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringEqual => RuntimeSpec {
                symbol: "$string_equal",
                deps: STRING_EQUAL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Concat => RuntimeSpec {
                symbol: "$concat",
                deps: CONCAT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringCharAt => RuntimeSpec {
                symbol: "$string_char_at",
                deps: STRING_CHAR_AT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringAt => RuntimeSpec {
                symbol: "$string_at",
                deps: STRING_AT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringSubstring => RuntimeSpec {
                symbol: "$string_substring",
                deps: STRING_SUBSTRING_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringSubstr => RuntimeSpec {
                symbol: "$string_substr",
                deps: STRING_SUBSTR_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringSlice => RuntimeSpec {
                symbol: "$string_slice",
                deps: STRING_SLICE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringIndexOf => RuntimeSpec {
                symbol: "$string_index_of",
                deps: STRING_INDEX_OF_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringLastIndexOf => RuntimeSpec {
                symbol: "$string_last_index_of",
                deps: STRING_LAST_INDEX_OF_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringLocaleCompare => RuntimeSpec {
                symbol: "$string_locale_compare",
                deps: STRING_LOCALE_COMPARE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringIncludes => RuntimeSpec {
                symbol: "$string_includes",
                deps: STRING_INCLUDES_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringPadStart => RuntimeSpec {
                symbol: "$string_pad_start",
                deps: STRING_PAD_START_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringPadEnd => RuntimeSpec {
                symbol: "$string_pad_end",
                deps: STRING_PAD_END_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringRepeat => RuntimeSpec {
                symbol: "$string_repeat",
                deps: STRING_REPEAT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringSplit => RuntimeSpec {
                symbol: "$string_split",
                deps: STRING_SPLIT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringTrim => RuntimeSpec {
                symbol: "$string_trim",
                deps: STRING_TRIM_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringTrimStart => RuntimeSpec {
                symbol: "$string_trim_start",
                deps: STRING_TRIM_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringTrimEnd => RuntimeSpec {
                symbol: "$string_trim_end",
                deps: STRING_TRIM_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringStartsWith => RuntimeSpec {
                symbol: "$string_starts_with",
                deps: STRING_STARTS_WITH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringEndsWith => RuntimeSpec {
                symbol: "$string_ends_with",
                deps: STRING_ENDS_WITH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringMatch => RuntimeSpec {
                symbol: "$string_match",
                deps: STRING_MATCH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringSearch => RuntimeSpec {
                symbol: "$string_search",
                deps: STRING_SEARCH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringToUpperCase => RuntimeSpec {
                symbol: "$string_to_upper_case",
                deps: STRING_TO_UPPER_CASE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringToLowerCase => RuntimeSpec {
                symbol: "$string_to_lower_case",
                deps: STRING_TO_LOWER_CASE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringCharCodeAt => RuntimeSpec {
                symbol: "$string_char_code_at",
                deps: STRING_CHAR_CODE_AT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringCodePointAt => RuntimeSpec {
                symbol: "$string_code_point_at",
                deps: STRING_CODE_POINT_AT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringIsWellFormed => RuntimeSpec {
                symbol: "$string_is_well_formed",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringToWellFormed => RuntimeSpec {
                symbol: "$string_to_well_formed",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringFromCharCode => RuntimeSpec {
                symbol: "$string_from_char_code",
                deps: STRING_FROM_CHAR_CODE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringFromCodePoint => RuntimeSpec {
                symbol: "$string_from_code_point",
                deps: STRING_FROM_CODE_POINT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringReplace => RuntimeSpec {
                symbol: "$string_replace",
                deps: STRING_REPLACE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringReplaceAll => RuntimeSpec {
                symbol: "$string_replace_all",
                deps: STRING_REPLACE_ALL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SymbolNew => RuntimeSpec {
                symbol: "$symbol_new",
                deps: SYMBOL_NEW_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: SYMBOL_NEW_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SymbolFor => RuntimeSpec {
                symbol: "$symbol_for",
                deps: SYMBOL_FOR_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: SYMBOL_FOR_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SymbolKeyFor => RuntimeSpec {
                symbol: "$symbol_key_for",
                deps: SYMBOL_KEY_FOR_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SymbolToPrimitive => RuntimeSpec {
                symbol: "$symbol_to_primitive",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SymbolToStringTag => RuntimeSpec {
                symbol: "$symbol_to_string_tag",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SymbolHasInstance => RuntimeSpec {
                symbol: "$symbol_has_instance",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::TaskPoll => RuntimeSpec {
                symbol: "$task_poll",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::TaskResult => RuntimeSpec {
                symbol: "$task_result",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::TaskDrop => RuntimeSpec {
                symbol: "$task_drop",
                deps: &[Self::AllocHeap],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::EffectOnly,
            },
            Self::TruthyBool => RuntimeSpec {
                symbol: "$truthy_bool",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Not => RuntimeSpec {
                symbol: "$not",
                deps: &[Self::TruthyBool],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::TypeOf => RuntimeSpec {
                symbol: "$typeof",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: TYPEOF_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::IsString => RuntimeSpec {
                symbol: "$is_string",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ValueOf => RuntimeSpec {
                symbol: "$value_of",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::InstanceOf => RuntimeSpec {
                symbol: "$instanceof",
                deps: &[],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::IsNaN => RuntimeSpec {
                symbol: "$is_nan",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ParseInt => RuntimeSpec {
                symbol: "$parse_int",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ParseFloat => RuntimeSpec {
                symbol: "$parse_float",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::IsFinite => RuntimeSpec {
                symbol: "$is_finite",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BooleanCoerce => RuntimeSpec {
                symbol: "$boolean_coerce",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::NumberCoerce => RuntimeSpec {
                symbol: "$number_coerce",
                deps: &[RuntimeFn::ParseInt],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::TypedArrayFromArray => RuntimeSpec {
                symbol: "$typed_array_from_array",
                deps: TYPED_ARRAY_FROM_ARRAY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::TypedArraySet => RuntimeSpec {
                symbol: "$typed_array_set",
                deps: TYPED_ARRAY_SET_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DataViewNew => RuntimeSpec {
                symbol: "$dataview_new",
                deps: DATAVIEW_NEW_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DataViewGetInt32 => RuntimeSpec {
                symbol: "$dataview_get_int32",
                deps: &[],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DataViewSetInt32 => RuntimeSpec {
                symbol: "$dataview_set_int32",
                deps: &[],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::EffectOnly,
            },
            Self::DataViewGetFloat64 => RuntimeSpec {
                symbol: "$dataview_get_float64",
                deps: &[],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DataViewSetFloat64 => RuntimeSpec {
                symbol: "$dataview_set_float64",
                deps: &[],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::EffectOnly,
            },
        }
