// Domain: Array -- auto-generated.
// Regenerate with: python3 scripts/refactor/extract-runtime-domains.py

            Self::ArrayGet => RuntimeSpec {
                symbol: "$array_get",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayIndexPresent => RuntimeSpec {
                symbol: "$array_index_present",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayBufferNew => RuntimeSpec {
                symbol: "$arraybuffer_new",
                deps: ARRAYBUFFER_NEW_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayPush => RuntimeSpec {
                symbol: "$array_push",
                deps: ARRAY_PUSH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayPushGrow => RuntimeSpec {
                symbol: "$array_push_grow",
                deps: ARRAY_PUSH_GROW_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayPop => RuntimeSpec {
                symbol: "$array_pop",
                deps: ARRAY_POP_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArraySlice => RuntimeSpec {
                symbol: "$array_slice",
                deps: ARRAY_SLICE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayConcat => RuntimeSpec {
                symbol: "$array_concat",
                deps: ARRAY_CONCAT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayMapValueToString => RuntimeSpec {
                symbol: "$array_map_value_to_string",
                deps: ARRAY_MAP_VALUE_TO_STRING_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayMapUnaryPlus => RuntimeSpec {
                symbol: "$array_map_unary_plus",
                deps: ARRAY_MAP_UNARY_PLUS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayMapStringSplit => RuntimeSpec {
                symbol: "$array_map_string_split",
                deps: ARRAY_MAP_STRING_SPLIT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayMapArrayLikeIdentity => RuntimeSpec {
                symbol: "$array_map_array_like_identity",
                deps: ARRAY_MAP_ARRAY_LIKE_IDENTITY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayMapArrayLikeDouble => RuntimeSpec {
                symbol: "$array_map_array_like_double",
                deps: ARRAY_MAP_ARRAY_LIKE_DOUBLE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArraySortNumeric => RuntimeSpec {
                symbol: "$array_sort_numeric",
                deps: ARRAY_SORT_NUMERIC_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayJoin => RuntimeSpec {
                symbol: "$array_join",
                deps: ARRAY_JOIN_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayReverse => RuntimeSpec {
                symbol: "$array_reverse",
                deps: ARRAY_REVERSE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayIndexOf => RuntimeSpec {
                symbol: "$array_index_of",
                deps: ARRAY_INDEX_OF_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayIncludes => RuntimeSpec {
                symbol: "$array_includes",
                deps: ARRAY_INCLUDES_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayFind => RuntimeSpec {
                symbol: "$array_find",
                deps: ARRAY_FIND_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayFindIndex => RuntimeSpec {
                symbol: "$array_find_index",
                deps: ARRAY_FIND_INDEX_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayFindLast => RuntimeSpec {
                symbol: "$array_find_last",
                deps: ARRAY_FIND_LAST_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayFindLastIndex => RuntimeSpec {
                symbol: "$array_find_last_index",
                deps: ARRAY_FIND_LAST_INDEX_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayFilter => RuntimeSpec {
                symbol: "$array_filter",
                deps: ARRAY_FILTER_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayEvery => RuntimeSpec {
                symbol: "$array_every",
                deps: ARRAY_EVERY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArraySome => RuntimeSpec {
                symbol: "$array_some",
                deps: ARRAY_SOME_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayReduce => RuntimeSpec {
                symbol: "$array_reduce",
                deps: ARRAY_REDUCE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayReduceRight => RuntimeSpec {
                symbol: "$array_reduce_right",
                deps: ARRAY_REDUCE_RIGHT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayLastIndexOf => RuntimeSpec {
                symbol: "$array_last_index_of",
                deps: ARRAY_LAST_INDEX_OF_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayForEach => RuntimeSpec {
                symbol: "$array_for_each",
                deps: ARRAY_FOR_EACH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayMap => RuntimeSpec {
                symbol: "$array_map",
                deps: ARRAY_MAP_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayAt => RuntimeSpec {
                symbol: "$array_at",
                deps: ARRAY_AT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayFill => RuntimeSpec {
                symbol: "$array_fill",
                deps: ARRAY_FILL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayFlat => RuntimeSpec {
                symbol: "$array_flat",
                deps: ARRAY_FLAT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayPushOrSpread => RuntimeSpec {
                symbol: "$array_push_or_spread",
                deps: ARRAY_PUSH_OR_SPREAD_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayCopyWithin => RuntimeSpec {
                symbol: "$array_copy_within",
                deps: ARRAY_COPY_WITHIN_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayWith => RuntimeSpec {
                symbol: "$array_with",
                deps: ARRAY_WITH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayToReversed => RuntimeSpec {
                symbol: "$array_to_reversed",
                deps: ARRAY_TO_REVERSED_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayToSorted => RuntimeSpec {
                symbol: "$array_to_sorted",
                deps: ARRAY_TO_SORTED_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayToSpliced => RuntimeSpec {
                symbol: "$array_to_spliced",
                deps: ARRAY_TO_SPLICED_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayValues => RuntimeSpec {
                symbol: "$array_values",
                deps: ARRAY_VALUES_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayKeys => RuntimeSpec {
                symbol: "$array_keys",
                deps: ARRAY_KEYS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayEntries => RuntimeSpec {
                symbol: "$array_entries",
                deps: ARRAY_ENTRIES_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayShift => RuntimeSpec {
                symbol: "$array_shift",
                deps: ARRAY_SHIFT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayUnshift => RuntimeSpec {
                symbol: "$array_unshift",
                deps: ARRAY_UNSHIFT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArraySplice => RuntimeSpec {
                symbol: "$array_splice",
                deps: ARRAY_SPLICE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ArrayIsArray => RuntimeSpec {
                symbol: "$array_is_array",
                deps: &[],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
