// Domain: BigInt -- auto-generated.
// Regenerate with: python3 scripts/refactor/extract-runtime-domains.py

            Self::MakeBigIntLiteral => RuntimeSpec {
                symbol: "$make_bigint_literal",
                deps: MAKE_BIGINT_LITERAL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntToString => RuntimeSpec {
                symbol: "$bigint_to_string",
                deps: BIGINT_TO_STRING_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntToBoolean => RuntimeSpec {
                symbol: "$bigint_to_boolean",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntFromValue => RuntimeSpec {
                symbol: "$bigint_from_value",
                deps: BIGINT_FROM_VALUE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntAsIntN => RuntimeSpec {
                symbol: "$bigint_as_int_n",
                deps: BIGINT_AS_INT_N_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntAsUintN => RuntimeSpec {
                symbol: "$bigint_as_uint_n",
                deps: BIGINT_AS_UINT_N_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntUnaryMinus => RuntimeSpec {
                symbol: "$bigint_unary_minus",
                deps: BIGINT_UNARY_MINUS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntAdd => RuntimeSpec {
                symbol: "$bigint_add",
                deps: BIGINT_ADD_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntSub => RuntimeSpec {
                symbol: "$bigint_sub",
                deps: BIGINT_SUB_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntMul => RuntimeSpec {
                symbol: "$bigint_mul",
                deps: BIGINT_MUL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntPow => RuntimeSpec {
                symbol: "$bigint_pow",
                deps: BIGINT_POW_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntDiv => RuntimeSpec {
                symbol: "$bigint_div",
                deps: BIGINT_DIV_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: BIGINT_DIVISION_BY_ZERO_RANGE_ERROR_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntRem => RuntimeSpec {
                symbol: "$bigint_rem",
                deps: BIGINT_REM_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntDivisionByZeroRangeError => RuntimeSpec {
                symbol: "$bigint_division_by_zero_range_error",
                deps: BIGINT_DIVISION_BY_ZERO_RANGE_ERROR_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: BIGINT_DIVISION_BY_ZERO_RANGE_ERROR_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntMixedArithmeticTypeError => RuntimeSpec {
                symbol: "$bigint_mixed_arithmetic_type_error",
                deps: BIGINT_MIXED_ARITHMETIC_TYPE_ERROR_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: BIGINT_MIXED_ARITHMETIC_TYPE_ERROR_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntStringComparisonBoundaryError => RuntimeSpec {
                symbol: "$bigint_string_comparison_boundary_error",
                deps: BIGINT_STRING_COMPARISON_BOUNDARY_ERROR_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: BIGINT_STRING_COMPARISON_BOUNDARY_ERROR_RUNTIME_STRINGS,
                result: RuntimeResult::EffectOnly,
            },
            Self::BigIntBitwiseNot => RuntimeSpec {
                symbol: "$bigint_bitwise_not",
                deps: BIGINT_BITWISE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntBitwiseAnd => RuntimeSpec {
                symbol: "$bigint_bitwise_and",
                deps: BIGINT_BITWISE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntBitwiseOr => RuntimeSpec {
                symbol: "$bigint_bitwise_or",
                deps: BIGINT_BITWISE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntBitwiseXor => RuntimeSpec {
                symbol: "$bigint_bitwise_xor",
                deps: BIGINT_BITWISE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntLeftShift => RuntimeSpec {
                symbol: "$bigint_left_shift",
                deps: BIGINT_LEFT_SHIFT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntRightShift => RuntimeSpec {
                symbol: "$bigint_right_shift",
                deps: BIGINT_RIGHT_SHIFT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::BigIntCompare => RuntimeSpec {
                symbol: "$bigint_compare",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
