// Domain: Core -- auto-generated.
// Regenerate with: python3 scripts/refactor/extract-runtime-domains.py

            Self::ReadStdinBytes => RuntimeSpec {
                symbol: "$read_stdin_bytes",
                deps: READ_STDIN_DEPS,
                imports: IMPORT_FD_READ,
                capability: CAP_STDIN_READ,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Write => RuntimeSpec {
                symbol: "$write",
                deps: WRITE_DEPS,
                imports: IMPORT_FD_WRITE,
                capability: CAP_STDOUT_WRITE,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::EffectOnly,
            },
            Self::Copy => RuntimeSpec {
                symbol: "$copy",
                deps: COPY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::EffectOnly,
            },
            Self::ValueToStringInto => RuntimeSpec {
                symbol: "$value_to_string_into",
                deps: VTS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: VTS_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ErrorMessage => RuntimeSpec {
                symbol: "$error_message",
                deps: ERROR_MESSAGE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: VTS_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Log => RuntimeSpec {
                symbol: "$log",
                deps: LOG_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: LOG_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PrivateBrandTypeError => RuntimeSpec {
                symbol: "$private_brand_type_error",
                deps: PRIVATE_BRAND_TYPE_ERROR_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: PRIVATE_BRAND_TYPE_ERROR_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::AllocHeap => RuntimeSpec {
                symbol: "$alloc_heap",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MemEqual => RuntimeSpec {
                symbol: "$mem_equal",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Index => RuntimeSpec {
                symbol: "$index",
                deps: INDEX_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::GetLength => RuntimeSpec {
                symbol: "$get_length",
                deps: &[Self::PropertyGet],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
