// Domain: Date -- auto-generated.
// Regenerate with: python3 scripts/refactor/extract-runtime-domains.py

            Self::DateNew => RuntimeSpec {
                symbol: "$date_new",
                deps: DATE_NEW_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateNewLive => RuntimeSpec {
                symbol: "$date_new_live",
                deps: DATE_NEW_LIVE_DEPS,
                imports: IMPORT_CLOCK_TIME_GET,
                capability: CAP_WASI_CLOCK_REALTIME,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateNow => RuntimeSpec {
                symbol: "$date_now",
                deps: DATE_NOW_DEPS,
                imports: IMPORT_CLOCK_TIME_GET,
                capability: CAP_WASI_CLOCK_REALTIME,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateEpochMsNowNumber => RuntimeSpec {
                symbol: "$date_epoch_ms_now_number",
                deps: DATE_EPOCH_MS_NOW_NUMBER_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateGetTime => RuntimeSpec {
                symbol: "$date_get_time",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateToString => RuntimeSpec {
                symbol: "$date_to_string",
                deps: NO_DEPS,
                imports: IMPORT_DATE_TO_STRING,
                capability: CAP_HOST_DATE_TO_STRING,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateGetLocalTimeField => RuntimeSpec {
                symbol: "$date_get_local_time_field",
                deps: NO_DEPS,
                imports: IMPORT_DATE_GET_LOCAL_TIME_FIELD,
                capability: CAP_HOST_DATE_GET_LOCAL_TIME_FIELD,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateToISOString => RuntimeSpec {
                symbol: "$date_to_iso_string",
                deps: NO_DEPS,
                imports: IMPORT_DATE_TO_ISO_STRING,
                capability: CAP_HOST_DATE_TO_ISO_STRING,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateGetTimezoneOffset => RuntimeSpec {
                symbol: "$date_get_timezone_offset",
                deps: NO_DEPS,
                imports: IMPORT_DATE_GET_TIMEZONE_OFFSET,
                capability: CAP_HOST_DATE_GET_TIMEZONE_OFFSET,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateGetUtcMilliseconds => RuntimeSpec {
                symbol: "$date_get_utc_milliseconds",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateGetUtcSeconds => RuntimeSpec {
                symbol: "$date_get_utc_seconds",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateGetUtcMinutes => RuntimeSpec {
                symbol: "$date_get_utc_minutes",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateGetUtcHours => RuntimeSpec {
                symbol: "$date_get_utc_hours",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateGetUtcDay => RuntimeSpec {
                symbol: "$date_get_utc_day",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateGetUtcDate => RuntimeSpec {
                symbol: "$date_get_utc_date",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateGetUtcMonth => RuntimeSpec {
                symbol: "$date_get_utc_month",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DateGetUtcFullYear => RuntimeSpec {
                symbol: "$date_get_utc_full_year",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
