// Domain: Host -- auto-generated.
// Regenerate with: python3 scripts/refactor/extract-runtime-domains.py

            Self::FsReadFileSync => RuntimeSpec {
                symbol: "$fs_read_file_sync",
                deps: FS_READ_WASI_DEPS,
                imports: IMPORT_FS_READ_WASI,
                capability: CAP_WASI_FILESYSTEM_READ,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::FsWriteFileSync => RuntimeSpec {
                symbol: "$fs_write_file_sync",
                deps: NO_DEPS,
                imports: IMPORT_FS_WRITE_WASI,
                capability: CAP_WASI_FILESYSTEM_WRITE,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::FsAppendFileSync => RuntimeSpec {
                symbol: "$fs_append_file_sync",
                deps: NO_DEPS,
                imports: IMPORT_FS_APPEND_FILE_SYNC,
                capability: CAP_HOST_FS_APPEND_FILE_SYNC,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ProcessArgv => RuntimeSpec {
                symbol: "$process_argv",
                deps: &[Self::AllocHeap, Self::Copy],
                imports: &[HostImport::ArgsSizesGet, HostImport::ArgsGet],
                capability: CAP_WASI_ARGS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ProcessEnv => RuntimeSpec {
                symbol: "$process_env",
                deps: &[
                    Self::AllocHeap,
                    Self::Copy,
                    Self::ObjectCreate,
                    Self::PropertySet,
                ],
                imports: &[HostImport::EnvironSizesGet, HostImport::EnvironGet],
                capability: CAP_WASI_ENV,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ProcessExit => RuntimeSpec {
                symbol: "$process_exit",
                deps: NO_DEPS,
                imports: IMPORT_PROCESS_EXIT,
                capability: CAP_HOST_PROCESS_EXIT,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::EffectOnly,
            },
            Self::PathJoin => RuntimeSpec {
                symbol: "$path_join",
                deps: NO_DEPS,
                imports: IMPORT_PATH_JOIN,
                capability: CAP_HOST_PATH_JOIN,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PathResolve => RuntimeSpec {
                symbol: "$path_resolve",
                deps: NO_DEPS,
                imports: IMPORT_PATH_RESOLVE,
                capability: CAP_HOST_PATH_RESOLVE,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PathBasename => RuntimeSpec {
                symbol: "$path_basename",
                deps: NO_DEPS,
                imports: IMPORT_PATH_BASENAME,
                capability: CAP_HOST_PATH_BASENAME,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PathDirname => RuntimeSpec {
                symbol: "$path_dirname",
                deps: NO_DEPS,
                imports: IMPORT_PATH_DIRNAME,
                capability: CAP_HOST_PATH_DIRNAME,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::CryptoRandomBytes => RuntimeSpec {
                symbol: "$crypto_random_bytes",
                deps: NO_DEPS,
                imports: IMPORT_CRYPTO_RANDOM_BYTES,
                capability: CAP_HOST_CRYPTO_RANDOM_BYTES,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
