// Domain: MapSet -- auto-generated.
// Regenerate with: python3 scripts/refactor/extract-runtime-domains.py

            Self::MapNew => RuntimeSpec {
                symbol: "$map_new",
                deps: MAP_NEW_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MapGet => RuntimeSpec {
                symbol: "$map_get",
                deps: MAP_GET_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MapSet => RuntimeSpec {
                symbol: "$map_set",
                deps: MAP_SET_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MapHas => RuntimeSpec {
                symbol: "$map_has",
                deps: MAP_HAS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MapDelete => RuntimeSpec {
                symbol: "$map_delete",
                deps: MAP_DELETE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MapValuesArray => RuntimeSpec {
                symbol: "$map_values_array",
                deps: MAP_VALUES_ARRAY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetNew => RuntimeSpec {
                symbol: "$set_new",
                deps: SET_NEW_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetAdd => RuntimeSpec {
                symbol: "$set_add",
                deps: SET_ADD_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetHas => RuntimeSpec {
                symbol: "$set_has",
                deps: SET_HAS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetDelete => RuntimeSpec {
                symbol: "$set_delete",
                deps: SET_DELETE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetSize => RuntimeSpec {
                symbol: "$set_size",
                deps: SET_SIZE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetClear => RuntimeSpec {
                symbol: "$set_clear",
                deps: SET_CLEAR_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetForEach => RuntimeSpec {
                symbol: "$set_for_each",
                deps: SET_FOR_EACH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MapClear => RuntimeSpec {
                symbol: "$map_clear",
                deps: MAP_CLEAR_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MapSize => RuntimeSpec {
                symbol: "$map_size",
                deps: MAP_SIZE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MapForEach => RuntimeSpec {
                symbol: "$map_for_each",
                deps: MAP_FOR_EACH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::MapEntriesArray => RuntimeSpec {
                symbol: "$map_entries_array",
                deps: MAP_ENTRIES_ARRAY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetFromArray => RuntimeSpec {
                symbol: "$set_from_array",
                deps: SET_FROM_ARRAY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetValuesArray => RuntimeSpec {
                symbol: "$set_values_array",
                deps: SET_VALUES_ARRAY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetPrototypeAddGet => RuntimeSpec {
                symbol: "$set_prototype_add_get",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SetPrototypeAddSet => RuntimeSpec {
                symbol: "$set_prototype_add_set",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::WeakMapNew => RuntimeSpec {
                symbol: "$weak_map_new",
                deps: &[RuntimeFn::AllocHeap],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::WeakMapSet => RuntimeSpec {
                symbol: "$weak_map_set",
                deps: &[RuntimeFn::StrictEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::WeakMapGet => RuntimeSpec {
                symbol: "$weak_map_get",
                deps: &[RuntimeFn::StrictEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::WeakMapHas => RuntimeSpec {
                symbol: "$weak_map_has",
                deps: &[RuntimeFn::StrictEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::WeakMapDelete => RuntimeSpec {
                symbol: "$weak_map_delete",
                deps: &[RuntimeFn::StrictEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::WeakSetNew => RuntimeSpec {
                symbol: "$weak_set_new",
                deps: &[RuntimeFn::AllocHeap],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::WeakSetAdd => RuntimeSpec {
                symbol: "$weak_set_add",
                deps: &[RuntimeFn::StrictEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::WeakSetHas => RuntimeSpec {
                symbol: "$weak_set_has",
                deps: &[RuntimeFn::StrictEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::WeakSetDelete => RuntimeSpec {
                symbol: "$weak_set_delete",
                deps: &[RuntimeFn::StrictEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
