// Domain: Number -- auto-generated.
// Regenerate with: python3 scripts/refactor/extract-runtime-domains.py

            Self::NumberFromI32 => RuntimeSpec {
                symbol: "$number_from_i32",
                deps: NUMBER_FROM_I32_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::NumberToExponential => RuntimeSpec {
                symbol: "$value_to_string_into",
                deps: VTS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: VTS_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::NumberToFixed => RuntimeSpec {
                symbol: "$value_to_string_into",
                deps: VTS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: VTS_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::NumberToPrecision => RuntimeSpec {
                symbol: "$value_to_string_into",
                deps: VTS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: VTS_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::NumberToI32 => RuntimeSpec {
                symbol: "$number_to_i32",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::NumberIsNaN => RuntimeSpec {
                symbol: "$number_is_nan",
                deps: &[RuntimeFn::IsNaN],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::NumberIsFinite => RuntimeSpec {
                symbol: "$number_is_finite",
                deps: &[RuntimeFn::IsFinite],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::NumberIsInteger => RuntimeSpec {
                symbol: "$number_is_integer",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::NumberIsSafeInteger => RuntimeSpec {
                symbol: "$number_is_safe_integer",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
