// Domain: Object -- auto-generated.
// Regenerate with: python3 scripts/refactor/extract-runtime-domains.py

            Self::PropertyGet => RuntimeSpec {
                symbol: "$property_get",
                deps: &[Self::MemEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PropertySet => RuntimeSpec {
                symbol: "$property_set",
                deps: &[Self::AllocHeap, Self::Copy, Self::MemEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PropertyDelete => RuntimeSpec {
                symbol: "$property_delete",
                deps: &[Self::MemEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PropertyHas => RuntimeSpec {
                symbol: "$property_has",
                deps: &[Self::MemEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectKeys => RuntimeSpec {
                symbol: "$object_keys",
                deps: OBJECT_KEYS_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectSpread => RuntimeSpec {
                symbol: "$object_spread",
                deps: OBJECT_SPREAD_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::SpreadViaIterator => RuntimeSpec {
                symbol: "$spread_via_iterator",
                deps: &[],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectValues => RuntimeSpec {
                symbol: "$object_values",
                deps: OBJECT_VALUES_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectEntries => RuntimeSpec {
                symbol: "$object_entries",
                deps: OBJECT_ENTRIES_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectHasOwnProperty => RuntimeSpec {
                symbol: "$object_has_own_property",
                deps: OBJECT_HAS_OWN_PROPERTY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectHasOwn => RuntimeSpec {
                symbol: "$object_has_own",
                deps: OBJECT_HAS_OWN_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectGetOwnPropertyDescriptor => RuntimeSpec {
                symbol: "$object_get_own_property_descriptor",
                deps: OBJECT_GET_OWN_PROPERTY_DESCRIPTOR_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectGetPrototypeOf => RuntimeSpec {
                symbol: "$object_get_prototype_of",
                deps: OBJECT_PROTOTYPE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectSetPrototypeOf => RuntimeSpec {
                symbol: "$object_set_prototype_of",
                deps: OBJECT_PROTOTYPE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectFreeze => RuntimeSpec {
                symbol: "$object_freeze",
                deps: OBJECT_FREEZE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectSeal => RuntimeSpec {
                symbol: "$object_seal",
                deps: OBJECT_SEAL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectPreventExtensions => RuntimeSpec {
                symbol: "$object_prevent_extensions",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectIsExtensible => RuntimeSpec {
                symbol: "$object_is_extensible",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectIsSealed => RuntimeSpec {
                symbol: "$object_is_sealed",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectIsFrozen => RuntimeSpec {
                symbol: "$object_is_frozen",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectDefineProperty => RuntimeSpec {
                symbol: "$object_define_property",
                deps: OBJECT_DEFINE_PROPERTY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectAssign => RuntimeSpec {
                symbol: "$object_assign",
                deps: OBJECT_ASSIGN_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectCreate => RuntimeSpec {
                symbol: "$object_create",
                deps: OBJECT_CREATE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::ObjectIs => RuntimeSpec {
                symbol: "$object_is",
                deps: &[
                    Self::IsString,
                    Self::StringEqual,
                    Self::BigIntCompare,
                    Self::NumberToI32,
                ],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
