// Domain: Promise -- auto-generated.
// Regenerate with: python3 scripts/refactor/extract-runtime-domains.py

            Self::PromiseConstructor => RuntimeSpec {
                symbol: "$promise_constructor",
                deps: &[Self::AllocHeap],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PromiseResolve => RuntimeSpec {
                symbol: "$promise_resolve",
                deps: &[Self::AllocHeap],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PromiseReject => RuntimeSpec {
                symbol: "$promise_reject",
                deps: &[Self::AllocHeap],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PromiseThen => RuntimeSpec {
                symbol: "$promise_then",
                deps: &[Self::AllocHeap, Self::StrictEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PromiseCatch => RuntimeSpec {
                symbol: "$promise_catch",
                deps: &[Self::StrictEqual],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PromiseAll => RuntimeSpec {
                symbol: "$promise_all",
                deps: &[Self::AllocHeap],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::PromiseRace => RuntimeSpec {
                symbol: "$promise_race",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
