// Domain: String -- auto-generated.
// Regenerate with: python3 scripts/refactor/extract-runtime-domains.py

            Self::StringEqual => RuntimeSpec {
                symbol: "$string_equal",
                deps: STRING_EQUAL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::Concat => RuntimeSpec {
                symbol: "$concat",
                deps: CONCAT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringCharAt => RuntimeSpec {
                symbol: "$string_char_at",
                deps: STRING_CHAR_AT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringAt => RuntimeSpec {
                symbol: "$string_at",
                deps: STRING_AT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringSubstring => RuntimeSpec {
                symbol: "$string_substring",
                deps: STRING_SUBSTRING_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringSubstr => RuntimeSpec {
                symbol: "$string_substr",
                deps: STRING_SUBSTR_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringSlice => RuntimeSpec {
                symbol: "$string_slice",
                deps: STRING_SLICE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringIndexOf => RuntimeSpec {
                symbol: "$string_index_of",
                deps: STRING_INDEX_OF_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringLastIndexOf => RuntimeSpec {
                symbol: "$string_last_index_of",
                deps: STRING_LAST_INDEX_OF_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringLocaleCompare => RuntimeSpec {
                symbol: "$string_locale_compare",
                deps: STRING_LOCALE_COMPARE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringIncludes => RuntimeSpec {
                symbol: "$string_includes",
                deps: STRING_INCLUDES_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringPadStart => RuntimeSpec {
                symbol: "$string_pad_start",
                deps: STRING_PAD_START_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringPadEnd => RuntimeSpec {
                symbol: "$string_pad_end",
                deps: STRING_PAD_END_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringRepeat => RuntimeSpec {
                symbol: "$string_repeat",
                deps: STRING_REPEAT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringSplit => RuntimeSpec {
                symbol: "$string_split",
                deps: STRING_SPLIT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringTrim => RuntimeSpec {
                symbol: "$string_trim",
                deps: STRING_TRIM_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringTrimStart => RuntimeSpec {
                symbol: "$string_trim_start",
                deps: STRING_TRIM_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringTrimEnd => RuntimeSpec {
                symbol: "$string_trim_end",
                deps: STRING_TRIM_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringStartsWith => RuntimeSpec {
                symbol: "$string_starts_with",
                deps: STRING_STARTS_WITH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringEndsWith => RuntimeSpec {
                symbol: "$string_ends_with",
                deps: STRING_ENDS_WITH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringMatch => RuntimeSpec {
                symbol: "$string_match",
                deps: STRING_MATCH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringSearch => RuntimeSpec {
                symbol: "$string_search",
                deps: STRING_SEARCH_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringToUpperCase => RuntimeSpec {
                symbol: "$string_to_upper_case",
                deps: STRING_TO_UPPER_CASE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringToLowerCase => RuntimeSpec {
                symbol: "$string_to_lower_case",
                deps: STRING_TO_LOWER_CASE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringCharCodeAt => RuntimeSpec {
                symbol: "$string_char_code_at",
                deps: STRING_CHAR_CODE_AT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringCodePointAt => RuntimeSpec {
                symbol: "$string_code_point_at",
                deps: STRING_CODE_POINT_AT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringIsWellFormed => RuntimeSpec {
                symbol: "$string_is_well_formed",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringToWellFormed => RuntimeSpec {
                symbol: "$string_to_well_formed",
                deps: NO_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringFromCharCode => RuntimeSpec {
                symbol: "$string_from_char_code",
                deps: STRING_FROM_CHAR_CODE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringFromCodePoint => RuntimeSpec {
                symbol: "$string_from_code_point",
                deps: STRING_FROM_CODE_POINT_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringReplace => RuntimeSpec {
                symbol: "$string_replace",
                deps: STRING_REPLACE_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::StringReplaceAll => RuntimeSpec {
                symbol: "$string_replace_all",
                deps: STRING_REPLACE_ALL_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
