// Domain: TypedArray -- auto-generated.
// Regenerate with: python3 scripts/refactor/extract-runtime-domains.py

            Self::TypedArrayFromArray => RuntimeSpec {
                symbol: "$typed_array_from_array",
                deps: TYPED_ARRAY_FROM_ARRAY_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DataViewNew => RuntimeSpec {
                symbol: "$dataview_new",
                deps: DATAVIEW_NEW_DEPS,
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DataViewGetInt32 => RuntimeSpec {
                symbol: "$dataview_get_int32",
                deps: &[],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DataViewSetInt32 => RuntimeSpec {
                symbol: "$dataview_set_int32",
                deps: &[],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::EffectOnly,
            },
            Self::DataViewGetFloat64 => RuntimeSpec {
                symbol: "$dataview_get_float64",
                deps: &[],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::Value,
            },
            Self::DataViewSetFloat64 => RuntimeSpec {
                symbol: "$dataview_set_float64",
                deps: &[],
                imports: NO_IMPORTS,
                capability: NO_CAPS,
                runtime_strings: NO_RUNTIME_STRINGS,
                result: RuntimeResult::EffectOnly,
            },
