#!/usr/bin/env python3
"""Semantic Regression Gate: detect regression in per-feature coverage.

Compares the current semantic coverage baseline (generated by
scripts/dashboard/semantic-coverage.py) against the stored baseline in
docs/current-state.md. Exits non-zero if regression is detected.

Regression conditions:
  - Fewer feature areas covered (total dir count decreased)
  - Fewer passing feature areas (pass count decreased)
  - Fewer total fixture files
  - Any feature that was "pass" is now "unknown" (regression)

On success, updates the baseline in docs/current-state.md.

Usage:
  python3 scripts/gate/semantic-regression.py                     # compare + update baseline
  python3 scripts/gate/semantic-regression.py --baseline-only     # only update baseline, no compare
  python3 scripts/gate/semantic-regression.py --help              # this help
"""

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).parent.parent.parent.resolve()
CURRENT_STATE_PATH = REPO_ROOT / "docs" / "current-state.md"

# Regex to extract JSON baseline embedded in current-state.md
BASELINE_MARKER_START = "<!-- semantic-coverage-baseline:start -->"
BASELINE_MARKER_END = "<!-- semantic-coverage-baseline:end -->"


def load_current_baseline() -> dict[str, Any] | None:
    """Load the current baseline from docs/current-state.md."""
    if not CURRENT_STATE_PATH.exists():
        return None

    content = CURRENT_STATE_PATH.read_text(encoding="utf-8")
    start_idx = content.find(BASELINE_MARKER_START)
    end_idx = content.find(BASELINE_MARKER_END)

    if start_idx == -1 or end_idx == -1:
        return None

    json_start = content.index("\n", start_idx) + 1
    json_block = content[json_start:end_idx].strip()

    try:
        return json.loads(json_block)
    except json.JSONDecodeError:
        print("ERROR: failed to parse baseline JSON in current-state.md", file=sys.stderr)
        return None


def run_semantic_coverage_baseline() -> dict[str, Any]:
    """Run the semantic coverage dashboard script to get current baseline."""
    dashboard_script = (
        REPO_ROOT / "scripts" / "dashboard" / "semantic-coverage.py"
    )
    if not dashboard_script.exists():
        print(f"ERROR: dashboard script not found: {dashboard_script}", file=sys.stderr)
        sys.exit(1)

    import subprocess

    result = subprocess.run(
        [sys.executable, str(dashboard_script), "--baseline"],
        capture_output=True,
        text=True,
        cwd=str(REPO_ROOT),
    )

    if result.returncode != 0:
        print(
            f"ERROR: semantic-coverage.py failed:\n{result.stderr}",
            file=sys.stderr,
        )
        sys.exit(1)

    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError as e:
        print(f"ERROR: failed to parse baseline JSON: {e}", file=sys.stderr)
        print(f"stdout was: {result.stdout[:500]}", file=sys.stderr)
        sys.exit(1)


def update_baseline_in_docs(baseline: dict[str, Any]) -> None:
    """Replace or append the baseline block in docs/current-state.md."""
    block = (
        f"{BASELINE_MARKER_START}\n"
        f"{json.dumps(baseline, indent=2, ensure_ascii=False)}\n"
        f"{BASELINE_MARKER_END}"
    )

    if not CURRENT_STATE_PATH.exists():
        # Create file with baseline
        CURRENT_STATE_PATH.write_text(
            f"# Current State\n\n## Semantic Coverage Baseline\n\n{block}\n",
            encoding="utf-8",
        )
        print(f"Created baseline in {CURRENT_STATE_PATH}", file=sys.stderr)
        return

    content = CURRENT_STATE_PATH.read_text(encoding="utf-8")
    start_idx = content.find(BASELINE_MARKER_START)
    end_idx = content.find(BASELINE_MARKER_END)

    if start_idx != -1 and end_idx != -1:
        # Replace existing block
        end_of_block = content.index("\n", end_idx) + 1 if "\n" in content[end_idx:] else len(content)
        new_content = content[:start_idx] + block + content[end_of_block:]
    else:
        # Append baseline section before the final newline
        if content.endswith("\n"):
            new_content = content + f"\n## Semantic Coverage Baseline\n\n{block}\n"
        else:
            new_content = content + f"\n\n## Semantic Coverage Baseline\n\n{block}\n"

    CURRENT_STATE_PATH.write_text(new_content, encoding="utf-8")
    print(f"Updated baseline in {CURRENT_STATE_PATH}", file=sys.stderr)


def detect_regression(
    current: dict[str, Any],
    baseline: dict[str, Any],
) -> list[str]:
    """Compare current vs baseline and return list of regression messages.

    Returns empty list if no regression.
    """
    regressions: list[str] = []

    # Compare feature count
    cur_feat = current.get("feature_count", 0)
    base_feat = baseline.get("feature_count", 0)
    if cur_feat < base_feat:
        regressions.append(
            f"Feature areas decreased: {base_feat} -> {cur_feat}"
        )

    # Compare pass count
    cur_pass = current.get("pass_count", 0)
    base_pass = baseline.get("pass_count", 0)
    if cur_pass < base_pass:
        regressions.append(
            f"Passing feature areas decreased: {base_pass} -> {cur_pass}"
        )

    # Compare total fixtures
    cur_total = current.get("total_fixtures", 0)
    base_total = baseline.get("total_fixtures", 0)
    if cur_total < base_total:
        regressions.append(
            f"Total fixtures decreased: {base_total} -> {cur_total}"
        )

    # Compare pass fixtures
    cur_pass_fixtures = current.get("pass_fixtures", 0)
    base_pass_fixtures = baseline.get("pass_fixtures", 0)
    if cur_pass_fixtures < base_pass_fixtures:
        regressions.append(
            f"Pass fixtures decreased: {base_pass_fixtures} -> {cur_pass_fixtures}"
        )

    # Check per-feature regression: a feature that was "pass" is now not "pass"
    current_features = current.get("features", {})
    baseline_features = baseline.get("features", {})

    for feat_name, base_status in sorted(baseline_features.items()):
        if base_status == "pass":
            cur_status = current_features.get(feat_name, "missing")
            if cur_status != "pass":
                regressions.append(
                    f"Feature '{feat_name}': pass -> {cur_status} (REGRESSION)"
                )

    return regressions


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Semantic regression gate: detect feature coverage regression",
        add_help=False,
    )
    parser.add_argument("--baseline-only", action="store_true", help="Only update baseline, no comparison")
    parser.add_argument("--help", action="store_true", help="Show help and exit")

    args, _unknown = parser.parse_known_args()

    if args.help:
        print(__doc__)
        return 0

    # Always get current coverage
    current_baseline = run_semantic_coverage_baseline()

    if args.baseline_only:
        current_baseline["timestamp"] = datetime.now(timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )
        update_baseline_in_docs(current_baseline)
        print("Baseline updated (no comparison performed)", file=sys.stderr)
        return 0

    # Load existing baseline
    stored_baseline = load_current_baseline()

    if stored_baseline is None:
        print(
            "No existing baseline found. Creating initial baseline.",
            file=sys.stderr,
        )
        update_baseline_in_docs(current_baseline)
        print(
            f"Initial baseline: {current_baseline['feature_count']} features, "
            f"{current_baseline['pass_count']} pass, "
            f"{current_baseline['total_fixtures']} total fixtures",
            file=sys.stderr,
        )
        return 0

    # Detect regression
    regressions = detect_regression(current_baseline, stored_baseline)

    if regressions:
        print("SEMANTIC REGRESSION DETECTED:", file=sys.stderr)
        for msg in regressions:
            print(f"  - {msg}", file=sys.stderr)
        print("Baseline NOT updated.", file=sys.stderr)
        return 1

    # No regression: update baseline
    current_baseline["timestamp"] = datetime.now(timezone.utc).strftime(
        "%Y-%m-%dT%H:%M:%SZ"
    )
    update_baseline_in_docs(current_baseline)

    print(
        f"No regression detected. "
        f"{current_baseline['feature_count']} features, "
        f"{current_baseline['pass_count']} pass, "
        f"{current_baseline['total_fixtures']} total fixtures.",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
