// Domain: BigInt -- auto-generated.
// Regenerate with: python3 scripts/refactor/extract-runtime-domains.py

            Self::MakeBigIntLiteral => "make_bigint_literal",
            Self::BigIntToString => "bigint_to_string",
            Self::BigIntToBoolean => "bigint_to_boolean",
            Self::BigIntFromValue => "bigint_from_value",
            Self::BigIntAsIntN => "bigint_as_int_n",
            Self::BigIntAsUintN => "bigint_as_uint_n",
            Self::BigIntUnaryMinus => "bigint_unary_minus",
            Self::BigIntAdd => "bigint_add",
            Self::BigIntSub => "bigint_sub",
            Self::BigIntMul => "bigint_mul",
            Self::BigIntPow => "bigint_pow",
            Self::BigIntDiv => "bigint_div",
            Self::BigIntRem => "bigint_rem",
            Self::BigIntDivisionByZeroRangeError => "bigint_division_by_zero_range_error",
            Self::BigIntMixedArithmeticTypeError => "bigint_mixed_arithmetic_type_error",
            Self::BigIntStringComparisonBoundaryError => "bigint_string_comparison_boundary_error",
            Self::BigIntBitwiseNot => "bigint_bitwise_not",
            Self::BigIntBitwiseAnd => "bigint_bitwise_and",
            Self::BigIntBitwiseOr => "bigint_bitwise_or",
            Self::BigIntBitwiseXor => "bigint_bitwise_xor",
            Self::BigIntLeftShift => "bigint_left_shift",
            Self::BigIntRightShift => "bigint_right_shift",
            Self::BigIntCompare => "bigint_compare",
