// Domain: Date -- auto-generated.
// Regenerate with: python3 scripts/refactor/extract-runtime-domains.py

            Self::DateNew => "date_new",
            Self::DateNewLive => "date_new_live",
            Self::DateNow => "date_now",
            Self::DateEpochMsNowNumber => "date_epoch_ms_now_number",
            Self::DateGetTime => "date_get_time",
            Self::DateToString => "date_to_string",
            Self::DateGetLocalTimeField => "date_get_local_time_field",
            Self::DateToISOString => "date_to_iso_string",
            Self::DateGetTimezoneOffset => "date_get_timezone_offset",
            Self::DateGetUtcMilliseconds => "date_get_utc_milliseconds",
            Self::DateGetUtcSeconds => "date_get_utc_seconds",
            Self::DateGetUtcMinutes => "date_get_utc_minutes",
            Self::DateGetUtcHours => "date_get_utc_hours",
            Self::DateGetUtcDay => "date_get_utc_day",
            Self::DateGetUtcDate => "date_get_utc_date",
            Self::DateGetUtcMonth => "date_get_utc_month",
            Self::DateGetUtcFullYear => "date_get_utc_full_year",
