// Domain: MapSet -- auto-generated.
// Regenerate with: python3 scripts/refactor/extract-runtime-domains.py

            Self::MapNew => "map_new",
            Self::MapGet => "map_get",
            Self::MapSet => "map_set",
            Self::MapHas => "map_has",
            Self::MapDelete => "map_delete",
            Self::MapValuesArray => "map_values_array",
            Self::SetNew => "set_new",
            Self::SetAdd => "set_add",
            Self::SetHas => "set_has",
            Self::SetDelete => "set_delete",
            Self::SetSize => "set_size",
            Self::SetClear => "set_clear",
            Self::SetForEach => "set_for_each",
            Self::MapClear => "map_clear",
            Self::MapSize => "map_size",
            Self::MapForEach => "map_for_each",
            Self::MapEntriesArray => "map_entries_array",
            Self::SetFromArray => "set_from_array",
            Self::SetValuesArray => "set_values_array",
            Self::SetPrototypeAddGet => "set_prototype_add_get",
            Self::SetPrototypeAddSet => "set_prototype_add_set",
            Self::WeakMapNew => "weak_map_new",
            Self::WeakMapSet => "weak_map_set",
            Self::WeakMapGet => "weak_map_get",
            Self::WeakMapHas => "weak_map_has",
            Self::WeakMapDelete => "weak_map_delete",
            Self::WeakSetNew => "weak_set_new",
            Self::WeakSetAdd => "weak_set_add",
            Self::WeakSetHas => "weak_set_has",
            Self::WeakSetDelete => "weak_set_delete",
