// Domain: Object -- auto-generated.
// Regenerate with: python3 scripts/refactor/extract-runtime-domains.py

            Self::PropertyGet => "property_get",
            Self::PropertySet => "property_set",
            Self::PropertyDelete => "property_delete",
            Self::PropertyHas => "property_has",
            Self::ObjectKeys => "object_keys",
            Self::ObjectSpread => "object_spread",
            Self::SpreadViaIterator => "spread_via_iterator",
            Self::ObjectValues => "object_values",
            Self::ObjectEntries => "object_entries",
            Self::ObjectHasOwnProperty => "object_has_own_property",
            Self::ObjectHasOwn => "object_has_own",
            Self::ObjectGetOwnPropertyDescriptor => "object_get_own_property_descriptor",
            Self::ObjectGetPrototypeOf => "object_get_prototype_of",
            Self::ObjectSetPrototypeOf => "object_set_prototype_of",
            Self::ObjectFreeze => "object_freeze",
            Self::ObjectSeal => "object_seal",
            Self::ObjectPreventExtensions => "object_prevent_extensions",
            Self::ObjectIsExtensible => "object_is_extensible",
            Self::ObjectIsSealed => "object_is_sealed",
            Self::ObjectIsFrozen => "object_is_frozen",
            Self::ObjectDefineProperty => "object_define_property",
            Self::ObjectAssign => "object_assign",
            Self::ObjectCreate => "object_create",
            Self::ObjectIs => "object_is",
