// Domain: Operator -- auto-generated.
// Regenerate with: python3 scripts/refactor/extract-runtime-domains.py

            Self::Add => "add",
            Self::AddFast => "add_fast",
            Self::Sub => "sub",
            Self::SubFast => "sub_fast",
            Self::Mul => "mul",
            Self::MulFast => "mul_fast",
            Self::Div => "div",
            Self::DivFast => "div_fast",
            Self::Mod => "mod",
            Self::ModFast => "mod_fast",
            Self::BitwiseToI32 => "bitwise_to_i32",
            Self::BitwiseAnd => "bitwise_and",
            Self::BitwiseXor => "bitwise_xor",
            Self::BitwiseOr => "bitwise_or",
            Self::Negate => "negate",
            Self::Less => "less",
            Self::LessFast => "less_fast",
            Self::LessEqual => "less_equal",
            Self::LessEqualFast => "less_equal_fast",
            Self::Greater => "greater",
            Self::GreaterFast => "greater_fast",
            Self::GreaterEqual => "greater_equal",
            Self::GreaterEqualFast => "greater_equal_fast",
            Self::StrictEqual => "strict_equal",
            Self::EqualEqual => "equal_equal",
            Self::BangEqual => "bang_equal",
            Self::StrictNotEqual => "strict_not_equal",
            Self::And => "and",
            Self::Or => "or",
