// Domain: String -- auto-generated.
// Regenerate with: python3 scripts/refactor/extract-runtime-domains.py

            Self::StringEqual => "string_equal",
            Self::Concat => "concat",
            Self::StringCharAt => "string_char_at",
            Self::StringAt => "string_at",
            Self::StringSubstring => "string_substring",
            Self::StringSubstr => "string_substr",
            Self::StringSlice => "string_slice",
            Self::StringIndexOf => "string_index_of",
            Self::StringLastIndexOf => "string_last_index_of",
            Self::StringLocaleCompare => "string_locale_compare",
            Self::StringIncludes => "string_includes",
            Self::StringPadStart => "string_pad_start",
            Self::StringPadEnd => "string_pad_end",
            Self::StringRepeat => "string_repeat",
            Self::StringSplit => "string_split",
            Self::StringTrim => "string_trim",
            Self::StringTrimStart => "string_trim_start",
            Self::StringTrimEnd => "string_trim_end",
            Self::StringStartsWith => "string_starts_with",
            Self::StringEndsWith => "string_ends_with",
            Self::StringMatch => "string_match",
            Self::StringSearch => "string_search",
            Self::StringToUpperCase => "string_to_upper_case",
            Self::StringToLowerCase => "string_to_lower_case",
            Self::StringCharCodeAt => "string_char_code_at",
            Self::StringCodePointAt => "string_code_point_at",
            Self::StringIsWellFormed => "string_is_well_formed",
            Self::StringToWellFormed => "string_to_well_formed",
            Self::StringFromCharCode => "string_from_char_code",
            Self::StringFromCodePoint => "string_from_code_point",
            Self::StringReplace => "string_replace",
            Self::StringReplaceAll => "string_replace_all",
