//! Catalog of RuntimeFn variants handled by the Date domain.
//!
//! Date domain includes: Date, Math, Promise, and Task operations.

#![allow(dead_code)]

use crate::runtime_fn::RuntimeFn;

/// All RuntimeFn variants routed through [`emit_dispatch_date`].
pub const DATE_FUNCTIONS: &[RuntimeFn] = &[
    // Date
    RuntimeFn::DateNew,
    RuntimeFn::DateNewLive,
    RuntimeFn::DateNow,
    RuntimeFn::DateEpochMsNowNumber,
    RuntimeFn::DateGetTime,
    RuntimeFn::DateSetTime,
    RuntimeFn::DateSetUTCFullYear,
    RuntimeFn::DateSetUTCMonth,
    RuntimeFn::DateSetUTCDate,
    RuntimeFn::DateSetUTCHours,
    RuntimeFn::DateSetUTCMinutes,
    RuntimeFn::DateSetUTCSeconds,
    RuntimeFn::DateSetUTCMilliseconds,
    RuntimeFn::DateSetFullYear,
    RuntimeFn::DateSetMonth,
    RuntimeFn::DateSetDate,
    RuntimeFn::DateSetHours,
    RuntimeFn::DateSetMinutes,
    RuntimeFn::DateSetSeconds,
    RuntimeFn::DateSetMilliseconds,
    RuntimeFn::DateParse,
    RuntimeFn::DateUTC,
    RuntimeFn::DateToString,
    RuntimeFn::DateGetLocalTimeField,
    RuntimeFn::DateToISOString,
    RuntimeFn::DateGetTimezoneOffset,
    RuntimeFn::DateToDateString,
    RuntimeFn::DateToTimeString,
    RuntimeFn::DateGetUtcMilliseconds,
    RuntimeFn::DateGetUtcSeconds,
    RuntimeFn::DateGetUtcMinutes,
    RuntimeFn::DateGetUtcHours,
    RuntimeFn::DateGetUtcDay,
    RuntimeFn::DateGetUtcDate,
    RuntimeFn::DateGetUtcMonth,
    RuntimeFn::DateGetUtcFullYear,
    RuntimeFn::IntlDateTimeFormatFormat,
    // Math
    RuntimeFn::MathFloor,
    RuntimeFn::MathCeil,
    RuntimeFn::MathRound,
    RuntimeFn::MathAbs,
    RuntimeFn::MathMax,
    RuntimeFn::MathMin,
    RuntimeFn::MathPow,
    RuntimeFn::MathRandom,
    RuntimeFn::MathTrunc,
    RuntimeFn::MathSign,
    RuntimeFn::MathCbrt,
    RuntimeFn::MathClz32,
    RuntimeFn::MathImul,
    RuntimeFn::MathSqrt,
    RuntimeFn::MathAcos,
    RuntimeFn::MathAcosh,
    RuntimeFn::MathAsin,
    RuntimeFn::MathAsinh,
    RuntimeFn::MathAtan,
    RuntimeFn::MathAtan2,
    RuntimeFn::MathAtanh,
    RuntimeFn::MathCos,
    RuntimeFn::MathCosh,
    RuntimeFn::MathExp,
    RuntimeFn::MathExpm1,
    RuntimeFn::MathFround,
    RuntimeFn::MathHypot,
    RuntimeFn::MathLog,
    RuntimeFn::MathLog10,
    RuntimeFn::MathLog1p,
    RuntimeFn::MathLog2,
    RuntimeFn::MathSin,
    RuntimeFn::MathSinh,
    RuntimeFn::MathTan,
    RuntimeFn::MathTanh,
    // Promise
    RuntimeFn::PromiseConstructor,
    RuntimeFn::PromiseResolve,
    RuntimeFn::PromiseReject,
    RuntimeFn::PromiseThen,
    RuntimeFn::PromiseCatch,
    RuntimeFn::PromiseFinally,
    RuntimeFn::PromiseAll,
    RuntimeFn::PromiseAllSettled,
    RuntimeFn::PromiseAny,
    RuntimeFn::PromiseRace,
    RuntimeFn::PromiseWithResolvers,
    RuntimeFn::AggregateError,
    // Task
    RuntimeFn::TaskPoll,
    RuntimeFn::TaskResult,
    RuntimeFn::TaskDrop,
];
